### ISSUE TITLE
Service fails while stopping

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1005]
Dear osparc support team
I encountered a rather new behavior. I was closing my study for the upcoming release to staging. However when I stopped my service, it failed while stopping it. normally this happens when I attempt starting it^^ 
its on tip-staging

these are the logs:
09:22:06Stopping simcore/services/dynamic/jupyter-smash:3.0.16...
09:25:20Service failed: Upss! This service (dy-sidecar_5ebeaa40-af10-4732-af60-f95f2df6e216) unexpectedly failed [OEC:140274748677216]
_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/3enpuh7933nhibq4y4dgexcqcy) *by `@msteiner`*._

**Comment by elisabettai** [comment]
@pcrespov feel free to close when you're done investigating and/or link other issues (if known).

**Comment by pcrespov** [comment]
- storage was not connecting the db -> @GitHK restarted service and solved the issue
- @GitHK retried saving data and succeeded
- @matusdrobuliak66 continues with release to staging
