### ISSUE TITLE
Registration error: confirmation link doesn't work

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1009]
I registered my account (user_email), and I'm receiving an email "Welcome to oSPARC" to confirm the registration and activate the account. However, if I click on the link (To complete your registration please click here...), I am immediately redirected to [http://osparc.io](http://osparc.io/), but nothing else happens.

If I try to log in using my credentials, the login fails, stating that I need to activate the account. So, clicking on the activation link failed. What is going wrong here? Note that the activation mail is 7 days old already. Not sure if the activation expired because of this.

![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/59275a32-c4ad-4b52-b4a3-151d460b8aa3)

**Comment by elisabettai** [comment]
@pcrespov, any idea on how we can solve this? Check our team chat for details.
Otherwise maybe we should just send him another invitation link? But we would need to remove the existing entry from the DB.

**Comment by pcrespov** [comment]
- confirmation code for `REGISTRATION` expired and was deleted from db
- solved by regenerating a new code (currently still not possible from front-end)
