### ISSUE TITLE
Login cookie expiration 

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1010]
It looks like osparc login cookie never expires. 

Maybe it is safer (best practice?) to add an expiration time after which the user has to login again. Most websites that require a login have that. Also sister platforms (e.g. DAT-Core Pennsieve) have that.

Also metrics-wise, it might be of interest to count how often users login into the platform (right now we're getting lower numbers because users have forever-lasting cookies).

**Comment by elisabettai** [comment]
@pcrespov, I imagine that was already discussed in the team in the past. Happy to read/hear your thoughts about this.

**Comment by pcrespov** [comment]
> @pcrespov, I imagine that was already discussed in the team in the past. Happy to read/hear your thoughts about this.

yes, we looked into it. It is feasible and not a big overload

**Comment by elisabettai** [comment]
Thanks @pcrespov! Should we then add then a default expiration? What would be reasonable, maybe 7 days? I thought initially 24h, but some power-users might have studies opened for more than 1 day.

I am assuming that when the login cookie expires, then the user is automatically logged out, but I am not sure.

**Comment by pcrespov** [comment]
@elisabettai l would read around what are the best practices. Just design some model and we can implement it

**Comment by pcrespov** [comment]
@elisabettai This issue resolved with https://github.com/ITISFoundation/osparc-simcore/pull/4947
