### ISSUE TITLE
Study info page has big empty space if study is set up in App Mode

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1016]
It would be nice to don't show the empty space at all (move all up?)
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/90fcbe43-ec32-4a01-a6e1-0c27f6fd218c)

**Comment by odeimaiz** [comment]
That GUI was was deprecated

**Comment by elisabettai** [comment]
Yep, it has changed (also in production), but it still looks like that:
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/f16a9541-f77c-4c44-998f-6a5c3a769a09)

**Comment by elisabettai** [comment]
Now the preview looks better, closing this.
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/5b29abbe-3dbd-4037-a672-940f56744583)
