### ISSUE TITLE
Privacy: Encryption of Data

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#1031]
## Description

In the context of User Privacy (#1030), it has been discussed and decided that certain parts of the stored user data and projects shall be encrypted.

The kind of and the level/depth and coverage of the encryption necessary in a first step shall be assessed and proposed by the Team, based on its technical knowledge (done via Sim4Life or S3, etc.).

We envision a meaningful trade-off between implementation effort, security/privacy and user experience (loading times of projects, etc.).

```[tasklist]
### Sundae
- [x] figure out how feasable it is to use rclone for this @GitHK
```

```[tasklist]
### Baklava
- [ ] Add AWS-based S3 bucket encryption @mrnicegyu11 @YuryHrytsuk
```

**Comment by GitHK** [comment]
we might be able to get over this one if we use https://rclone.org/crypt/
For this to work all across we also need to move inputs/outputs (aka file uploads to rclone)

**Comment by GitHK** [comment]
Conclusions after my investigation:
 
- If encryption is required at file level, it is possible to do so by using rclone.
- It has some caveats, and we'll have to do it on a per node basis.
- nodeports will require a some major overhauling to support encrypted transfers.
- nodeports will need to transfer also single files via rclone when encryption is enabled.
- we will require a service for storing encryption keys
- if we are very nice about it we might want to support an unlock feature (like the password you use to unlock the iPhone, which is part of the key used to encrypt the data). this has further complications, if the users forget it, their data will be lost. But at last nobody can decrypt it.

**Comment by pcrespov** [comment]
As agreed during the PM1, closing on behalf of @drniiken
