### ISSUE TITLE
Implementation of "payment infrastructure", API comm w/ backend, etc. @odeimaiz @matusdrobuliak66

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-issues#1041]

**Comment by SCA-ZMT** [comment]
@elisabettai is this still open?

**Comment by matusdrobuliak66** [comment]
All remaining issue with payment infrastructure/resource tracking are tracked https://github.com/ITISFoundation/osparc-issues/issues/1307 therefore closing this issue for duplication
