### ISSUE TITLE
Service autostart UI improvements

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1042]
Team Black suggestion on this:
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/271ab10b-34b0-4a1f-810f-f601b5161566)

1. Instead of the current "Disable Service Autostart" it might be clearer to rename it to "Service Autostart" and use a toggle button instead of the "check button" to turn it on/off
2. Adding this option in the secondary column in the workbench might help making it more visible.

**Comment by elisabettai** [comment]
What do you think, @odeimaiz?

**Comment by odeimaiz** [comment]
- We can rename it 👍 
- I like the checkbox more than the toggle button, I think it's more clear.

**Comment by elisabettai** [comment]
- If you rename it, I'd propose: "Autostart services" and then the default is to have the check box checked. In this way the current behavior stays. 
- We were thinking to have it as it is (in the Study Info page) and **in addition** in the secondary column. Just a suggestion to have users noticing this option. Up to you. 😉

**Comment by elisabettai** [comment]
Let's see what Team Black thinks about the new implementation.
