### ISSUE TITLE
Studies with old services are not updatable nor deletable nor selectable

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#1046]
**Long Story Short**

After re-deployment of AWS-staging, some service images disappeared.
Some "old" studies are showing that they use services that are inexistent.

![image](https://github.com/ITISFoundation/osparc-issues/assets/35365065/3433a3a4-856e-4962-a0e2-413c3e7a54f7)

**Expected Behavior**

I would expect that I can update the services if some are available, or even remove that study from the dashboard.
**Actual behaviour**

I cannot select the study or inspect its services. Therefore there is no way of updating the services inside if newer ones are available.
**Steps to reproduce**

**Environment**

**Additional context**

**Comment by odeimaiz** [comment]
Fixed a couple of sprints ago 👌
