### ISSUE TITLE
Save a 2FA method

### ISSUE THREAD

**Issue by cosfor1** [ITISFoundation/osparc-issues#1053]
In sim4life.io, would it be possible, when I login, to have a checkbox that allows me to say "use this from now on" for the 2FA method?, without having always to specify skip sms message and send code via email, for instance?

Thank you,\
Cosimo

**Comment by elisabettai** [comment]
@GitHK, do you think this can be tackled once you have [this](https://github.com/ITISFoundation/osparc-issues/issues/954)? I guess that would be a new preference, in addition to the one we have already in the frontend.

**Comment by GitHK** [comment]
once this is closed https://github.com/ITISFoundation/osparc-issues/issues/1062 this issue can be tackled

**Comment by GitHK** [comment]
@odeimaiz this can now be picked up

**Comment by odeimaiz** [comment]
@pcrespov @GitHK yes, it can now be implemented.

**Comment by pcrespov** [comment]
@cosfor1 can you provide me with some example of app where the 2FA (if active) is only used once for the log in? AFAIK the 2FA is part of the login workflow (together with the user/password or any other type of auth) . Another story is that you as a user can enable/disable that step for login.

**Comment by newton1985** [comment]
In addition, I'd like to make sure that we waive the need to wait 60 seconds (if that wasn't already intended for users who select the email always preference)

**Comment by elisabettai** [comment]
@newton1985, I did the 2 factor-authentication via email just now. You don't need to wait 60' if you go with email right away (instead of first trying with SMS and than with email).
