### ISSUE TITLE
Adding/removing collaborators from a Template gives an error

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1064]
There's a frontend error, but after refreshing the operation is actually successful.

**Steps to reproduce**
Error 1: Go to an existing template, add an organization-> there's an error in the frontend
Error 2: Go to an existing template, remove one organization -> there's another error in the frontend

**Environment**
Firefox, osparc.io

**Comment by elisabettai** [comment]
fyi, @odeimaiz, @sanderegg. I haven't checked if this still happens on master.

**Comment by odeimaiz** [comment]
The fix is already in staging
