### ISSUE TITLE
Ability to get Study/Service info even if a Study is blocked/locked

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1068]
**Describe the goal**
Since support usually benefits from knowing the Service/Study UUID it would be helpful if users could access this information even if the Study is blocked. At the moment this is not possible. 

**Describe the benefit**
Faster and easier support process.

**Comment by elisabettai** [comment]
Thanks @Konohana0608 for opening this!

When you hover with your mouse on the blocked Study, you should see some message like "Service information missing simcore/...". That should tell which service is causing troubles, but that message is likely not very user-friendly.

To make this more usable also for external users, I'd suggest:
1. Change the message when you hover to something like: "You don't have access to xx service in study uuid. Please contact support to ask access".
2. When users click on the study card, they can see the study info page, so they can copy the study id

fyi @odeimaiz

**Comment by odeimaiz** [comment]
Thanks for you comments. It was already implemented here:
https://github.com/ITISFoundation/osparc-simcore/pull/4599

**Comment by elisabettai** [comment]
Very nice! Some minor tweaks (in the messaging) can make it even more user-friendly.
