### ISSUE TITLE
Wrong sharee permissions

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1076]
@newton1985 shared a study with me on osparc.io (`a4628a32-3419-11ed-9a85-02420a0b01c2`) and got this message.

![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/bbd23d44-2bd3-4b4d-ba9b-7de8ebb1abb7)

But I do see both services in my Services tab.

**Comment by elisabettai** [comment]
I haven't investigated this further yet, but @odeimaiz or @mguidon you've seen this already or have an idea of what's going on?

**Comment by odeimaiz** [comment]
Yes, this feature was required some time ago, and the way it was implemented was not the best.

The frontend doesn't really know if you have access to it or not if the service is not directly shared with you. I guess you only have access to it via an organization...

**Comment by elisabettai** [comment]
And what happens with Services share with "Everyone"?
