### ISSUE TITLE
API Error when downloading files

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1078]
we're following the standard procedure, using a script that is confirmed to work, normally, but we get the classic error:
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/e0ff4f92-869b-4d6c-883a-030a5168bd21)

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/grq76in8itbt3d4pbwk9qscybe) *by `@karimi`*._

**Comment by elisabettai** [comment]
@bisgaard-itis, @pcrespov, this is the issue Fariba reported. Feel free to close when it's solved

**Comment by bisgaard-itis** [comment]
This was solved by the user by inspecting the solver log. Hence, a user issue in the submitted job
