### ISSUE TITLE
May ORCID Authentication

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1091]
Description:
Leveraging the login infrastructure to support login using an ORCID account. To prevent abuse, it might still be necessary to either have a first time approval step, or to demand a phone number (two-factor authentication), or to limit certain functionalities / resources, similarly to how it is also done for anonymous access through the Portal.

Deliverable:
Infrastructure functionality

Acceptance criteria: 
Users with an ORCID account can login to the o²S²PARC platform

Out of scope: –

Deadline:
Q3

++++
Comment NIH:
We'd like to make it as easy as possible for new users to log in. Perhaps a captcha would be best here.
Response SIM-Core:
No. this is about accountability, should they abuse the very open scripting possibilities we offer. i will want a verifiable phone number or a personal check.
Comment NIH:
Can we agree that the login authentication would not involve a manual review step by SIM-Core? Using phone number as an example, the person could get an automated SMS that they would need to reply to in order to validate their number. That type of solution is ok with us, since it doesn't involve a manual review step by SIM-Core.
Response SIM-Core:
That is exactly what i meant with two factor authentication :-)
and we already tested a solution, so this is likely going to be what we implement. expect me to send you phone bills for SMS sending ;-)

[wrike Y7-MS 2.1.2: ORCID Authentication](https://www.wrike.com/open.htm?id=1157509611)

**Comment by pcrespov** [comment]
In the work with map-core we might need the following use-case:
- A user has an orcid account
- it has registered in both portal and osparc
- the user logs in in the portal with orcid. 
- It clicks to run a service (that require login) or uses the API (which requires auth)
- How could we forward the authentication to osparc!??

**Comment by pcrespov** [comment]
@elisabettai can yo update the status on thisone please?

**Comment by elisabettai** [comment]
@pcrespov, apologizes for the late answer (I still don't receive notifications for mentions in GitHub 🤦🏻‍♀️ 😞 , my fault).

This is dropped. Below our official statement (approved by NIH).

Y7Q3 Status update (06/17/2024): Delayed
Implementation: This milestone is delayed. While we have done significant work on adding security layers to the account requests process (i.e. by adding a captcha) and improving the user experience with the two factor authentication #1090, infrastructure to allow users to directly login with an ORCiD is still to be developed. 

Justification: The effort of realizing the proposed login infrastructure is high and in view of the important feedback received on usability and performance, following the release of the o2S2PARC-based Sim4Life web-version, addressing these was prioritized (for a more detailed discussion, see the Interim Report). We suggest that the refactoring of login functionality be dropped at the current time. This can also be justified by the need for better user screening (i.e., person in the loop), once o2S2PARC switches into sustainability mode (i.e., costs start to be attributed to users). 

Mitigation: The priority at which registration requests are handled was increased, resulting in reduced wait times.
