### ISSUE TITLE
May: Facilitation of Service Creation

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1092]
## Description:
- very simple creation of services that map inputs (and capture outputs) to a command-line-interface (CLI) application and execute it (many scientific software satisfy this criterion and could then easily be onboarded by users; standards from the common workflow language (CWL) could be leveraged)
- simple creation of a service from a Python function adhering to a standardized interface (Python annotations)

## Deliverable:
Infrastructure for service creation

## Acceptance criteria:
The process for creating new services based on CLI, annotated Python, or JupyterLab flavors is strongly simplified (for at least two out of these three)

## Out of scope:
No dedicated GUI

## Deadline:
Q3

[wrike Y7-MS 3.1.1: Facilitation of Service Creation](https://www.wrike.com/open.htm?id=1155713271)
```[tasklist]
### Proposal of tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1383
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1458
```

**Comment by esraneufeld** [comment]
complete at least the jupyter one for the milestone deadline. preferably also progress on one of the other two

**Comment by elisabettai** [comment]
### Update Sprint Enchanted Odyssey
- A new cookiecutter for streamlined creation of JupyterLab-based services has been created, see code [here](https://github.com/ITISFoundation/cookiecutter-osparc-jupyterlab-service).
- The new cookiecutter has been tested and refined by creating the following 3 new services:
-- [JupyterLab SPARC](https://github.com/ITISFoundation/jupyterlab-sparc): Python environment with the [SPARC Python Client](https://github.com/ITISFoundation/jupyterlab-sparc) installed and other useful packages.
-- [JupyterLab Julia](https://github.com/ITISFoundation/jupyterlab-julia): with Julia (and Python kernel)
-- [JupyterLab R](https://github.com/ITISFoundation/jupyterlab-r): with R (and Python kernel)

fyi @pcrespov. 
At some point we'll need to discuss if you'd like to go on with the second item in the tasklist (annotated Python function), by the NIH deadline (end of May) or if we want to drop it completely.

**Comment by elisabettai** [comment]
@pcrespov, regarding the second task, i.e. making a cookiecutter for annotate Python functions. I remember you suggested that I bring a use-case to the table for this. I thought a bit more about that, but I don't have any unfortunately, most of the services I have onboarded are sort-of complex software, sometime in Python, but not always.

Maybe @wvangeit has some use-cases related to optimization. 

For info, this milestone is due by end of May

**Comment by elisabettai** [comment]
## Update Sprint Leeroy Jenkins

A new cookiecutter for simple creation of services based on o a command-line-interface (CLI) application and execute has been created, source code [here](https://github.com/ITISFoundation/cookiecutter-osparc-cli-service).

It has been tested with:
- a toy example (the bash `touch` command) 
- a scientific software, already onboarded in the past: Spinal Cord Toolbox
- a scientific software, already onboarded in the past: k-Wave
