### ISSUE TITLE
Nov Communication Support in o²S²PARC

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1096]
**Description:**
Collaboration on shared o²S²PARC studies: notes and notifications, tasks.
A key strength of o²S²PARC is its ability to support collaborative modeling and research. This aspect should be strengthened by facilitating task-related communication. It shall be possible to add ‘Post-it’s within studies that contain notes. Mention of user names (with @ symbol) shall trigger the sending of a corresponding mail containing the note and a link that directly opens the corresponding study (provided locking status permits it). At a later time point, it will be envisioned to extend this to a notification, chat, and support infrastructure.

**Deliverable:**
o²S²PARC platform functionality

**Acceptance criteria**: 
Comments can be added on the workbench and assigned to specific users (members of common organizations), resulting in them being notified.

Out of scope: –

Deadline:
Q1

[wrike Y7-MS 6.1: Communication Support in o²S²PARC](https://www.wrike.com/open.htm?id=1155714653)

**Comment by elisabettai** [comment]
@esraneufeld, what @odeimaiz presented about post-its and comments to NIH last week seems to satisfy the "Acceptance criteria" in the description above. Should we consider this milestone complete?

**Comment by esraneufeld** [comment]
dear elisaetta
for nih reporting, we can call it closed. but once the release is over, i would like to improve this functionality a bit. particularly the means of responding to a sticky note and the ability of making them visible to all.

**Comment by elisabettai** [comment]
OK. I'll close this now, since this case refers strictly to the NIH milestone and it helps keeping things organized.

Feel free to create a new case (later) for the improvements or I can keep a note so we remember to do that.
