### ISSUE TITLE
Nov DevOps Infrastructure and Automation (1/3)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1100]
Description:
Develop DevOps infrastructure empowering users to perform more monitoring and troubleshooting tasks themselves, thus facilitating debugging and reducing the required SIM-Core manpower in the longer run.
Foreseen functionality includes:
 - Provide increased automation for the following routine DevOps tasks:
    - Better organization of docker images in registry (validation of metadata, deletion of faulty images)
    - Simplification of interaction with database to have command line tools for:
       - bulk add/remove/upgrade access rights to services for a user/group
       - bulk remove/add/upgrade services from projects 
       - automate resource limits assignment for users based on service and user/group-id (also relates to API extensions & computational backend refactoring discussed above)
    - Information on which users have currently which studies open
    - Development of tools to collect resource usage (compute & storage) information for potential billing (part of sustainability plans) based on
       - services
       - user groups
    - Housekeeping: Detecting stale (old/unused) user accounts and proactively find corrupt projects/services and unused data for clean-up by DevOps

- Web-Application Monitoring: Automatic collection of metrics upon any unexpected failures and nascent bugs, which will be used to assess the user-experience during our development cycles. This will help to assess if user experience degrades or improves and how much time for maintenance is required flexibly. There is no need to rely only on traditional, mostly slow feedback cycles (such as dissatisfied users’ email feedback)

Deliverable: 
Extended DevOps infrastructure: tools to collect resource usage

Acceptance criteria: 
Infrastructure is in place that provides increased DevOps automation and web-application monitoring

Out of scope: –

Deadline:
Q1

[wrike Y7-MS 7.1.1: DevOps Infrastructure and Automation (1/3)](https://www.wrike.com/open.htm?id=1158229965)

**Comment by elisabettai** [comment]
@mrnicegyu11, this is the first of three "DevOps" improvements planned for Y7.

This case specifically has as deliverable: "Extended DevOps infrastructure: tools to collect resource usage". I'd say this is complete because we have the resource usage tracker service in place. Is there something missing from DevOps side? Maybe @matusdrobuliak66 knows best?

**Comment by matusdrobuliak66** [comment]
> @mrnicegyu11, this is the first of three "DevOps" improvements planned for Y7.
> 
> This case specifically has as deliverable: "Extended DevOps infrastructure: tools to collect resource usage". I'd say this is complete because we have the resource usage tracker service in place. Is there something missing from DevOps side? Maybe @matusdrobuliak66 knows best?

Resource usage tracker is currently storing information about user usage. So yes that part can be closed from my perspective

**Comment by mrnicegyu11** [comment]
Seems good for me thanks a lot @elisabettai
