### ISSUE TITLE
Resize rename study window

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#1130]
![image](https://github.com/ITISFoundation/osparc-issues/assets/33161876/fc26da2b-c106-498c-a599-08ee04e93125)

**Comment by eofli** [comment]
1. Snapping Window: if possible, better to have the checkbox items in grid (aligned)
<img width="594" alt="snapsettings" src="https://github.com/ITISFoundation/osparc-issues/assets/40888440/f4f202ca-c421-41ef-809f-58852453d58b">

**Comment by eofli** [comment]
2. Icon for Text needs to be improved
![iconText](https://github.com/ITISFoundation/osparc-issues/assets/40888440/5fed3f7b-1431-44f1-86aa-cf635c3ae43e)

**Comment by mguidon** [comment]
![image](https://github.com/ITISFoundation/osparc-issues/assets/33161876/fc26da2b-c106-498c-a599-08ee04e93125)

**Comment by pcrespov** [comment]
not actionable/usable

**Comment by elisabettai** [comment]
@pcrespov, why is this not actionable? 
As far as I understand, he's suggesting to make the "Rename" window larger, which is not a bad idea I think.

**Comment by pcrespov** [comment]
> @pcrespov, why is this not actionable? As far as I understand, he's suggesting to make the "Rename" window larger, which is not a bad idea I think.

@elisabettai For me "General UI/UX Feedback for product" with an empty description does mean really anything. It looks like an abandoned issue. If that is not the case, can you please then change the title, add more details and assign to @jsaq007 or @ignapas

**Comment by jsaq007** [comment]
It's a small change and worth doing as the input field is really small and a bit of a pain. I will assign it to me and take care of it in another bigger PR
