### ISSUE TITLE
Sep:MAP-Core support: Confirm with SIM-Core that their "new" JSON schema is ready

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1135]
Until now, the (MAP-Core) Simulation viewer has been using its own JSON schema to encode all the information needed to create a UI on the fly. However, this was never meant to be either a permanent solution or a full solution. SIM-Core has been working on a more generic JSON schema. This "new" JSON schema should therefore be used by the Simulation viewer.

Our role: confirm that our "new" JSON schema is ready for use by MAP-Core, i.e. it covers everything that the Simulation viewer currently needs.

[4.2 SIM API support|*|wrike 4.2 1. Confirm with SIM-Core that their "new" JSON schema is ready I ](https://www.wrike.com/open.htm?id=1201345460)

On Sep. 25 Alan (MAP-Core) wrote:

> Just as a quick reminder:
> 
>  the new JSON schema should, in some way or another, support what we currently use in datasets [135](https://sparc.science/file/135/3?path=files%2Fprimary%2Fsimulation.json), [157](https://sparc.science/file/157/3?path=files%2Fprimary%2Fsimulation.json), [308](https://sparc.science/file/308/1?path=files%2Fcode%2Fsimulation.json), [318](https://sparc.science/file/318/1?path=files%2Fcode%2Fsimulation.json), and [320](https://sparc.science/file/320/1?path=files%2Fcode%2Fsimulation.json).
>     our "old" JSON schema can be found [here](https://github.com/ABI-Software/simulationvuer/blob/main/src/components/json.js).

```[tasklist]
### TheNameless
- [x] release api-server entrypoint for ports that provide solver schemas
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/pull/75
- [x] release python client,
- [ ] Single `openapi.json` for api-server with `DEV_FEATURES=1` and make sure dev features are makrked there.
- [x] Conditional import on dev features in client
```

**Comment by elisabettai** [comment]
@pcrespov, @bisgaard-itis  this issue was related to release the api-server entrypoint for port that provide solved schemas, which I think is done. So I'd be inclined to close this one.

Is the missing point in the tasklist above still relevant?

**Comment by bisgaard-itis** [comment]
Yep, the last unchecked task is relevant. I have moved it to a separate issue (https://github.com/ITISFoundation/osparc-simcore/issues/5103) and am closing this one

**Comment by bisgaard-itis** [comment]
@pcrespov I just closed this one because all the tasks are checked. But do you wish to keep it open for the work you are currently doing for Alan?
