### ISSUE TITLE
Update MAP-Core on API developments

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1136]
MAP-Core will have to report every quarter about our APIs used by the MAP Portal widgets.
This will likely involve having regular calls with them and/or providing documentation in time. @pcrespov 

And updating Portal datasets when MAP requests that. @elisabettai 
SIM-Core Role: 
- Timely provision of documentation for new APIs 

The general MAP-Core milestone says:

> Description: Support the integration of new SIM (oSPARC) APIs via the MAP widgets on the SPARC Portal, work with SIM to support MAP functionality on oSPARC. For example:
> 
>    -  Expose new capabilities on the SPARC Portal via the Simulationvuer. This might include:
>     Updates required to match oSPARC authentication service changes ( #1091 #1090 ) 
>    -  Explore caching of user information via portal profile for use with extended services (﻿#1095 )
>    -  Evaluate how to leverage the extended study configuration API as it evolves (#1110 #1111 ﻿)
>    -  Migrate OpenCOR plugin on oSPARC to use libOpenCOR and the new SIM plugin-building tools
>      - - will enable progress monitoring which is not possible with current OpenCOR plugin  (#1095 )
> 
> 
> Acceptance criteria:
> 
>   Quarterly reporting on new SIM APIs used by the MAP Portal widgets.
>   Attend all SIM-Core Y7 webinars
> 
> 
> Prerequisite:  n.a
> 
> Timeline: continuous
> 
> SIM-Core Role: 
> 
>   Timely provision of documentation for new APIs

from [wrike 4.2 SIM API support](https://www.wrike.com/open.htm?id=1116244039)

**Comment by elisabettai** [comment]
HI @pcrespov, could you maybe summarize the ongoing work with Alan? Also feel free to redirect me to another case if you have one.

**Comment by elisabettai** [comment]
@pcrespov, have met with MAP in January as anticipated [in wrike](https://github.com/ITISFoundation/osparc-issues/issues/1135) and/or is there any new progress since we published the ports schemas?

**Comment by pcrespov** [comment]
> @pcrespov, have you met with MAP in January as anticipated [in wrike](https://github.com/ITISFoundation/osparc-issues/issues/1135) and/or is there any new progress since we published the ports schemas?

@elisabettai not yet. I was expecting them to contact me. I will send them a reminder by the end of the week.

**Comment by pcrespov** [comment]
### Update Sprint Schoggilebe

- Meeting with Alan from MAPCore on Tue Feb 14, 2024 (22h ZH-time)
- TODO: minutes of meeting  (waiting feedback from Alan)
