### ISSUE TITLE
Incident: nodes can't be started anymore

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1147]
**Long Story Short**
As a consequence of this https://github.com/ITISFoundation/osparc-issues/issues/1143, we need to "restore" two nodes (osparc.io). Neither collaborators or study owner can start the services anymore

`09472011-f0b7-4349-875b-4c23392c4a1e` and `45ad9f51-85c2-4e86-9b2b-d46ecfdd6917`

**Definition of done**
- We go back to a previous version of it (preferred solution)
- Data is zipped and sent to the user, who will have to manually unzip.

**More info**
Corresponding sidecars are hanging with an error during saving, which is good.

**Comment by GitHK** [comment]
Incident followup.
Some files were partially used inside the `workspace/` folder in the both nodes. We decided to revert to the previous state by and removed these folders.
Some partial data was saved and we decided to revert.

**Comment by elisabettai** [comment]
This was resolved by "discarding" changes to those nodes. A follow up will be to warn users about not using "tar" when creating archives or disable the command (see https://github.com/ITISFoundation/jupyter-math/issues/23)

**Comment by GitHK** [comment]
closing, issue already resolved at the time
