### ISSUE TITLE
Group studies according to tags

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1148]
**Describe the user role**
General oSparc user

**Describe the goal**
Visually group studies according to tags

**Describe the benefit**
I know there have been tickets about creating folders for studies. It seems this creates extra complication wrt to sharing folders etc. 
As an intermediate solution, maybe I could propose to let people visually group studies according to tags. As far as I can see it would just require a change in the front end, since the tags mechanism already exists. This would already allow users to make an easy distinction between e.g. 'shared' and 'self-owned' studies.
It would basically be something similar to how gmail works wrt to IMAP. Emails are just labelled in gmail, but look like folders when accessing through imap.

An extra could be to allow 'subtags' using slashes in the names, but that probably gets too much in the territory of folders.

To create a bit of structure in the studies list

**Additional context**

**Comment by wvangeit** [comment]
Btw, this could be named 'smart folders' (if this is not trademarked by apple), so that it can be kept once 'real' folders exist.

**Comment by odeimaiz** [comment]
@wvangeit Now that folders are coming and we don't plan to extend Tags to nested tags, can we close this issue?

**Comment by wvangeit** [comment]
Sure, makes sense
