### ISSUE TITLE
Project card data is empty

### ISSUE THREAD

**Issue by cosfor1** [ITISFoundation/osparc-issues#1150]
For "new studies" (i.e. the ones created/opened after the last release on Sep. 28), the Project data selection (from the three dots menu) seems to be broken.

Thank you,\
Cosimo

@odeimaiz @elisabettai

**Comment by elisabettai** [comment]
Hi @GitHK, is this hard to fix? 

This is a blocker for users who need to update services manually to a new version, see details [here](https://git.speag.com/oSparc/services/jupyter-smash/-/issues/18#note_172861). 

In addition, how this is going to work once we fix the issue? Will users have to download files one by one of will there be some ways to download them all at once? E.g. with a zip?
