### ISSUE TITLE
Failed services when opening

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1171]
Dear osparc support team
I have two services in failed state~~ could you please un-fail them? :blush: 

tip.itis.swiss
study: 58298744-3bc3-11ee-b48d-02420a0b004d
service 1: e4595917-7749-4fc8-af35-388ac6e13ffe
service 2: 209f42c6-3d7a-499c-b871-db0c9cf0497c

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/7g8xbzu58pb1bq8wkzxp3ham1o) *by `@msteiner`*._

**Comment by elisabettai** [comment]
@GitHK please close when solved and ideally link existing PRs that should fix this?

**Comment by GitHK** [comment]
Solved, we have an outstanding issue with one of the services that have been wrongly build and create issues when saving the state.
A new release for those services is required impacts version 3.0.20 and 3.0.19 of smash
