### ISSUE TITLE
Only show “credits” column in usage table if wallets/payments are activated in the product

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#1182]
<img width="831" alt="image" src="https://github.com/ITISFoundation/osparc-issues/assets/32402063/06350f01-30c7-412d-977d-24ea575d79f6">

Products with payments disabled ( `is_payments_enabled=False`)  have no `wallets`, `credits` or `payments`. Therefore UI should not show any indication of these terms. Above, in the `User -> My Account -> Usage` of an `osparc` product still displays the column credits with `-`. This column should be removed. The column User as well since we cannot share wallets either so all runs will be from the same user.

Please, review the entire UI and ensure consistency

NOTE: This is an action item from review meeting 2023-11-08

**Comment by elisabettai** [comment]
@jsaq007, if you get the chance, it will be nice if you can fix this soon-ish, ahead of the next monthly meeting (on Dec. 6th)
