### ISSUE TITLE
Read-only user cannot open the iframes

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1183]
**Long Story Short**
I have been added as a User (with only read access) to a study, but I cannot open the iframe. I am also not able to select any node in the workbench.
If I click on the node on the left-most column, it works (i.e. the iframe is displayed).

**Expected Behavior**
As a user of a study, I should be able to visualize the iframe of an interactive service

**Steps to reproduce**
Look at study on osparc-master called "Read Only 2 Jupyters"

**Additional context**

**Comment by elisabettai** [comment]
@jsaq007 or @ignapas, maybe you can have a look? It is not a critical bug.

**Comment by jsaq007** [comment]
I am looking into it
