### ISSUE TITLE
Template creation is still buggy

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1184]
**Long Story Short**
On osparc.io, creating templates often show misleading error messages. The user sees twice a message in the frontend that says that two tasks have been created (why do we have 2) and then an unexpected client error message.

However. the template is created in the backend and it appears after in the Templates tab after refreshing

![Create_template_bug](https://github.com/ITISFoundation/osparc-issues/assets/18575092/d71d8943-84ce-4cbc-82cd-34e53000ccb7)

**Expected Behavior**

**Actual behaviour**

**Steps to reproduce**

**Environment**
osparc.io (but also sim4life.io) (with Firefox)

Note: potentially a duplicate of https://github.com/ITISFoundation/osparc-issues/issues/1048

**Comment by elisabettai** [comment]
Same happened on sim4life.io. But different error message;

![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/9eb1f50c-39a4-423c-9621-e44053d9ab4e)

@sanderegg, do you think the two things are related? Should we investigate before January and fix it once for all? 😉

**Comment by sanderegg** [comment]
@elisabettai maybe but for sure, should be prioritized
