### ISSUE TITLE
Create AxonDeepSeg Service(s) in o^2S^2PARC

### ISSUE THREAD

**Issue by AntoninoMarioC** [ITISFoundation/osparc-issues#1188]
**Describe the user role**
In order to enable quantitative modeling of nerves for application related to bioelectronic medicine, I'd like to have a service(s) for AxonDeepSeg (https://github.com/axondeepseg/axondeepseg).

**Describe the goal**
AxonDeepSeg allow two things primarily. 
1. segmentation of nerve cross section and extraction of axonal statistics relevant for in silico modeling
2. to train a CNN network for future segmentations (e.g. nerve tissue specific, or dedicated to specific histology staining)

As a user, I would consider three flavors (ideally):
1. a service that enables running AxonDeepSeg via GUI as iSEG
2. a service that enables the training of a segmentation network
3.  a service that enables running a trained network to input images (e.g. via Python), provided a trained network.

Priority for me would be to have 1.

** Note**
I have already used the tool and have ready image data and code to integrate the tool within the modeling of neurostimulation

**Comment by AntoninoMarioC** [comment]
[s41598-018-22181-4-1.pdf](https://github.com/ITISFoundation/osparc-issues/files/13424213/s41598-018-22181-4-1.pdf)

**Comment by elisabettai** [comment]
@AntoninoMarioC, you will now found the first flavor of AxonDeepSeg (a GUI service, similar to iSEG) on oSPARC, I have provided some more details in a PM.

For flavours 2 and 3, it looks like you'd like 2 computational services to (1) train a network, (2) apply a network to images. We can discuss the details. Otherwise another option will JupyterLab with AxonDeepSeg installed where you can do (1) and (2). The user experience would be similar to working with jupyterlab-sim4life.

**Comment by elisabettai** [comment]
To make developing code easier, we've also added a new JupyterLab service with AxonDeepSeg preinstalled. 
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/dd4806b6-5b04-4767-8bec-7f16859cb224)
@AntoninoMarioC 

@AntoninoMarioC can you tell us what is next in priority for you? In the case description we have:

2. a service that enables the training of a segmentation network
3. a service that enables running a trained network to input images (e.g. via Python), provided a trained network.

**Comment by elisabettai** [comment]
As requested by @AntoninoMarioC, we now have also a runner service on oSPARC for AxonDeepSeg. It takes as input an image to segment and it performs the segmentation and extraction of the morphometrics.
