### ISSUE TITLE
Open button after updating services doesn't work

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1198]
**Long Story Short**
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/ad1e2a0d-34e5-4731-a382-51a4c92d1779)
When you click on `Open` just after updating a service nothing happens

**Expected behavior**
After updating one or more services, it should be possible to open the study from the same window

**Steps to reproduce**
1. Choose a project that has some services that can be updated
2. Update the service(s) in the project from the window shown above
3. Click on `Open`
4. Nothing happens

**Environment**

osparc.io, sim4life.io (and probably other deployments)

**Additional context**
This was reported already by multiple users.

**Comment by elisabettai** [comment]
@jsaq007, hopefully something that requires a small fix

**Comment by odeimaiz** [comment]
fixed
