### ISSUE TITLE
Should we work towards integrating TIP and sim4life.io

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1209]
**Describe the user role**
I just had a really interesting discussion with @elisabettai and we had the following Idea: 

As a user, it might make everything a lot easier if the tools were not in separate places but they could flawlessly switch between the two functions. 

**Describe the goal**
The goal would be to simplify our whole workflow by integrating it into one powerful tool. Especially thinking of the different steps that we will have in the personalized version of TIP. 

The first step will be creating a personalized model using segmantic and placing the electrodes using Bryn's algorithm to place them. These are all functionalities that use the S4L API. We also want the users to see the generated model to make sure that everything is predicted and placed properly. This corresponds to the "**Modeling**" section in S4L.

The next step is the automatic generation of Simulations and then running all the simulations (maybe using Makaroff's algorithm) so we can build the field library. Also, this is done using the S4L API and corresponds to the "**Simulation**" section within S4L. 

The final two steps in TIP are the TI Postpro and the subsequent old sim4life service which we limited to only showing the "Analysis" Part of S4L desktop. But we could simply put the whole TI Postpro functionality into the "**Analysis**" section and then maybe just have a new view where u can switch between the TI Postpro view and the regular S4L Analysis Tab view, so basically just combine everything. 

I feel like we are developing things in parallel that maybe needed to be developed in parallel at the beginning to find out the needs of each of the tools, as if TI Postpro was a sort of development branch. But I feel it is time to merge these two great tools into one.

Isn't it a bit of a contradiction that you can generate and run like 70 Simulations in TIP to create the fields library, and then also look at your results, and all of this is for free while users have to pay to be on sim4life.io?
This could also answer the question Niels raised about finding the limit of how much we give away for free in TIP since we don't want to lose control and give away stuff that users don't have to pay for. If the two tools are linked we could already take advantage of the payment structure you implemented for Sim4Life.io and apply them for TIP. Also, it would probably heavily simplify the move of TIP to AWS since Sim4Life.io is already on AWS.

I would like to discuss this idea in the meeting next Friday and am looking forward to all of your Input.

**Describe the benefit**
- Simplify development of our toolbelt
- Stop developing things that we already have good solutions for in parallel (like @pcrespov said to me, why reinvent the wheel when we already have a working solution) and focus all our energy on the actual issues that we need to improve.
- Reduce costs (we might not have to pay for two tools on AWS but we have them all in one place and we then scale our cluster and resources accordingly. (I will continue working on the cost optimization tool with @mrnicegyu11 )

**Comment by Konohana0608** [comment]
https://github.com/ITISFoundation/osparc-issues/assets/61539759/5fd1c042-8291-4640-a2c2-9a1f27f4ae1c

**Comment by Konohana0608** [comment]
showing the idea in a video format~~

Personalizer --> Modeling Tab
Simulator --> Simulation Tab
Electrode selector --> might need a 4th Tab or menu in S4L.io
TI_Postpro/Exposure Analysis --> Analysis Tab

**Comment by mrnicegyu11** [comment]
Closing this old "discussion" ticket in favor of the following actionable folllow-up:
https://github.com/ITISFoundation/osparc-issues/issues/1309
