### ISSUE TITLE
Some product colors inconcistencies?

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1216]
This was noticed on **osparc-master.speag.com** (osparc product)

## Highlighting on selection in the primary column
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/0b989059-3086-4b1a-b7da-b9e31afe05ad).

We should probably apply here the color specific to the product (a "light violet")?

## Selected nodes color in light theme
This is on osparc-master (osparc product), so selection should be purple.
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/a5d6ba4d-bd97-43e8-a437-f08400a9b4bf)

In the dark mode it is OK.

**Comment by jsaq007** [comment]
Part of not all of these are done in the Xmas image PR perhaps you can have a look and close this if it's not needed? Else I will take care of it when I return on 3rd Jan

**Comment by elisabettai** [comment]
Both of them looks good now on osparc-master, I see the product colors for selected nodes in light mode and dark mode as well.
Thanks @jsaq007 for the fix and apologizes for seeing this only now.

![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/8301c91e-bde5-4413-9e4e-bfb491fb122b)

![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/ab332840-ce73-4d99-86e2-4e8f814e06be)
