### ISSUE TITLE
Workbench: collapse buttons could be made more visible

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1233]
To help users see those buttons
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/4f318501-97a9-45fd-896c-d3b1a5e6ab8f)

We could take inspiration from overleaf:
![collapse_resize_overleaf](https://github.com/ITISFoundation/osparc-issues/assets/18575092/5db1061e-75cf-464f-9c94-7761e40237f6)

**Comment by jsaq007** [comment]
@elisabettai I think we can close this as the issue seems to be resolved?
<img width="1720" alt="Screenshot 2024-01-29 at 11 46 10" src="https://github.com/ITISFoundation/osparc-issues/assets/903587/08c0fe44-7729-4dba-84a5-d1c2e7c95a87">

**Comment by elisabettai** [comment]
Hi @jsaq007, this one is not exactly a duplicate, because the suggestion from Team Black was to also change the vertical separator to something like overleaf-style (or anything more visible than a simple line).

I can show Team Black the improvement in the colors we have now (but on the oSPARC product) and see what they say (next call with Team Black is on Feb. 21st).

Of course this is not the most important thing at the moment. 😉
