### ISSUE TITLE
Dashboard; list views have low contrast

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1234]
Team Black users reported that Studies and Services list vieware somewhat difficult to read.

Maybe adding transparency to background could help?

Studies list view
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/489ec5f1-a76e-49fa-85c9-4f6f678cc62c)

Services list view
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/64473be3-c4b7-46ad-b732-d12392d79063)

**Comment by jsaq007** [comment]
@elisabettai I have made the text lighter in the card I could still improve it if you think it's necessary?

<img width="1677" alt="Screenshot 2024-01-29 at 17 06 21" src="https://github.com/ITISFoundation/osparc-issues/assets/903587/36152d3c-768c-4eb7-9dbc-9fbc952f33e1">

**Comment by elisabettai** [comment]
Hi @jsaq007, it looks a bit better to me, but hard to spot the difference and understand what "lighter" text means. (I've looked now at osparc-master). 😉 

Unfortunately I have not many ideas on how to improve this. Team Black proposed to add transparency, but I'm not sure it will help. If you have other ideas we can try, otherwise feel free to close and I ask Team Black what they think about the change (next meeting on Feb 21st).

**Comment by jsaq007** [comment]
OK. Good to know you weren't able to spot the difference directly. I will adjust it further in my next PR
