### ISSUE TITLE
Light team improvements 

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1235]
Workbench: nodes status (e.g. "Success") hard to read (low contrast)
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/f4691af4-6561-4d8c-aa74-3923d3e547da)

**Comment by jsaq007** [comment]
@elisabettai I think this can e closed. If there are any further issue regarding theming we should address them in their own issues.
