### ISSUE TITLE
"Add Editors" button misalignment 

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1246]
**Long Story Short**
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/abd597cb-5ac2-4e88-93e7-a62b03a0000a)

In addition, I'd also rename the button to "Share with..." as suggested here: https://z43.manuscript.com/f/cases/190346/New-feedback-Add-Editors

**Comment by jsaq007** [comment]
Closed with this https://z43.fogbugz.com/f/cases/190346/New-feedback-Add-Editors
