### ISSUE TITLE
Remove word "Error" when trying to access a template that requires login

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1252]
EN saw this page and said: "a) avoid the word error on that page (i thought we already did that) "
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/f359df9f-57d6-4ad6-9f17-55e598a0753a)

**Comment by elisabettai** [comment]
Hi @pcrespov, POs don't like that we say "Error".
I think that comes from the error code we return here: https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/src/simcore_service_webserver/studies_dispatcher/_studies_access.py#L104

Should we just leave "status_code' empty? I guess that's not good practice? 😉

**Comment by pcrespov** [comment]
> Hi @pcrespov, POs don't like that we say "Error". I think that comes from the error code we return here: https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/src/simcore_service_webserver/studies_dispatcher/_studies_access.py#L104
> 
> Should we just leave "status_code" empty? I guess that's not good practice? 😉

@elisabettai this change should be done in the front-end. Please do not remove the status-errors produced by the server. I think we can implement the PO view by simply removing the title in the front-end. Done :-) .
