### ISSUE TITLE
Cannot open saved project

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-issues#1263]
This is a placeholder for https://z43.manuscript.com/f/cases/192039/New-feedback-Cannot-open-a-saved-project

**Comment by GitHK** [comment]
@jsaq007 you mentioned that this one might be fixed by some recent changes?

**Comment by jsaq007** [comment]
I believe the original issue has been closed. @odeimaiz, @ignapas, @bisgaard-itis and @GitHK what do you think should I dig deeper or should we close this will we get something back on the original?

**Comment by bisgaard-itis** [comment]
> I believe the original issue has been closed. @odeimaiz, @ignapas, @bisgaard-itis and @GitHK what do you think should I dig deeper or should we close this will we get something back on the original?

The way I understand the FB case it is closed because it is hard to reproduce. If that's the case I would go for a lower hanging fruit.
