### ISSUE TITLE
Height of study cards ribbons

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1271]
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/a1919765-ddde-4cb6-ac88-1130528b1ab9)

**Comment by elisabettai** [comment]
Hi @jsaq007, Team Black had a question on the new study card design. They said that they're attention was caught by the different cards having different heights in the transparent ribbons. Have you thought about that? Do you think it looks good?

**Comment by jsaq007** [comment]
As this screenshot isn't up to date with the latest stuff being release in the coming time it's different to see what these studies would look like when the update comes.
Unfortunately we are caught in a situation where content is different in pretty much all projects and different content shows at different times which is less attractive when you have empty lines. It feels more like there is a bug as something should be visible there.
If there is specific feedback based on how they or other users experience it I would be happy to look at the UX/UI again and take any feedback into consideration.

**Comment by elisabettai** [comment]
Thanks @jsaq007 for the answer, I'll pass this on in the next meeting, together with updated UI. I think it answers the question.
