### ISSUE TITLE
Log out users when cookie expires

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1298]
Dear osparc team
I am aware that this happens when I randomly get logged out. It just seems to happen pretty frequently lately. Do you know why that is?

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/cyrytpcgwbrwu8sc6q4qbfd47o) *by `@msteiner`*._

![image (3)](https://github.com/ITISFoundation/osparc-issues/assets/18575092/2fef0be0-e164-41ca-b102-7529a6764860)

**Comment by elisabettai** [comment]
As discussed @odeimaiz, not sure what's the best for the user experience here.

**Comment by pcrespov** [comment]
@odeimaiz @elisabettai this is linked with this issue I created some time ago https://github.com/ITISFoundation/osparc-simcore/issues/5239

**Comment by elisabettai** [comment]
Thanks @pcrespov, I'm closing this as duplicate then (and transferred the other issue to this repo).
