### ISSUE TITLE
TI solution & Guided Mode

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#130]
Related to cases:
#18 , #91 
Design v0.9 of the TI treatment planning tool, keeping in mind synergies with the upcoming guided mode.
EN will attach the current specs document
- wireframes/mockups
- implementation approach

**Comment by esraneufeld** [comment]
[SWspecs_v1.0.xlsx](https://github.com/ITISFoundation/osparc-issues/files/4170947/SWspecs_v1.0.xlsx)
[TI_Solutions_20191217osparc.pptx](https://github.com/ITISFoundation/osparc-issues/files/4170958/TI_Solutions_20191217osparc.pptx)

**Comment by sanderegg** [comment]
@mguidon needs to get the scripts from Anto
