### ISSUE TITLE
Optional Blocking of Access/Configuration to Services

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#133]
allow to specify for a node, if it should be inaccessible/greyed out when required input is missing.  this would allow macro's to be used as step-wise, wizard-like applications

use-case: i am not able to proceed to the stimulation parameter optimization in the TI tool, before i have not finished the setup step (selection of head model...)

**Comment by KZzizzle** [comment]
@drniiken I believe the guided mode now fulfills this - if you agree I will close this issue

**Comment by drniiken** [comment]
Yep, sounds good. Thanks @KZzizzle .
