### ISSUE TITLE
Step-Through

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#134]
- [ ] have a left and right button, to advance to the next/previous service from within an open service. 
- [ ] If there are multiple inputs/outputs, enable a way to define the primary next one (e.g., the different steps in an EM simulation setup have an order), or - if not available - offer a selection.

**Comment by KZzizzle** [comment]
@drniiken this also appears to be fulfilled but feel free to add more specification

**Comment by drniiken** [comment]
@KZzizzle ... I'll have a look, sure. Thanks.

**Comment by pcrespov** [comment]
Completed.
