### ISSUE TITLE
sim4life.lite reduced mode (CAD editing)

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#1340]
```[tasklist]
### Tasks
```

**Comment by esraneufeld** [comment]
create a service, freely accessible on osparc, that offers the possibility of importing CAD, editing it, and saving/exporting the result. only support formats for which we do run into additional licensing issues. this for now suffices to address #1049

**Comment by mguidon** [comment]
| Label | Description | Enabled |
|-------|-------------|---------|
| 10-10 System | Create international 10-10 system points on scalp. | :x: |
| Activate Grid | Make the selected working grid the active one | :x: |
| Align | Align the current selection to a target selection. | :x: |
| Annotate | Annotate | :x: |
| Append Meshes | Append Meshes | :x: |
| Append Meshes | Append or merge meshes. | :x: |
| Arc | Click to set the center, click to set the radius and start point, then click to set the end point. | :x: |
| Assign Material | Assign material settings to the selected entities. | :x: |
| Auto-Label | Automatic segmentation of medical images. | :x: |
| Axon Model | Create axons from wires | :x: |
| BCAGE | Start Birdcage Creation Tool | :x: |
| BCAGE Editor | Start Birdcage Edit Tool | :x: |
| Bend Part | Bend a solid model around a given axis. | :x: |
| Blend Edges | Create smooth blend on the selected edges | :x: |
| Blend Faces | Create a new blend surface between the two selected faces and unite the result with the selection. | :x: |
| Block | Click to create first corner, the second corner of the base, then click to set the height of the block. | :x: |
| Boundary Patch | Use this tool to create a patch at the outer surface of an unstructured mesh. | :x: |
| Bounding Box | Extract the bounding box from the selection and create a wire block. | :x: |
| CLUA | Start CLUA Creation Tool | :x: |
| Calculators | Show Calculators | :x: |
| Centerline | Extract centerline through closed surface mesh between start and end points. | :x: |
| Chamfer Edges | Chamfer selected edges. | :x: |
| Check Wire Path | Analyze which solids a set of wires pass through | :x: |
| Circle | Click to set the center and click to set the radius. | :x: |
| Clone As Posable | Creates a posable copy of a posable model, e.g., if different postures are needed. | :x: |
| Clone As Static | Creates a static copy of a posable model. This is useful if you need to edit the model (e.g., boolean operation, planar cut) | :x: |
| Clone with Expressions | Clone with Expressions | :x: |
| Coil | Start Coil Creation Tool | :x: |
| Cone | Click to set the center of the base, click to set the base radius then click to set the height and the top radius of the cone. | :x: |
| Copy | Copy | :x: |
| Copy Phased Array Parameters | Copy Phased Array Configuration | :x: |
| Cover Holes | Cover holes to create a closed polyhedron. | :x: |
| Cover Holes | Detect simple holes in surfaces and create faces to cover the holes. | :x: |
| Cover Loops | Cover selected wire body and create a sheet body. | :x: |
| Cover Open Edges | Detect simple edge loops in a surfaces and create faces to cover the selected edges. | :x: |
| Create Group | Create Group | :x: |
| Create Patch | Create Patch | :x: |
| Create Protected Model | Create Protected Model | :x: |
| Crop Image | Crop image interactively to a region of interest | :x: |
| Cubic Cut | Create cubic cuts of the selected parts. | :x: |
| Cut | Cut | :x: |
| Cylinder | Click to set the center of the base, click to set the radius then click to set the height of the cylinder. | :x: |
| Delete | Delete | :x: |
| Delete Domains | Delete selected domains. | :x: |
| Delete Triangle Patch | Delete Triangle Patch | :x: |
| Detach Faces | Detach selected faces from the bodies as new sheet bodies. The original body is modified. | :x: |
| Distance | Measure distance between two points | :x: |
| Domain Patch(es) | Use this tool to create a patch surrounding selected domains. | :x: |
| Draw Line | Draw line on surface mesh. | :x: |
| Edit Cubic Cut | Edit cubic cut of the selected part. | :x: |
| Edit Faceting | Allows to edit faceting parameters of a solid or face. Facets define the resolution of the representation of parts. | :x: |
| Edit Planar Cut | Edit planar cut of the selected part. | :x: |
| Electrode Placement | Electrode Placement | :x: |
| Embed Wire | Embed selected wire into the surface of the selected body | :x: |
| Export Model | Export a model to a file. | :x: |
| Export Selected | Export the selected parts to a file. | :x: |
| Extract Domain | Creates a new unstructured mesh with the selected domains. | :x: |
| Extract Edges | Create copies of all edges belonging to the selection. | :x: |
| Extract Faces | Create copies as sheet bodies of the faces belonging to the selection. | :x: |
| Extract Outlines | Extract Outlines | :x: |
| Extract Patch Surface | Extract surface mesh from selected patches. | :x: |
| Extract Points | Extract all vertices belonging to the selection as new helper points. | :x: |
| Extract Region | This tool extracts all cells which are partly inside a solid region. | :x: |
| Extract Surface | Extract surface meshes from selection. | :x: |
| Extract Triangle Mesh | Extract Triangle Mesh | :x: |
| Extrude | Extrude selected profile into a given direction. Click the starting point, click end point and click to set the direction.  | :x: |
| Extrude Patch | Extrude patch along normal direction to create a closed surface with specified thickness. | :x: |
| Fit Spline | Fit Spline | :x: |
| Fix Normals | Fix Normals | :x: |
| Full Array | Generates an array with the given entity and layout | :x: |
| Generate Surfaces | Extract surface model from label field | :x: |
| Geometry | Measure geometrical properties of objects in the modeling | :x: |
| Group Selection | Group Selection | :x: |
| Helix | Helix | :x: |
| Hide | Hide | :x: |
| Hide Others | Hide Others | :x: |
| Hide To-Be-Encrypted | Hide To-Be-Encrypted | :x: |
| Import | Import a model from a file | :x: |
| Imprint | Imprint curves as edges where the selected parts intersect. | :x: |
| Improve Mesh | Improve element quality. | :x: |
| Interface Patch | Use this tool to create a patch between two domains. | :x: |
| Interpolate To | Resample image to grid of target image | :x: |
| Intersect | Create intersection volume of selected bodies | :x: |
| Intersect With | Intersect a selection of target entities with one given entity. | :x: |
| Intersection Patch | Intersection Patch | :x: |
| Invert Mesh | Invert Mesh | :x: |
| Join | Smoothly join splines | :x: |
| Key Frame Animation | Key Frame Animation | :x: |
| LUA | Start LUA Creation Tool | :x: |
| Label Field | Create a new label field | :x: |
| Lines | Lines | :x: |
| Local Remesh | Recompute parts of a surface mesh. | :x: |
| Local Tet Remesh | Recompute parts of a volumetric unstructured mesh. | :x: |
| Make Default | Create a working coordinate system (WCS) which can be used as a reference or a modeling grid. | :x: |
| Make Symmetric | Detect symmetry plane and make symmetric. | :x: |
| Mask Mesh | This tool masks all cells which are partly inside a solid region. | :x: |
| Merge | Merge | :x: |
| Merge | Merge | :x: |
| Merge Domains | Merges selected unstructured mesh domains into a single domain. | :x: |
| Merge Meshes | Merge Meshes | :x: |
| Merge Patches | Merge Patches | :x: |
| Mesh Doctor | Analyze and fix surface triangle mesh inconsistencies. | :x: |
| Mesh Extrusion | Extrude mesh along spline or polyline. | :x: |
| Mesh Slice | Generate a multi-domain (patch) surface mesh from a 2D slice in a label field. | :x: |
| Mesh Viewer | Inspect size distribution and mesh quality. | :x: |
| Morph | Deform surface using an interactive deformation grid. | :x: |
| Move | Use this tool to translate or rotate the selected parts or sub-parts. | :x: |
| Move Faces | Provides a parametrization for moving or rotating selected faces. | :x: |
| Multidomain Mesh | Generate a multi-domain volumetric unstructured mesh from the selected solids. | :x: |
| Neuron A-Delta Fiber | Convert 3 common-node wires to A-Delta Neuron | :x: |
| P-LOOP | Start P-LOOP Creation Tool | :x: |
| POSER | Start POSER tool | :x: |
| Paste | Paste | :x: |
| Paste Phased Array Parameters | Paste Phased Array Configuration | :x: |
| Phased Array | Start Phased Array Creation Tool | :x: |
| Place Grid | Click on a object to place and orient the grid along the object | :x: |
| Planar Cut | Create planar slices or create planar cuts of the selected parts. | :x: |
| Point | Point | :x: |
| Polygon | Click to set the center and click to set the radius. | :x: |
| Project Wire | Project wire bodies onto solid or sheet bodies along their surface normals. | :x: |
| Project Wire Onto | Project wire bodies onto solid or sheet bodies along their surface normals and embeds the result. | :x: |
| Protected Model from Selection | Protected Model from Selection | :x: |
| Pyramid | Click to set the center of the base, click to set the base radius then click to set the height and the top radius of the pyramid. | :x: |
| Reconstruct Hull | Reconstruct exterior surface of assembly of solid entities. | :x: |
| Rectangle | Click to set the first corner of a rectangle aligned to the current working grid, then click to set the second corner. | :x: |
| Refine Mesh | Locally refine the mesh based on a set of bisection criteria. | :x: |
| Remesh | Allows to edit an existing surface mesh. | :x: |
| Remove Parametrization | Remove all parametrization from selection. | :x: |
| Resample | Resample image to change the resolution | :x: |
| Reset Grid | Reset the position and orientation of the working grid | :x: |
| Reverse | Reverse the orientations of the selected bodies. This can be used to fix the surface of an inverted body or to revert the orientation of a curve. | :x: |
| SEFT | Start SEFT Creation Tool | :x: |
| Sections Viewer | View neuron section centers | :x: |
| Segmentation Group | Create a new segmentation group with a default label field | :x: |
| Select Patches | Select and define triangle patches. | :x: |
| Separate Body | Separate the given body into a list of bodies with separate volumes. | :x: |
| Separate Meshes | Separate Meshes | :x: |
| Show | Show | :x: |
| Show All | Show All | :x: |
| Simplify Surfaces | Collapse edges to reduce number of triangles in surface. | :x: |
| Simplify Wires | Simplify wires and approximate by splines where possible | :x: |
| Skin Wires | Create a sheet or solid body that fits a set of surfaces through a sequence of selected wires. | :x: |
| Slice | Create intersection graph of selected bodies | :x: |
| Smooth | Smooth surface mesh. | :x: |
| Sort Group | Sort Group | :x: |
| Sphere | Sphere | :x: |
| Spline | Spline | :x: |
| Split Domains | Splits a domain. | :x: |
| Split Patches | Split Patches | :x: |
| Stent | Stent | :x: |
| Stitch | Stitch selected surfaces into a body. If the surfaces form a closed volume the result will be a solid body. | :x: |
| Subdivide | Subdivide surface mesh. | :x: |
| Subtract | Subtract bodies from first selected body | :x: |
| Subtract From | Subtract one entity from a list of target entities. | :x: |
| Surface Projection | Project a (almost) 2D entity on a surface | :x: |
| Sweep/Offset | Use this tool to create sweeps and offsets of wires, faces, sheets or bodies. | :x: |
| Text | Create and place a text object | :x: |
| Thicken Wire | Thickens a wire object | :x: |
| To Mesh | Convert solid into a triangle mesh. | :x: |
| To Polyhedron | Convert meshes or solids to polyhedral bodies. | :x: |
| To Polyline | To Polyline | :x: |
| Tube | Tube | :x: |
| Unite | Create union of selected bodies | :x: |
| WCS | Create a working coordinate system (WCS) which can be used as a reference or a modeling grid. | :x: |
| Warp Image | Warp Image | :x: |
| Wire Block | Click to create first corner, the second corner of the base, then click to set the height of the block. | :x: |
| Wire Tool Box | Routings tools for splitting, trimming, orienting wires | :x: |
| Wrap On Body | Wrap a wire or sheet onto a body. | :x: |

**Comment by esraneufeld** [comment]
dear @mguidon 
thank you for preparing this. i suggest the following changes:

---------------------------

out:
coil

in:
Cover Open Edges
Detach Faces
Draw Line
Extract Edges
Extract Faces
Extract Surface
Extract Triangle Mesh
Generate Surfaces
Improve Mesh
Interpolate To
Invert Mesh
Label Field
Local Remesh
Mesh Doctor
Morph
Remesh
Resample
Reverse
Segmentation Group
Simplify Surfaces
Smooth
Subdivide
To Mesh
To Polyhedron
Wire Tool Box

------------------------------

the rationale is that:
- we want people to work with surface meshes too
- i think that we will need similar functionality also in combination with image-based modeling in the future. to avoid redoing it a second time, i suggest to already include it

i am not entirely sure about the functionality of all of these, so i might have missed some. but i assume that this will be fixable if we stumble across it in the future...
thanks
esra

**Comment by mguidon** [comment]
This can be changed afterwards but requires re-publishing of the service. It could be done via the DB though. This avoids a re-release. For now, this is the final list:

| Label | Description | Enabled |
|-------|-------------|---------|
| 10-10 System | Create international 10-10 system points on scalp. | :x: |
| Activate Grid | Make the selected working grid the active one | :heavy_check_mark: |
| Align | Align the current selection to a target selection. | :heavy_check_mark: |
| Annotate | Annotate | :heavy_check_mark: |
| Append Meshes | Append Meshes | :x: |
| Append Meshes | Append or merge meshes. | :x: |
| Arc | Click to set the center, click to set the radius and start point, then click to set the end point. | :heavy_check_mark: |
| Assign Material | Assign material settings to the selected entities. | :x: |
| Auto-Label | Automatic segmentation of medical images. | :x: |
| Axon Model | Create axons from wires | :x: |
| BCAGE | Start Birdcage Creation Tool | :x: |
| BCAGE Editor | Start Birdcage Edit Tool | :x: |
| Bend Part | Bend a solid model around a given axis. | :heavy_check_mark: |
| Blend Edges | Create smooth blend on the selected edges | :heavy_check_mark: |
| Blend Faces | Create a new blend surface between the two selected faces and unite the result with the selection. | :heavy_check_mark: |
| Block | Click to create first corner, the second corner of the base, then click to set the height of the block. | :heavy_check_mark: |
| Boundary Patch | Use this tool to create a patch at the outer surface of an unstructured mesh. | :x: |
| Bounding Box | Extract the bounding box from the selection and create a wire block. | :heavy_check_mark: |
| CLUA | Start CLUA Creation Tool | :x: |
| Calculators | Show Calculators | :x: |
| Centerline | Extract centerline through closed surface mesh between start and end points. | :x: |
| Chamfer Edges | Chamfer selected edges. | :heavy_check_mark: |
| Check Wire Path | Analyze which solids a set of wires pass through | :heavy_check_mark: |
| Circle | Click to set the center and click to set the radius. | :heavy_check_mark: |
| Clone As Posable | Creates a posable copy of a posable model, e.g., if different postures are needed. | :x: |
| Clone As Static | Creates a static copy of a posable model. This is useful if you need to edit the model (e.g., boolean operation, planar cut) | :x: |
| Clone with Expressions | Clone with Expressions | :heavy_check_mark: |
| Coil | Start Coil Creation Tool | :x: |
| Cone | Click to set the center of the base, click to set the base radius then click to set the height and the top radius of the cone. | :heavy_check_mark: |
| Copy | Copy | :heavy_check_mark: |
| Copy Phased Array Parameters | Copy Phased Array Configuration | :x: |
| Cover Holes | Cover holes to create a closed polyhedron. | :heavy_check_mark: |
| Cover Holes | Detect simple holes in surfaces and create faces to cover the holes. | :heavy_check_mark: |
| Cover Loops | Cover selected wire body and create a sheet body. | :heavy_check_mark: |
| Cover Open Edges | Detect simple edge loops in a surfaces and create faces to cover the selected edges. | :heavy_check_mark: |
| Create Group | Create Group | :heavy_check_mark: |
| Create Group | Create Group | :heavy_check_mark: |
| Create Patch | Create Patch | :x: |
| Create Protected Model | Create Protected Model | :x: |
| Crop Image | Crop image interactively to a region of interest | :heavy_check_mark: |
| Cubic Cut | Create cubic cuts of the selected parts. | :heavy_check_mark: |
| Cut | Cut | :heavy_check_mark: |
| Cylinder | Click to set the center of the base, click to set the radius then click to set the height of the cylinder. | :heavy_check_mark: |
| Delete | Delete | :heavy_check_mark: |
| Delete Domains | Delete selected domains. | :x: |
| Delete Triangle Patch | Delete Triangle Patch | :x: |
| Detach Faces | Detach selected faces from the bodies as new sheet bodies. The original body is modified. | :heavy_check_mark: |
| Distance | Measure distance between two points | :heavy_check_mark: |
| Domain Patch(es) | Use this tool to create a patch surrounding selected domains. | :x: |
| Draw Line | Draw line on surface mesh. | :heavy_check_mark: |
| Edit Cubic Cut | Edit cubic cut of the selected part. | :heavy_check_mark: |
| Edit Faceting | Allows to edit faceting parameters of a solid or face. Facets define the resolution of the representation of parts. | :heavy_check_mark: |
| Edit Planar Cut | Edit planar cut of the selected part. | :heavy_check_mark: |
| Electrode Placement | Electrode Placement | :x: |
| Embed Wire | Embed selected wire into the surface of the selected body | :heavy_check_mark: |
| Export Model | Export a model to a file. | :heavy_check_mark: |
| Export Selected | Export the selected parts to a file. | :heavy_check_mark: |
| Extract Domain | Creates a new unstructured mesh with the selected domains. | :x: |
| Extract Edges | Create copies of all edges belonging to the selection. | :heavy_check_mark: |
| Extract Faces | Create copies as sheet bodies of the faces belonging to the selection. | :heavy_check_mark: |
| Extract Outlines | Extract Outlines | :heavy_check_mark: |
| Extract Patch Surface | Extract surface mesh from selected patches. | :x: |
| Extract Points | Extract all vertices belonging to the selection as new helper points. | :heavy_check_mark: |
| Extract Region | This tool extracts all cells which are partly inside a solid region. | :heavy_check_mark: |
| Extract Surface | Extract surface meshes from selection. | :heavy_check_mark: |
| Extract Triangle Mesh | Extract Triangle Mesh | :heavy_check_mark: |
| Extrude | Extrude selected profile into a given direction. Click the starting point, click end point and click to set the direction.  | :heavy_check_mark: |
| Extrude Patch | Extrude patch along normal direction to create a closed surface with specified thickness. | :x: |
| Find and Replace | Find and replace substrings in entity names. | :x: |
| Fit Spline | Fit Spline | :heavy_check_mark: |
| Fix Normals | Fix Normals | :heavy_check_mark: |
| Full Array | Generates an array with the given entity and layout | :x: |
| Generate Surfaces | Extract surface model from label field | :heavy_check_mark: |
| Geometry | Measure geometrical properties of objects in the modeling | :heavy_check_mark: |
| Group Selection | Group Selection | :heavy_check_mark: |
| Helix | Helix | :heavy_check_mark: |
| Hide | Hide | :heavy_check_mark: |
| Hide Others | Hide Others | :heavy_check_mark: |
| Hide To-Be-Encrypted | Hide To-Be-Encrypted | :x: |
| Imp/Export | Imp/Export | :heavy_check_mark: |
| Import | Import a model from a file | :heavy_check_mark: |
| Imprint | Imprint curves as edges where the selected parts intersect. | :heavy_check_mark: |
| Improve Mesh | Improve element quality. | :heavy_check_mark: |
| Interface Patch | Use this tool to create a patch between two domains. | :x: |
| Interpolate To | Resample image to grid of target image | :heavy_check_mark: |
| Intersect | Create intersection volume of selected bodies | :heavy_check_mark: |
| Intersect With | Intersect a selection of target entities with one given entity. | :heavy_check_mark: |
| Intersection Patch | Intersection Patch | :x: |
| Invert Mesh | Invert Mesh | :heavy_check_mark: |
| Join | Smoothly join splines | :heavy_check_mark: |
| Key Frame Animation | Key Frame Animation | :x: |
| Key Frame Animation | Key Frame Animation | :x: |
| LUA | Start LUA Creation Tool | :x: |
| Label Field | Create a new label field | :heavy_check_mark: |
| Lines | Lines | :heavy_check_mark: |
| Local Remesh | Recompute parts of a surface mesh. | :heavy_check_mark: |
| Local Tet Remesh | Recompute parts of a volumetric unstructured mesh. | :x: |
| Make Default | Create a working coordinate system (WCS) which can be used as a reference or a modeling grid. | :heavy_check_mark: |
| Make Symmetric | Detect symmetry plane and make symmetric. | :heavy_check_mark: |
| Mask Mesh | This tool masks all cells which are partly inside a solid region. | :x: |
| Merge | Merge | :x: |
| Merge | Merge | :x: |
| Merge Domains | Merges selected unstructured mesh domains into a single domain. | :x: |
| Merge Meshes | Merge Meshes | :x: |
| Merge Patches | Merge Patches | :x: |
| Mesh Doctor | Analyze and fix surface triangle mesh inconsistencies. | :heavy_check_mark: |
| Mesh Extrusion | Extrude mesh along spline or polyline. | :x: |
| Mesh Slice | Generate a multi-domain (patch) surface mesh from a 2D slice in a label field. | :x: |
| Mesh Tools | Mesh Tools | :heavy_check_mark: |
| Mesh Viewer | Inspect size distribution and mesh quality. | :x: |
| Morph | Deform surface using an interactive deformation grid. | :heavy_check_mark: |
| Move | Use this tool to translate or rotate the selected parts or sub-parts. | :heavy_check_mark: |
| Move Faces | Provides a parametrization for moving or rotating selected faces. | :heavy_check_mark: |
| Multidomain Mesh | Generate a multi-domain volumetric unstructured mesh from the selected solids. | :heavy_check_mark: |
| Multidomain Mesh | Generate a multi-domain volumetric unstructured mesh from the selected solids. | :heavy_check_mark: |
| Neuron A-Delta Fiber | Convert 3 common-node wires to A-Delta Neuron | :x: |
| P-LOOP | Start P-LOOP Creation Tool | :x: |
| POSER | Start POSER tool | :x: |
| Paste | Paste | :heavy_check_mark: |
| Paste Phased Array Parameters | Paste Phased Array Configuration | :x: |
| Phased Array | Start Phased Array Creation Tool | :x: |
| Place Grid | Click on a object to place and orient the grid along the object | :heavy_check_mark: |
| Planar Cut | Create planar slices or create planar cuts of the selected parts. | :heavy_check_mark: |
| Point | Point | :heavy_check_mark: |
| Polygon | Click to set the center and click to set the radius. | :heavy_check_mark: |
| Project Wire | Project wire bodies onto solid or sheet bodies along their surface normals. | :heavy_check_mark: |
| Project Wire Onto | Project wire bodies onto solid or sheet bodies along their surface normals and embeds the result. | :heavy_check_mark: |
| Protected Model from Selection | Protected Model from Selection | :x: |
| Pyramid | Click to set the center of the base, click to set the base radius then click to set the height and the top radius of the pyramid. | :heavy_check_mark: |
| Reconstruct Hull | Reconstruct exterior surface of assembly of solid entities. | :heavy_check_mark: |
| Rectangle | Click to set the first corner of a rectangle aligned to the current working grid, then click to set the second corner. | :heavy_check_mark: |
| Redo | Redoes the previously undone action | :heavy_check_mark: |
| Refine Mesh | Locally refine the mesh based on a set of bisection criteria. | :x: |
| Remesh | Allows to edit an existing surface mesh. | :heavy_check_mark: |
| Remove Parametrization | Remove all parametrization from selection. | :heavy_check_mark: |
| Resample | Resample image to change the resolution | :heavy_check_mark: |
| Reset Grid | Reset the position and orientation of the working grid | :heavy_check_mark: |
| Reset Grid | Reset the position and orientation of the working grid | :heavy_check_mark: |
| Reverse | Reverse the orientations of the selected bodies. This can be used to fix the surface of an inverted body or to revert the orientation of a curve. | :heavy_check_mark: |
| SEFT | Start SEFT Creation Tool | :x: |
| Sections Viewer | View neuron section centers | :x: |
| Segmentation Group | Create a new segmentation group with a default label field | :heavy_check_mark: |
| Select | Select top-level objects in the model such as bodies and meshes. | :heavy_check_mark: |
| Select Patches | Select and define triangle patches. | :x: |
| Separate Body | Separate the given body into a list of bodies with separate volumes. | :heavy_check_mark: |
| Separate Meshes | Separate Meshes | :x: |
| Show | Show | :heavy_check_mark: |
| Show All | Show All | :heavy_check_mark: |
| Simplify Surfaces | Collapse edges to reduce number of triangles in surface. | :heavy_check_mark: |
| Simplify Wires | Simplify wires and approximate by splines where possible | :heavy_check_mark: |
| Sketch | Sketch | :heavy_check_mark: |
| Skin Wires | Create a sheet or solid body that fits a set of surfaces through a sequence of selected wires. | :heavy_check_mark: |
| Slice | Create intersection graph of selected bodies | :heavy_check_mark: |
| Smooth | Smooth surface mesh. | :heavy_check_mark: |
| Snapping | Edit Snapping settings | :heavy_check_mark: |
| Solids | Solids | :heavy_check_mark: |
| Sort Group | Sort Group | :heavy_check_mark: |
| Sphere | Sphere | :heavy_check_mark: |
| Spline | Spline | :heavy_check_mark: |
| Split Domains | Splits a domain. | :x: |
| Split Patches | Split Patches | :x: |
| Stent | Stent | :heavy_check_mark: |
| Stitch | Stitch selected surfaces into a body. If the surfaces form a closed volume the result will be a solid body. | :heavy_check_mark: |
| Sub | Select sub objects in the model. This selection tool allows to select non-top level objects such as edges, faces, vertices and patches. | :heavy_check_mark: |
| Subdivide | Subdivide surface mesh. | :heavy_check_mark: |
| Subtract | Subtract bodies from first selected body | :heavy_check_mark: |
| Subtract From | Subtract one entity from a list of target entities. | :heavy_check_mark: |
| Surface Projection | Project a (almost) 2D entity on a surface | :x: |
| Sweep/Offset | Use this tool to create sweeps and offsets of wires, faces, sheets or bodies. | :heavy_check_mark: |
| Templates | Templates | :x: |
| Text | Create and place a text object | :heavy_check_mark: |
| Thicken Wire | Thickens a wire object | :heavy_check_mark: |
| To Mesh | Convert solid into a triangle mesh. | :heavy_check_mark: |
| To Polyhedron | Convert meshes or solids to polyhedral bodies. | :heavy_check_mark: |
| To Polyline | To Polyline | :heavy_check_mark: |
| Tools | Tools | :heavy_check_mark: |
| Tube | Tube | :heavy_check_mark: |
| Undo | Undoes the last action | :heavy_check_mark: |
| Unite | Create union of selected bodies | :heavy_check_mark: |
| ViP Tools | ViP Tools | :x: |
| View Analysis | Shows/Hides the Analysis Visualization | :x: |
| View Analysis | Shows/Hides the Analysis Visualization | :x: |
| WCS | Create a working coordinate system (WCS) which can be used as a reference or a modeling grid. | :heavy_check_mark: |
| Warp Image | Warp Image | :heavy_check_mark: |
| Wire Block | Click to create first corner, the second corner of the base, then click to set the height of the block. | :heavy_check_mark: |
| Wire Tool Box | Routings tools for splitting, trimming, orienting wires | :heavy_check_mark: |
| Wrap On Body | Wrap a wire or sheet onto a body. | :heavy_check_mark: |
| Zoom All | Zooms to the extent of the whole scene | :x: |
| Zoom Selection | Zooms to the selected parts | :x: |

**Comment by SCA-ZMT** [comment]
Please approve list for public release.

**Comment by drniiken** [comment]
Dear Eli, Simone, Manuel, all:

Esra, Erdem and me just talked about it.
All good for now. Approved ... please go ahead.
@elisabettai @mguidon @SCA-ZMT
