### ISSUE TITLE
Tabs for Multi-Node Services

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#135]
to be refined:

when a series of nodes belong closely together, i want to be able to switch between them using tabs at the top (in addition to the tree on the upper-right). this is particularly true for situations such as the different steps in EM simulation setup (setup, solids, BC...). 
tbd: We could trigger this behavior either 1) always when we are at a  sublevel of the workbench, 2) when we are within a sublevel that accesses a shared instance of, e.g., sim4life, 3) when we are within a macro/guided mode.

- [ ] i can switch between nodes on a sublevel of the workbench through tabs on the top.

**Comment by KZzizzle** [comment]
@drniiken in guided mode this is now working and switching can be done in non-guided mode in the primary column of the GUI - feel free to add specification if you think there is more to do

**Comment by drniiken** [comment]
Thanks a lot @KZzizzle ... I'll have a look here, too.

**Comment by pcrespov** [comment]
Done
