### ISSUE TITLE
Bring osparc-filecomms under itis-foundation github (https://github.com/wvangeit/osparc-filecomms)

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1362]

**Comment by pcrespov** [comment]
> osparc-filecomms

@wvangeit you should be admin of the new repo https://github.com/ITISFoundation/osparc-filecomms

**Comment by wvangeit** [comment]
Thank you @pcrespov 
Code moved to https://github.com/ITISFoundation/osparc-filecomms
And have given that repo permission in pypi to publish to the appropriate store, rerun of an older merge ran successfully in Github Actions.
