### ISSUE TITLE
Deploy osparc_client with new endpoints to pypi

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1364]

**Comment by wvangeit** [comment]
@bisgaard-itis. I just remembered. Once the api changes is in the master branches, we also need to generate a new json file in the api python client I assume. And make sure the new client is deployed on pypi?

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis. I just remembered. Once the api changes is in the master branches, we also need to generate a new json file in the api python client I assume. And make sure the new client is deployed on pypi?

Yep, good point. But this should be very easy. Once we have the api-server changes in master I can take care of this in 1/2 hour.

**Comment by wvangeit** [comment]
@bisgaard-itis Is this something you could today?

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis Is this something you could today?

Definitely. Should we keep the studies endpoints in dev-mode? Or would you like that move them to "prodction mode"?

**Comment by wvangeit** [comment]
I think for this/next week we can keep it in dev mode.
