### ISSUE TITLE
Create itisfoundation empty repo for map service

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1373]
Repo is here: https://github.com/wvangeit/osparc-studymap
Let's use, as discussed, the following name for the repo: osparc-meta-parallelrunner

**Comment by pcrespov** [comment]
@wvangeit repo ready in  https://github.com/ITISFoundation/osparc-meta-parallelrunner
- I added you as admin and the rest of us (dev-team) with write access.

**Comment by wvangeit** [comment]
Thanks a lot @pcrespov
