### ISSUE TITLE
Memory used by Rabbit only goes up

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#138]
It only drops when we redeploy

![image](https://user-images.githubusercontent.com/33152403/74935191-249cdf00-53e8-11ea-9278-d16f9baf6fdf.png)

**Comment by odeimaiz** [comment]
It only goes down when we redeploy

**Comment by sanderegg** [comment]
fixed now through https://github.com/ITISFoundation/osparc-simcore/pull/1315
