### ISSUE TITLE
Computational services UI: warn users that they can't delete nodes while running

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1398]
![delete_nodes_pipeline](https://github.com/ITISFoundation/osparc-issues/assets/18575092/7bb5ce86-c206-431c-80a0-5f6aba323bc0)

Users are not allowed to delete nodes while their running, but they get the impression that they can.

We should show a message saying that they have to wait until the node has finished running before deleting it.

**Comment by sanderegg** [comment]
The delete text button should be disabled right?
