### ISSUE TITLE
CC Human 0D Solver not running

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#140]
studyId: 8fa45d79-740d-58dd-8764-e9c44a13f87e
serviceId: 16ad0938-ba39-50d6-89ce-e6c00d238fd0
https://osparc01.speag.com/graylog/messages/graylog_3/467ea8e0-53ea-11ea-9506-0242ac140007

**Comment by sanderegg** [comment]
fixed for some time already.
