### ISSUE TITLE
Make public: osparc python client with MM endpoints @bisgaard-itis

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1428]

**Comment by wvangeit** [comment]
@bisgaard-itis Not sure what exactly has to be done here, I assigned it to you.

**Comment by wvangeit** [comment]
Move this to nice-to-have, since it's not blocking anymore

**Comment by wvangeit** [comment]
@bisgaard-itis is this one done?

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis is this one done?

Yes, this is the studies part of the api which the latest released version of the client hits:

![image](https://github.com/ITISFoundation/osparc-issues/assets/126242332/bfa22433-825e-4d0f-b25e-358498556d91)
