### ISSUE TITLE
Make api-server entrypoints public https://github.com/ITISFoundation/osparc-simcore/pull/5792

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1432]

**Comment by matusdrobuliak66** [comment]
https://github.com/ITISFoundation/osparc-simcore/issues/5811

**Comment by bisgaard-itis** [comment]
We agreed that all the study endpoints except the following three should be published to production:
![image](https://github.com/ITISFoundation/osparc-issues/assets/126242332/94f3f0f8-1e74-4ab1-a57d-a364594e291c)

**Comment by wvangeit** [comment]
@pcrespov As discussion, I slightly updated the title of the task, and moved it to nice-to-haves (since it's not blocking anymore)

**Comment by bisgaard-itis** [comment]
I don't believe there is anymore to be done here. The `studies` endpoints will be made public next time there is a release to production.
