### ISSUE TITLE
Extend the number of input ports of Sim4Life services to 4

### ISSUE THREAD

**Issue by AntoninoMarioC** [ITISFoundation/osparc-issues#1470]
**Describe the user role**
Extend the number of input ports of Sim4Life services to 4. Only one is unpractical.
![image](https://github.com/ITISFoundation/osparc-issues/assets/34208500/b678860b-d0af-4673-940d-d79673376e4e)

**Comment by elisabettai** [comment]
Following up in fogbugz, please use this case: https://z43.fogbugz.com/f/cases/198926/Extend-the-number-of-input-ports-of-Sim4Life-services-to-4
