### ISSUE TITLE
Unstructured thermal solver on oSPARC

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1502]
Required for in silico safety assessment (partial blocker).

This requires porting the solver and working on the drag-and-drop.

from EN: "we also should include the unstructured thermal solver, required for the in silico safety assessment. apparently, it is not released on osparc. manuel wants to work a bit on source drag and drop."

**Comment by mguidon** [comment]
Also: There is no python API whatsoever.
