### ISSUE TITLE
Find a suitable grid/table library for the rocket

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#1520]

**Comment by jsaq007** [comment]
These are the top 5 I have come up with so far. My feeling is the best on to use would be MUI. Mainly it's what we use now for our styling and components. Integration would be the easiest. However the full features are paid ;( 

 
**Material-UI (MUI) Data Grid**
* Description: Part of the Material-UI library, offering robust features like sorting, filtering, and pagination.
* Link: [MUI Data Grid Documentation](https://mui.com/x/react-data-grid/demo/)
**AG Grid Community**
* Description: A feature-rich, highly customizable data grid with sorting, filtering, adding/removing rows and columns, and reordering.
* Link: [AG Grid](https://www.ag-grid.com/)
**react-table**
* Description: A lightweight and flexible library for building tables with sorting, filtering, and extensibility.
* Link: [react-table GitHub](https://github.com/TanStack/table)
**react-data-grid**
* Description: A highly customizable data grid for React with features like sorting, filtering, and row/column manipulation.
* Link: [react-data-grid GitHub](https://github.com/adazzle/react-data-grid)
**Handsontable**
* Description: A JavaScript/React data grid component with Excel-like features including sorting, filtering, and row/column reordering.
* Link: [Handsontable Documentation](https://handsontable.com/docs/javascript-data-grid/demo/)
