### ISSUE TITLE
Long filenames in File Broswer not displayed

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#1525]
https://z43.fogbugz.com/f/cases/196670/New-feedback-Long-filenames-are-not-disp

Also, @ignapas while you are at it: It would be nice if ESC would close the dialogs

**Comment by ignapas** [comment]
when is it that ESC does not close them?

**Comment by mguidon** [comment]
> When is it that ESC does not close them? Normally they should close. Maybe remote dialogs are not closed with ESC because they are server controlled.. we could think of a mechanism to make that work too

I meant the file browsers. They dont react on esc. With the remote ones you are right, this needs some work.
