### ISSUE TITLE
Disk usage indicator: total?

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1531]
It is not clear how much total space is available (observation from Team Black)
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/e8b0a4fb-116c-44db-a381-629de472b8e6)

**Comment by elisabettai** [comment]
@GitHK, do you also publish the total disk space available, so that it can be shown by the frontend? fyi @jsaq007

**Comment by GitHK** [comment]
> @GitHK, do you also publish the total disk space available, so that it can be shown by the frontend? fyi @jsaq007

Yes, the data is there

**Comment by elisabettai** [comment]
HI @jsaq007, do you think you can make the indicator show how much of the total space is used? as it is now it is not clear at all how much it is still available.

**Comment by elisabettai** [comment]
Hi @odeimaiz, in case you feel motivated in taking a look to this. 😉

**Comment by odeimaiz** [comment]
@elisabettai What do you suggest?

**Comment by elisabettai** [comment]
Mmh, maybe:
1. Show "current_use/total_available" as a text or
2. Make the button show that there's a limit (I am not sure what the current blue bar shows, is it a percentage?)

**Comment by odeimaiz** [comment]
1. I find that too long
2. I'll add a border to show that there is a limit...? Yes, it's the percentage

**Comment by elisabettai** [comment]
@odeimaiz, option 2 sounds good. This is what Team Black was expecting I think and they were confused that there was no second border
