### ISSUE TITLE
Bug when deleting file from "Service data" menu --> cannot start service anymore

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1532]
**Long Story Short**
When the Service data menu is used to delete files from a service's output, this change is not correctly propagated since the output is still visible in the sidepanel's outputs section. This missmatch then causes the service to not being able to start again. 

**Expected Behavior**
Deleting files from the service data environment should also update the UI outputs.

**Steps to reproduce**
- Create an interactive service
- put some data in the output
- go back to dashboard
- delete the file from the output using the "Service data" menu
- Try to restart the service

![image](https://github.com/ITISFoundation/osparc-issues/assets/61539759/9f21656b-bdb3-4baf-b458-6a5bb15bb1fb)

**Comment by odeimaiz** [comment]
Duplicated
https://github.com/ITISFoundation/osparc-issues/issues/1538
