### ISSUE TITLE
Cannot add "Everybody" to template after it has been shared with one or more users

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1583]
**Long Story Short**
![Cannot_share_template_witheverybody_after_creation](https://github.com/user-attachments/assets/40c4e282-a369-4a25-9d8c-5e0f7e0c12c7)

**More info**
This is on osparc.io. As I far as understand, we are not showing the product-specific "Everybody" in the view above.
Sharing with "Everybody" when publishing the template seems to work (at least the frontend part is there)

**Comment by odeimaiz** [comment]
Fixed in https://github.com/ITISFoundation/osparc-simcore/pull/6183
