### ISSUE TITLE
Add registration form for the oSPARC product

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1584]
**Describe the user role**
POs have agreed on adding a registration form to the osparc product.

**Additional context**
We can start from the one we have in s4l/tip and apply a few modifications documented in the pdf attached. 
[account_request_form_osparc.io.pdf](https://github.com/user-attachments/files/16410049/account_request_form_osparc.io.pdf)

fyi: @pcrespov, as we discussed 😊

**Comment by odeimaiz** [comment]
@pcrespov Backend work is required.

At the moment, in the product's vendor information we store the ``LOGIN_REGISTRATION_INVITATION_REQUIRED`` flag.

This flag is used by the frontend in two different ways:
- If the product is billable, a request form is show.
- If the product is non-billable, a pop window asks the user to send an email to product vendor email.

We now want to display a request form in a non-billable product, so the two solutions I see are:
- we add yet another flag or...
- we always show the request account form and we get rid of the send us an email pop up window (currently used in s4l-lite)
