### ISSUE TITLE
Random dynamic service disconnection

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1616]
I am getting this while playing with a  jupyter-math on NIH AWS staging, node uuid: `ea512f42-9834-4037-96d3-ce643558a56c`
![image](https://github.com/user-attachments/assets/e57d2e62-07a4-4d3d-8207-0207aa4574d1)

And after reloading the iframe (reload button in the UI), I get this:
![image](https://github.com/user-attachments/assets/985b8d0e-257f-4fbf-8fc7-a9a447502f57)

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/xdcswyxaki8e8fiyb8ifdsa88o) *by @elisabettai*._

**Comment by GitHK** [comment]
this can be safely closed since it's referenced by https://github.com/ITISFoundation/osparc-simcore/issues/6087
