### ISSUE TITLE
Update osparc-client version in all TIP services

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#1618]
in order to correctly show the parent services in the costs dialog the osparc-client version must be at least 0.7.x

**Comment by pcrespov** [comment]
![image](https://github.com/user-attachments/assets/3bfe1b60-6eb4-42e2-a1c5-a0a3ff30f888)

and `v0.8.2` [supports references to parents](https://github.com/ITISFoundation/osparc-simcore-clients/blob/v0.8.2/clients/python/client/osparc/_models.py)

**Comment by mrnicegyu11** [comment]
as written in the comment, I will close this issue. feel free to reopen.
