### ISSUE TITLE
tip-product on aws-master and aws-staging

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#1624]
We need to have a tip.product in the AWS staging and master.

Currently master:
- [osparc-master-zmt.click](http://osparc-master-zmt.click/)
Currently staging:
- [osparc-staging.io](https://osparc-staging.io/)
- [staging.s4l-lite.io](https://staging.s4l-lite.io/)
- [sim4life-staging.cloud](https://sim4life-staging.cloud/) (billable)

We need to add a new billable TIP product to both, which also means an additional DNS name I guess?

**Comment by YuryHrytsuk** [comment]
I am taking a lead on this issue

**Comment by pcrespov** [comment]
AFAIK This is done!

**Comment by YuryHrytsuk** [comment]
> AFAIK This is done!

We do not have a TIP Product on AWS Staging. 

But I think we are not going to introduce it since there seem to be no need. 

So, closing the issue
