### ISSUE TITLE
monitoring & observability for the EFS 

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#1630]
Prepare a plan for monitoring and observability of EFS, including specific actions to be taken (e.g., if a user consumes too much volume on EFS, we want to restrict their access). Begin implementation.

**Comment by matusdrobuliak66** [comment]
- https://github.com/ITISFoundation/osparc-simcore/pull/6493
 - https://github.com/ITISFoundation/osparc-simcore/pull/6502
 - https://github.com/ITISFoundation/osparc-simcore/pull/6540
 - https://github.com/ITISFoundation/osparc-simcore/pull/6562
