### ISSUE TITLE
Tutorial 1 (Nov.), tentative topic: metamodeling

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1632]
### Description
Two new tutorials that demonstrate modeling functionality useful to users in a ‘realistic’ example; tentative topics are 1. meta- modeling functionality (with a real example) and 2. CAD modeling (it can be a follow up of the one published in Y7Q3); topics may be adjusted as required

### Deliverable
Tutorial 1 published on the SPARC Portal or on the o²S²PARC documentation / GitHub

### Deadline
Y8Q1 (November)

Wrike [link](https://www.wrike.com/open.htm?id=1425078981) (account/access required)

**Comment by JavierGOrdonnez** [comment]
Tutorial completed last Monday. Publicly available at https://docs.sparc.science/docs/tutorial-running-a-metamodeling-pipeline .
