### ISSUE TITLE
Annoying "A new version of the application is now available" notification

### ISSUE THREAD

**Issue by calys** [ITISFoundation/osparc-issues#1697]
This notification popup persists even after reloading the page:

![Image](https://github.com/user-attachments/assets/55f4b977-44ce-4a5e-9087-d06dfb3a934b)

**Comment by odeimaiz** [comment]
The notification persists because you still might have the cached version. We need to find a way to make sure clients ask for brand new frontends when a new version is released.

**Comment by calys** [comment]
Thanks for the explanation @odeimaiz. I think this points to a few different things we need to fix:
- a brand new frontend refresh when there is a new version (as you mentioned)
- a notification like that should never be shown more than once (per version update), by design. In this case, I suppose it should only be triggered if the status of the application goes from "up-to-date" to "not so up-to-date anymore". This should only happen if a new version is pushed.
- if the application is not up-to-date, this fact should be shown somewhere in the UI. But it is a status, not a notification, and should therefore be less intrusive. There is actually an example of that in my screenshot above, because my Chrome browser was not up-to-date ("Finish Update" button at the top right).

**Comment by odeimaiz** [comment]
Resolved in https://github.com/ITISFoundation/osparc-simcore/pull/6397
