### ISSUE TITLE
TIP: lite

### ISSUE THREAD

**Issue by calys** [ITISFoundation/osparc-issues#1701]
Concept of TIP lite:
- ~only one product and one deployment~
- ~user accounts grant different types of access (full, lite, etc…)~
- new product, on **tip-lite.science**
- TIP lite is mostly the same as TIP, but with many features disabled

Users of TIP lite
- do not need to pay anything or provide credit card information

TIP lite [must have]:
- [x] only one TI planning template (“classic TI”)
- [x] only two anatomical models instead of five: MIDA anisotropic + Mouse
- [ ] disabled Exposure Analysis tab in "classic TI", show teaser instead
- [x] no Report generation in "classic TI"
- ~users can be "upgraded" to the full version of TIP by the POs~
- ~if users are "upgraded" from lite to full, they do not lose their data~

TIP lite [essentials]:
- [x] the logo is a little different
- [x] there is an "apply to the full version of TIP" message  shown "somewhere" on the dashboard [TBD]
- [x] the others five templates are greyed out
- [x] in "classic TI" template, the other three anatomical models are greyed out
- [x] in "classic TI" template, “Add to Report”, “Export Report” buttons are greyed out

TIP lite [good to have]:
- ~the others five templates are greyed out, and there is a message shown on the card on mouse hover [TBD]~

Management of existing users:
 - [ ] see #1713 

Notes:
- ~in the event that users are "downgraded" from full to lite, they should in principle not lose their data. They might, however, not be able to open some of their projects any more.~
- TIP lite is independent from the "full" TIP, in the sense that users can for now not migrate their projects from tip-lite.science to tip.science
- the current deployment at tip.itis.swiss remains as it is, essentially stuck at TIP V2.2, without the personalized plans

**Comment by matusdrobuliak66** [comment]
**Backend discussion:**
1. Api -> move user from product A to B (2 sprints)
2. Boot/env -> (1-2 sprints)
  - parts (TODO: @pcrespov please add description)
  - patch boot option only for tester in products
3. Redirect/logging in  -> (1 sprint)
4. EBS/buffer machines -> (2-3 sprints)

**Comment by pcrespov** [comment]
### TIP meeting

- SyR, OM, MD, PC, MS (online)
- Discussing mostly TIP lite https://github.com/ITISFoundation/osparc-issues/issues/1701
- Main features to develop
	- membership concept
	- boot of services
	- EBS
	- monitoring (startup time, usage)
- When to move to AWS tip.science ?
	- migration of users: https://github.com/ITISFoundation/osparc-ops-environments/issues/632
	- expose v3 only for testers

**Comment by pcrespov** [comment]
- [ ] url `tip-lite.science`   
	- [ ] AWS zmt account @YuryHrytsuk 
- [ ] product @pcrespov 
	- [ ] emails, templates urls, etc, vendors
	- [ ] fogbugz
	- [ ] tip-master-zmt.click, tip-lite-master-zmt.click, s4l-desktop-master.speag.com as tip-lite and request tip-lite-master.speag.com
- [ ] front-end @odeimaiz
	- [ ] assets: logo @calys 
- [ ] project templates ( 3 (v2) +3 (v3) + 1 (lite) )  @odeimaiz @Konohana0608 
	- [ ] 3 (v2) via migration review
	- [ ] 3 (V3) delete and redo 
	- [ ] 1 (lite) new
- [ ] services (8)
	- [ ] assign services to product 
	- [ ] services need to behave differently depending on the product they run (2)
		- [ ] TI postpro MS
		- [ ] Electron Selector  @odeimaiz 
	- [ ] ![|500](https://github.com/user-attachments/assets/a961a5f4-5103-4169-91f2-d8d2e11c49fc)
	- [ ] review service_access_rights
	- [ ] review prices
	- [ ] deprecate old versions
- [ ] users
	- [ ] migrated users and triage (who goes where) @calys @matusdrobuliak66 
	- [ ] make sure wallets are in place
- [ ] Add time spent to credits summary @matusdrobuliak66 @odeimaiz 
- [ ] e2e for lite @pcrespov 
      - (ti-place)
      - extend test that light users

**Comment by calys** [comment]
@pcrespov, @drniiken  
I updated the issue description and created a separate one regarding migration of existing users (#1713). Please also review and double-check that is is aligned with what you have in mind.
