### ISSUE TITLE
Making Logs In OSPARC Readeable

### ISSUE THREAD

**Issue by AntoninoMarioC** [ITISFoundation/osparc-issues#1702]
**Describe the user role**
Extract information from logs is very difficult.
1. The full log text doesn't automatically fit with its window, long messages are shown only for the window length. The only option is to download the log
2.  The log is massive with logs from all services and the platform. It is not easy to find the right information, e.g. from a specific service.

**Describe the goal**
What is needed:
1. Fix the issue 1, with the log being fully displayed within the window, and not in one string/line
2. Enable downloading service specific logs, and not the massive log

**Comment by odeimaiz** [comment]
Implemented in https://github.com/ITISFoundation/osparc-simcore/pull/6222
