### ISSUE TITLE
Addressing multiple opened tabs for the same user

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-issues#172]
**Describe the user role**

As a SPARC user, I would like to have some visual feedback when I am working with multiple tabs. The tabs could be opened:
- in the same browser
- in different browsers
- on different computers
- a mix of the above

The visual feedback should inform me that I am not using the most recently interacted with tab. Also a button to take control of this tab should be present.

**Describe the goal**

The idea is **to avoid content sync between tabs**. It is hard to get right. The suggested approach allows for a relatively simpler and robust implementation.

**Describe the benefit**

Avoids issues caused by working on old tabs containing possibly not updated content. In the current build, without a page refresh the content is not be updated. This can cause a lot of unexpected edge cases.

Taking control of a tab, causes all other tabs to become inactive and block user interaction.

**Additional context**

Suggested implementation:
-  use socket.io to keep track of the last time the user interacted with the tab (mouse & keyboard input), a dedicated event will be sent via socket.io when user interacts with the page
- the backend can keep track (in Redis) of the user's active tab
- all other tabs will be marked as not active and a message will be displayed blocking all user interaction
- upon reconnection the frontend should always check if the current tab is an active tab and update it accordingly
- when a user takes control of a tab, the page should be refreshed (updates the content)

Use Cases:

- account is shared between multiple users
- account is used by the same user on multiple computers or browser tabs

**Comment by ignapas** [comment]
The only problem I see here is that refreshing the page cannot guarantee that the user will get the same view he had before

**Comment by elisabettai** [comment]
Need further ample discussion.

**Comment by GitHK** [comment]
This is outdated, we are now having locks on used projects.
