### ISSUE TITLE
s4l-lite.io: Release 8.0.2

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#1736]
On October 10, 2024 we will release a new version of sim4life lite. It will be based on 8.0.2. We will release the new version early on to s4l-lite.io such that the app-team can test functionality and tutorials. (Procedure to be outlined by MaG). 
At the day of the release, the new version will be shared with everyone.
```[tasklist]
### MartinKippenberger
- [x] Publish/Test Release Candidate
- [x] Service Homepage Markdown
- [x] App Team testing form week from 30th Sept on s4l-lite.io
- [x] Buffer-Machine Configuration
- [x] DB Configuration
```

**Comment by matusdrobuliak66** [comment]
🚀 released

**Comment by pcrespov** [comment]
## [MartinKippenberger Sprint](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20241028_MartinKippenberger.md)
- Used new features in https://github.com/ITISFoundation/osparc-issues/issues/1404 in the release of new s4l-lite service
- Recommend reviewing how to test and upgrade tutorials 
- Recommend reviewing UX for sharing (projects, services, ...)
