### ISSUE TITLE
Collapsable folder icon - frontend change request

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#1740]
> When a folder contains no folders, can it be shown without a collapsible button next to it, in the folders view which will open when a project is moved to a folder? In this way we can avoid showing a loading icon when the collapsible button is clicked, but there is nothing to be loaded.
> 
> Thank you,\
> Cosimo
> 
> ![Image](https://github.com/user-attachments/assets/9c51775f-3618-4a31-876a-04723e039cec)
> 
> ![Image](https://github.com/user-attachments/assets/1284f8cc-3330-446c-9e71-7a5133aea7c6)
> 
> ![Image](https://github.com/user-attachments/assets/1b79c678-cfc3-430f-aa67-9e3f13329e9e)
> 
>  

 _Originally posted by @cosfor1 in [#716](https://github.com/ITISFoundation/osparc-issues/issues/716#issuecomment-2378786525)_

**Comment by odeimaiz** [comment]
implemented in https://github.com/ITISFoundation/osparc-simcore/pull/6457
