### ISSUE TITLE
Guided Tours Broken in S4L-lite

### ISSUE THREAD

**Issue by capbrown** [ITISFoundation/osparc-issues#1746]
The guided tours button in the lite version isn't working. It open a menu, but does not have any guides.
![guided_tours](https://github.com/user-attachments/assets/4969a68a-53a9-4386-8590-ce6ff3415455)

**Comment by capbrown** [comment]
@ignapas  @pcrespov @eofli Do you know if this could be included in the upcoming release, or at least as its own update soon after? I believe that of all the front end related issues I created, this should be a priority because lite users are those who benefit from it most.

**Comment by ignapas** [comment]
> @ignapas @pcrespov @eofli Do you know if this could be included in the upcoming release, or at least as its own update soon after? I believe that of all the front end related issues I created, this should be a priority because lite users are those who benefit from it most.

will check and come back too you asap, thank you!
