### ISSUE TITLE
Out of date nodes

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#1811]
If the inputs of a computational node that has been executed change, the state of the node would change from "Success" to "modified".

At some point (I guess with PATCH node), we lost this feature and therefore the frontend can't paint the nodes and edges that are out of date orange. We need to bring back a mechanism to let the backend notify the frontend about changes in the states.

PR when this was implemented:
https://github.com/ITISFoundation/osparc-simcore/pull/2153

Currently:
![OutOfDate](https://github.com/user-attachments/assets/19583143-2ee0-4b73-b299-18ed85df588c)

After reloading, the status is fetched:
![Reload](https://github.com/user-attachments/assets/91e6c16f-cd7f-4092-b805-ae4bf3080c40)

```[tasklist]
### Event Horizon
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6970
```

**Comment by odeimaiz** [comment]
I believe the reason is that when the backend is running a pipeline, it keeps the frontend updated with websocket messages. Since we introduced the PATCH, the frontend patches, but it doesn't get an updated state in the response, hence the status of the outputs get outdated.

**Comment by sanderegg** [comment]
This entry might be linked: https://github.com/ITISFoundation/osparc-simcore/issues/6505

**Comment by giancarloromeo** [comment]
@odeimaiz this one fixes the preoblem whenever inputs are changed. 
For the outputs, please refer to this other one: #6963
