### ISSUE TITLE
3D image occasionally disappears when rotating/scrolling

### ISSUE THREAD

**Issue by ilya747** [ITISFoundation/osparc-issues#233]
## Long story short

3D visualisation disappears occasionally when rotated with the left mouse button. It vanished completely when I tried to magnify it by scrolling the wheel
## Expected behaviour

Image can be rotated and magnified easily using the mouse. The same as it works in SPARC nerve activity predictor.
## Actual behaviour

Image disappears. Occasionally or completely. Sometimes I could get it back by clicking the white button on the top-right, and sometimes I had to restart the node. 
## Steps to reproduce

Open "3DVisualization of EM-Neuro". Double-click "3d-viewer-gpu". Open the image full screen. Start it (action potential travels), then stop. Rotate the visualisation and magnify it using the mouse. Image disappears.
PS - I'm a member of TeamBlack, but I wasn't able to add a black "Feedback" label to the issue (I accessed GitHub through the link in the osparc interface).
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "46dd09f",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/46dd09f/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "9082a78",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/9082a78/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.1.2",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.13",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.49.1",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by KZzizzle** [comment]
DoD: change default of "Interactive Image Ratio" setting to <1, give a tip to user about what the default parameter is and why it is set this way.

**Comment by odeimaiz** [comment]
Dear @ilya747,

What we thought could be a solution doesn't actually fix it, but it helps avoiding the black screen.

As Katie mentioned, here the steps that help:
![asdf](https://user-images.githubusercontent.com/33152403/88806774-221d8d00-d1b1-11ea-95ff-0a40ef9beced.gif)

**Comment by pcrespov** [comment]
no bandwidth
