### ISSUE TITLE
Broke 3D Viewer

### ISSUE THREAD

**Issue by arowald** [ITISFoundation/osparc-issues#234]
## Long story short
I tried to visualize some 3d objects by using a file-picker and coupling it to the 3d-viewer. I accidentally generated a sphere. While I could delete the sphere and use one of the uploaded structures I could not a) access the other structures and b) refresh or interact with the 3d viewer.

## Expected behaviour
I would have expected to be able to upload and interact with more than one structure but that seems to only be possible by compressing them into zip 

I also would have expected for the 3d viewer to show me current selections and get rid of deleted elements. Unfortunately it crashed.

## Actual behaviour
Only the first structure I uploaded was accessible

The 3d viewer showed me exactly what I was doing until I deleted the sphere at which point I could no longer get visual updates on what was happening.

## Steps to reproduce
Upload a file, create a sphere, delete the sphere, link your object, sphere should still be there and your uploaded structure won't

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "46dd09f",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/46dd09f/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "9082a78",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/9082a78/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.1.2",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.13",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.49.1",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by pcrespov** [comment]
no bandwidth
