### ISSUE TITLE
Where are the physics solvers?

### ISSUE THREAD

**Issue by arowald** [ITISFoundation/osparc-issues#235]
**Describe the user role**
I would like to translate my Sim4Life pipeline into OSPARC. For this I need access to the same/similar physics-based solvers as with Sim4Life. In my particular context, I am most interested into solving Maxwells equations under quasistatic approximation so something like a quasi-static solver for Electrodynamics would be great. I can't find such a module implemented.

**Describe the goal**
Calculate the electric field, current or potential in a biological tissue.

**Describe the benefit**
Development of neuromodulation therapies.

**Additional context**

**Comment by ceiber-uom** [comment]
This is critical for me as well.

**Comment by KZzizzle** [comment]
@ilya747 Jupyter FEniCS (homepage here https://fenicsproject.org/) is now deployed on staging and production of o2S2PARC. Let us know if it is helpful and if you would like additional supporting modules preinstalled.

**Comment by KZzizzle** [comment]
The Jupyter Smash service is now available on osparc staging. To test, please follow the tutorial: https://itisfoundation.github.io/osparc-manual-z43/#/Tutorials/Sim4LifeParallelPlate

**Comment by KZzizzle** [comment]
![image](https://user-images.githubusercontent.com/28002886/100635388-c286e800-3330-11eb-8830-12594b886051.png)
