### ISSUE TITLE
flowchart disappeared from workbench but is still accessible through service tree

### ISSUE THREAD

**Issue by arowald** [ITISFoundation/osparc-issues#236]
**Long Story Short**
Closed my study on one computer. Opened it up on another computer and the components of the workbench disappeared but are still in the service desk.

**Expected Behavior**
Components are always visible on workbench.

**Actual behaviour**
Components disappeared.

**Steps to reproduce**
This seems to happen randomly. I tried a bunch of permutations of including components in the workflow and opening and closing them on different computers. On the same computer I never had the issue. With another computer sometimes the components disappear seemingly at random.

**Environment**
Chrome

**Additional context**

**Comment by KZzizzle** [comment]
continued testing required, try to reproduce with more pipelines

**Comment by KZzizzle** [comment]
stale issue - closing
