### ISSUE TITLE
folder structure of jupyter notebook is inaccessible via jupyter-base-notebook

### ISSUE THREAD

**Issue by arowald** [ITISFoundation/osparc-issues#238]
## Long story short
I tried to access the folder structure (_input,_output, etc) via jupyter-base-notebook. It is inaccessible but the output subfolders show up when linking the component with another component like the table-viewer.

## Expected behaviour
Expected to see the folders in the notebook or at least via the python code:
import os
import pathlib
output_folder = os.path.join(pathlib.Path().absolute())
my_list = os.listdir(output_folder)

## Actual behaviour
subfolder are inaccessible both via python script and the notebook

## Steps to reproduce
Just open jupyter-base-notebook.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "46dd09f",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/46dd09f/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "9082a78",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/9082a78/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.1.2",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.13",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.49.1",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by pcrespov** [comment]
@arowald we will discontinue support to this service. Instead, I recommend you using Jupyterlab as an alternative (under Discover tab, search for Jupyterlab) 

![image](https://user-images.githubusercontent.com/32402063/95960539-264a6580-0e04-11eb-856d-bb7842324845.png)

You have similar folder structure for data exchange with other services that is accessibles from the scripts
![image](https://user-images.githubusercontent.com/32402063/95960706-5c87e500-0e04-11eb-8fe4-a490dd8a39d7.png)

Our manual also include an introduction about this service
http://docs.osparc.io/#/docs/study_setup/JupyterLabs?id=jupyter-octavepython-math
