### ISSUE TITLE
More informative system status reporting when running the pipeline

### ISSUE THREAD

**Issue by HaiboNi** [ITISFoundation/osparc-issues#239]
**Describe the user role**
As a SPARC user, I want to see a more informative system running status, so that I can understand if the pipeline is running or if any error has occurred. 

**Describe the goal**
Modify the 'Run' and 'Stop' button after it is clicked.  It would be great if the progress bar of each flow chart is colored. 

**Describe the benefit**
It would be immediately clearly to the user about the progress of the pipeline/simulation. 

**Additional context**

**Comment by KZzizzle** [comment]
Get StS to weigh in on how this should behave and how this should be implemented.

Things to consider:
Global progress bar
signal indicating when each node is completed 
Ready -> Available

**Comment by KZzizzle** [comment]
current request: place a global status bar on the bottom of the workbench, next to/near the "Run" button" or animate the the run button

visual cue that the pipeline has begun to run.

**Comment by KZzizzle** [comment]
Documentation added here: http://docs.osparc.io/#/docs/submission?id=showing-progress
