### ISSUE TITLE
Visual cue for connecting nodes

### ISSUE THREAD

**Issue by ceiber-uom** [ITISFoundation/osparc-issues#242]
**Describe the user role**
As a user of o²S²PARC, in the main workbench

**Describe the goal**
A subtle highlight to show when you’re in the hitbox of the click-and-drag would be nice – the yellow effect from the documentation would be good. Also, click-click without drag would be nice, particularly for very large models.

It took me a while to figure out that you had to click on the "out" and drag - there's no visual cue that there's an opportunity to do something when the link doesn't exist - I tried shift- and ctrl-clicking, double-clicking, single-clicking, even dragging the boxes together so the "in" and "out" ports coincided (hey, it works in spice / eagle). 

**Describe the benefit**
You can start to build models without referring to the documentation and navigating through 3+ pages to find out how to do this basic task

**Comment by KZzizzle** [comment]
Get StS input on how this should look and ideal user experience before giving a point value

**Comment by KZzizzle** [comment]
Documentation for this feature is found here: http://docs.osparc.io/#/docs/study_setup/connecting_services?id=connection-indicator
