### ISSUE TITLE
repository for studies/templates/services

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#252]
we would like to have a separate _hub_, which can host templates, studies, and services (distinction is increasingly artificial, but that is another discussion). it draws its content from (potentially multiple) repositories. for items that do not contain heavy data, these repositories are likely to be based on _github/gitlab_.
once the hub has been made aware of certain repositories, it is possible to browse, search and field items, based on meta-data and popularity (general and user-specific). criteria can include usage frequency, degree of V&V...
this can then be leveraged from within _osparc_ to search for studies, templates, and services.

note: it can also be a good platform on which to build versioning functionality.
note: we could also have _Binder_-like functionality to open a search result in _oSPARC_.
note: the hub is also the 'app store'
note: pull requests in _github/gitlab_ are a valuable workflow for QA (peer reviews, automatic validation...)

for illustration, check:
- https://ch.mathworks.com/matlabcentral/fileexchange
- https://tfhub.dev

implementation idea: hub points to repository. git contains light-weight version-controlled information (incl. scripts) that points to data repositories (S3) and _docker_ registeries.
repositories can be private or public, controlling access, e.g., for privacy or licensing. same is true for data.

**Comment by pcrespov** [comment]
no bandwidth. Already discussed in #68
