### ISSUE TITLE
Workbench can not be maneuvered

### ISSUE THREAD

**Issue by arowald** [ITISFoundation/osparc-issues#253]
**Describe the user role**

SPARC investigator

**Describe the goal**

I wanted to build a larger project with lots of nodes. However, on my laptop screen (which is small) my workbench is completely filled. I would like to move around on the workbench (left,right,up,down) but this is not possible it seems. A simply UI change so that I can use my mousepad for maneuvering would be nice.

**Describe the benefit**

One of the major benefits of osparc for me is that I no longer would need to sit in front of my workstation to set up, run and analyze a simulation. Unfortunately, everything I am interested in doing, uses at least 10+ nodes. On my small 13 inch laptop screen, the workbench is completely full and I can not work efficiently.

**Additional context**

Tested on Macbook Air.

**Comment by KZzizzle** [comment]
developer estimate: 6 points
