### ISSUE TITLE
Jupyter notebook erroring

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#255]
## Long story short
When opening my dashboard, one of my jupyter notebooks shows error and I cannot open it anymore

## Expected behaviour
When I click a Jupyter notebook that shows "error" in the dashboard, I would expect that I see a more descriptive information why the notebook is not starting. Right now I do not know if it is a system issue or is a user mistake.

## Actual behaviour
When double clicking on a jupyter notebook that shows error, I just receive a message saying that the notebook is failing to start

## Steps to reproduce
Double click to open a jupyter notebook which is "error" state

![osparc_20200612_1](https://user-images.githubusercontent.com/2193724/84497495-e79d7680-ac7c-11ea-8160-20f9bba4cfc4.png)

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "5ed8a8f",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/5ed8a8f/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "a75a741",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/a75a741/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by nitrosx** [comment]
Here is the view in the dashboard:
![osparc_20200612_2](https://user-images.githubusercontent.com/2193724/84497636-31865c80-ac7d-11ea-8e09-6ed7b5c7dd4c.png)

**Comment by KZzizzle** [comment]
A more helpful error message would also be nice - for example, if the code would be stil accessible but there was a problem with pulling the image.

**Comment by KZzizzle** [comment]
additionally, could instruct the user what they should do (e.g. submit ticket, etc.)
