### ISSUE TITLE
 intended usage of "Organizations"

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#262]
What is the intended usage of "Organizations" under the preferences profile settings tab?

**Describe the user role**
Under Preferences -> Profile settings, there is a section named Organizations with what appears to be a text area.
This space is empty and clicking on it highlights it but it does not enable editing.

**Describe the goal**
If the intended behavior is to allow the user to specify her own affiliation, she should be able to edit and add the relative information.
If the organizations information is pulled from somewhere else, it should be duly noted that this is a read-only value

**Comment by KZzizzle** [comment]
@odeimaiz in case you are working with the access rights at some point, perhaps this could be integrated.

**Comment by odeimaiz** [comment]
Deprecated. The current organization management tab replaces it
