### ISSUE TITLE
Search & Discover

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#265]
A way to search for templates, studies and services is required. This is a proposal, that is up to discussion:
- combination of text search & faceted search (similar to fogbugz search)
- criteria
  - creator/ownership
  - meta data text
  - tags
  - hierarchy (see below)
- sorting should reflect match, but can later be extended with intelligence to reflect usage frequency, quality rating, user-specific activity...

two types of tags:
- arbitrary tags, created by the user
- standardized/curated tags (classifiers) across all users (perhaps later also organization/group-specific), with review process for acceptance

hierarchy:
- initially for z43
- hierarchical structure (tree), managed only by 'administrators' (same administrators that can also create groups)

This search&discover functionality should be usable as an element in different places:
- to find a service on the desktop (service browser)
- to create a new study following a template from the dashboard (button next to the 'new empty study' button)
- ...

**Comment by ignapas** [comment]
## Update on XieXie
### Classifiers repository
* [This](https://git.speag.com/curated-data/classifiers) repo is created to store the classifiers
* CI creates a JSON file that can be consumed by other entities.
### Classifiers service (TODO)
* A service in oSPARC consumes the data and assigns classifiers to services (@KZzizzle please correct)
### Search by classifiers (front-end)
* A checkbox tree component is implemented
* This tree is used by a a filter component
* The filter is used in the discovery tab

**Comment by drniiken** [comment]
focusing on classifiers and frontend in the next sprint
