### ISSUE TITLE
HW/SW Dev Support Case: Online Material Database for Solid Materials

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#266]
Dear Team,

as mentioned in the review meeting, we'll be continuously supporting the HW/SW team with dev and help tasks, which I'm distributing among our entire Team ... so here is one for the oSPARC subgroup.

This request comes from Sina.
Please find his basic user story provided right below.
For additional details, I suggest to get in contact with him directly.

I also attached the link to the current tissue-frequency-chart of the tissue properties database:
https://itis.swiss/virtual-population/tissue-properties/database/tissue-frequency-chart/

Thanks and best, Nik

**HW/SW Dev Support Case: Online Material Database for Solid Materials**

**User Story**

Currently we are missing a universal data base of solid materials used in our products (similar to our tissue data base).  Such data base is beneficial in material selection procedure in product development and ultimately can be imported in Sim4Life for simulation purposes. 

**Acceptance Criteria**

User should be able to:

- [x] obtain dielectric properties of different materials at a defined frequency, temperature over 4MHz-67 GHz. Linear interpolation is needed for the interval frequencies. (Bryn has already implemented the frequency interpolation)

- [x] plot the dielectric properties of different materials within the 4MHz-67 GHz range (please see attached).

- [x] export the data if needed

![Screenshot 2020-06-22 at 09 29 14 (2)](https://user-images.githubusercontent.com/32800795/87039295-3f34f080-c1ef-11ea-8e08-f27d49f10eab.png)

**Comment by pcrespov** [comment]
## Update on sprint [Xie Xie](https://github.com/ITISFoundation/osparc-issues/milestone/7)

# Current Status

- **Curated Data Repository**: https://git.speag.com/curated-data/materials
   - Data curator uses a web interface to submit new data. 
   - CI validates it and provides means for peer-review
   - data is versioned and bundled with extra metadata and ready to be consumed by any external service
- **Frontend**: ... TODO
