### ISSUE TITLE
Jupyter Octave + Python Maths Feedback

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#267]
This is a placeholder issue for all issues concerning the Jupyter Octave + Python Maths service. To add your feedback, please directly comment on this issue. This way we can keep all related feedback in one place.

**Comment by nitrosx** [comment]
When working in the same notebook, variables are not persistent between the octave and python kernel, although I can switch between them from one cell to the next.
If this is the intended behaviour, it should be clearly communicated to the user.

**Comment by nitrosx** [comment]
Top panel with settings cannot be collapsed like the side panels, taking away real estate once the user has selected the inputs or other settings.
Can it be made collapsible?

**Comment by nitrosx** [comment]
Do we have an example on how to access input files from within notebooks?

**Comment by nitrosx** [comment]
Are python modules installed through pip persistent across sessions?
If not, it has to be clearly communicated and a solution/automation should be provided.
What about octave "modules/packages"? Can they be installed through the terminal?

**Comment by nitrosx** [comment]
When I restart the kernel, there is no option to also clear the output in the notebook.
Can we add this feature?

**Comment by nitrosx** [comment]
Full screen mode: how much would it take to implement a full screen mode? Would it be useful for other users?

**Comment by nitrosx** [comment]
I tried to install the cartopy module, but it failed.
Here is the pip command:
`.venv/bin/pip install cartopy`

What should the user do in this cases? Should we provide some kind of "how-to"?

**Comment by nitrosx** [comment]
I was playing around with hvPlot and pyviz following the following tutorials: 
- [https://hvplot.holoviz.org/](https://hvplot.holoviz.org/)

I also installed the pyviz module following their "Getting Started" page
- [https://hvplot.holoviz.org/getting_started/index.html](https://hvplot.holoviz.org/getting_started/index.html)

Pip install worked fine, but their command to enable it in jupyter lab stalled without message. It did not failed, it just hanged there.
Here is the command that I run in the terminal:
`jupyter labextension install @pyviz/jupyterlab_pyviz`

Are this kind of operation permitted? What is the best practice for cases like this one?

**Comment by nitrosx** [comment]
This morning when I logged back in into my study, I open my Jupyter block, and the notebooks that I created yesterday were not found.
When I clicked on the "work" folder, I received an error message saying "Directory not found". Here is the screenshot.
![jupyter_octave_python_error_1](https://user-images.githubusercontent.com/2193724/89301586-d4cd6f80-d637-11ea-9414-508761ed5456.png)

Now the jupyter lab interface is unresponsive. When I click on Dimiss, it appears right away

**Comment by HaiboNi** [comment]
When I tried to build the service and edit the mattward-viewer, the webpage became frozen at the parameter input page and did not respond to any clicks. 
<img width="1416" alt="Screen Shot 2020-08-30 at 5 03 20 PM" src="https://user-images.githubusercontent.com/4180875/91672429-64edc000-eae3-11ea-8ceb-7c2a2f094ed1.png">

**Comment by HaiboNi** [comment]
## Renaming the study/service resulting in an error message
When I attempted to rename the service as highlighted in the screenshot, an error message came out, although the renaming appeared successful.
<img width="1322" alt="Screen Shot 2020-08-30 at 5 56 22 PM" src="https://user-images.githubusercontent.com/4180875/91673780-961dbe80-eaea-11ea-892f-a4f9b9393aa8.png">

**Comment by KZzizzle** [comment]
> When I tried to build the service and edit the mattward-viewer, the webpage became frozen at the parameter input page and did not respond to any clicks.
> <img alt="Screen Shot 2020-08-30 at 5 03 20 PM" width="1416" src="https://user-images.githubusercontent.com/4180875/91672429-64edc000-eae3-11ea-8ceb-7c2a2f094ed1.png">
> 
> Then, I refreshed the webpage and clicked on the service/study, a message on the top read "Study is opened" without actually opening the service. Clicking a different service and then coming back to the dashboard, I was able to access the service of interest.
> <img alt="Screen Shot 2020-08-30 at 5 12 24 PM" width="1297" src="https://user-images.githubusercontent.com/4180875/91672623-68357b80-eae4-11ea-8eed-7c9fc7d093c9.png">

This has now been fixed, could you confirm?

**Comment by KZzizzle** [comment]
> ## Renaming the study/service resulting in an error message
> When I attempted to rename the service as highlighted in the screenshot, an error message came out, although the renaming appeared successful.
> <img alt="Screen Shot 2020-08-30 at 5 56 22 PM" width="1322" src="https://user-images.githubusercontent.com/4180875/91673780-961dbe80-eaea-11ea-892f-a4f9b9393aa8.png">

This has now been fixed - please confirm

**Comment by pcrespov** [comment]
> I was playing around with hvPlot and pyviz following the following tutorials:
> 
> * https://hvplot.holoviz.org/
> 
> I also installed the pyviz module following their "Getting Started" page
> 
> * https://hvplot.holoviz.org/getting_started/index.html
> 
> Pip install worked fine, but their command to enable it in jupyter lab stalled without message. It did not failed, it just hanged there.
> Here is the command that I run in the terminal:
> `jupyter labextension install @pyviz/jupyterlab_pyviz`
> 
> Are this kind of operation permitted? What is the best practice for cases like this one?
>

@nitrosx installing lab extensions sometimes requires rebuilding jupyter lab app (i.e. it does ``jupyter lab build -y`` behind scenes. For the moment, non-admin users do not have permissions to do that. 

In any case, I noticed that there is a way to install [extensions from the UI](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#using-the-extension-manager)

**Comment by pcrespov** [comment]
> I tried to install the cartopy module, but it failed.
> Here is the pip command:
> `.venv/bin/pip install cartopy`
> 
> What should the user do in this cases? Should we provide some kind of "how-to"?

This python package has some non-python external dependencies that are not installed and pip does not know how to compile. In this particular case the package is missing two, namely GEOS and Proj [see issue cartopy issue 1471](https://github.com/SciTools/cartopy/issues/1471#issuecomment-588981410)

Installing non-python dependencies is one of the weakness of pip. Alternatively you can use conda, i.e. ``conda install cartopy`` . conda offers a repository that takes care of these dependencies as well and if they happen to have the library you are interested, it is the best way to go. In this case, I managed to install this library without errors

**Comment by KZzizzle** [comment]
> Top panel with settings cannot be collapsed like the side panels, taking away real estate once the user has selected the inputs or other settings.
> Can it be made collapsible?

Full-screen mode of JupyterLab fulfills this success criterium

**Comment by KZzizzle** [comment]
> Do we have an example on how to access input files from within notebooks?

Explanation of this should be added to documentation

**Comment by KZzizzle** [comment]
> Are python modules installed through pip persistent across sessions?
> If not, it has to be clearly communicated and a solution/automation should be provided.
> What about octave "modules/packages"? Can they be installed through the terminal?

First, add to documentation. Then once we have a better solution, we will add this to documentation as well.

**Comment by KZzizzle** [comment]
> When I restart the kernel, there is no option to also clear the output in the notebook.
> Can we add this feature?

unable to reproduce

**Comment by KZzizzle** [comment]
> Full screen mode: how much would it take to implement a full screen mode? Would it be useful for other users?

Paused until use case is defined

**Comment by KZzizzle** [comment]
> This morning when I logged back in into my study, I open my Jupyter block, and the notebooks that I created yesterday were not found.
> When I clicked on the "work" folder, I received an error message saying "Directory not found". Here is the screenshot.
> ![jupyter_octave_python_error_1](https://user-images.githubusercontent.com/2193724/89301586-d4cd6f80-d637-11ea-9414-508761ed5456.png)
> 
> Now the jupyter lab interface is unresponsive. When I click on Dimiss, it appears right away

paused until we see issues on production

**Comment by KZzizzle** [comment]
> When I tried to build the service and edit the mattward-viewer, the webpage became frozen at the parameter input page and did not respond to any clicks.
> <img alt="Screen Shot 2020-08-30 at 5 03 20 PM" width="1416" src="https://user-images.githubusercontent.com/4180875/91672429-64edc000-eae3-11ea-8ceb-7c2a2f094ed1.png">
> 
> Then, I refreshed the webpage and clicked on the service/study, a message on the top read "Study is opened" without actually opening the service. Clicking a different service and then coming back to the dashboard, I was able to access the service of interest.
> <img alt="Screen Shot 2020-08-30 at 5 12 24 PM" width="1297" src="https://user-images.githubusercontent.com/4180875/91672623-68357b80-eae4-11ea-8eed-7c9fc7d093c9.png">

Arrange meeting with Haibo to try to debug

**Comment by KZzizzle** [comment]
Newest JupyterLab Octave + Python maths is now available on staging! Version 1.4.0

**Comment by KZzizzle** [comment]
> > Are python modules installed through pip persistent across sessions?
> > If not, it has to be clearly communicated and a solution/automation should be provided.
> > What about octave "modules/packages"? Can they be installed through the terminal?
> 
> First, add to documentation. Then once we have a better solution, we will add this to documentation as well.

added to documentation: http://docs.osparc.io/#/docs/setting_up___running_a_study/JupyterLabs?id=items-of-note

**Comment by KZzizzle** [comment]
> > Do we have an example on how to access input files from within notebooks?
> 
> Explanation of this should be added to documentation

The documentation for this feature can be found here: http://docs.osparc.io/#/docs/study_setup/JupyterLabs?id=input-and-output-ports-in-jupyterlab
