### ISSUE TITLE
OpenCOR (Computational) Service Feedback

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#268]
This is a placeholder issue for all issues concerning the OpenCORE service. To add your feedback, please directly comment on this issue. This way we can keep all related feedback in one place.

- [x]  disable Run button when the computation is running

**Comment by nitrosx** [comment]
In openCOR, is it possible to disable the Run button when computation is running?

**Comment by KZzizzle** [comment]
developer estimate: 1 point

**Comment by nitrosx** [comment]
Output file is not persistent across sessions (aka if I log out and log back in).
If this is the intended behaviour, it should be clearly communicated to the user.
Can it be made persistent?

**Comment by HaiboNi** [comment]
The output data file from simulations appears persistent now. However, the jupyter notebook I created was lost when I went to the dashboard and then click on the same service. 
* The jupyter notebook I created: 
![Screenshot at 2020-08-30 17-36-20](https://user-images.githubusercontent.com/4180875/91673277-40e0ad80-eae8-11ea-9486-6eb719684d4e.png)
* The jupyter notebook was not present when I came back to the service, although the jason output file was still there: 
![Screenshot at 2020-08-30 17-38-12](https://user-images.githubusercontent.com/4180875/91673307-71284c00-eae8-11ea-8eca-5f142945d377.png)

**Comment by KZzizzle** [comment]
> Output file is not persistent across sessions (aka if I log out and log back in).
> If this is the intended behaviour, it should be clearly communicated to the user.
> Can it be made persistent?

please share the study (unless it's inside a Jupyterlab older than 1 month) because it seems to be a bug

**Comment by KZzizzle** [comment]
> The output data file from simulations appears persistent now. However, the jupyter notebook I created was lost when I went to the dashboard and then click on the same service.
> 
> * The jupyter notebook I created:
>   ![Screenshot at 2020-08-30 17-36-20](https://user-images.githubusercontent.com/4180875/91673277-40e0ad80-eae8-11ea-9486-6eb719684d4e.png)
> * The jupyter notebook was not present when I came back to the service, although the jason output file was still there:
>   ![Screenshot at 2020-08-30 17-38-12](https://user-images.githubusercontent.com/4180875/91673307-71284c00-eae8-11ea-8eca-5f142945d377.png)

we have now fixed this with our newest version of the Jupyterlab

**Comment by KZzizzle** [comment]
> Output file is not persistent across sessions (aka if I log out and log back in).
> If this is the intended behaviour, it should be clearly communicated to the user.
> Can it be made persistent?

please add to documentation that anything outside home folder is not persistent

**Comment by sanderegg** [comment]
> When computation is running, the "Run" button does change its state.
> Would it possible to disable the Run button when the computation is running?

The Run button shows now a spinning button while the pipeline is running. additionally a "Stop" button has been implemented and allows to stop a running pipeline.
