### ISSUE TITLE
Jupyter Octave + Python Maths does not save state

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#269]
**Long Story Short**
If files are added to the workspace of a jupyter+octave+python maths notebook, or a new notebook is created, these do not persist after leaving the study and going back to the dashboard

**Expected Behavior**
Uploaded files and notebooks stay in the service unless they are deleted by the user

**Actual behaviour**
Files disappeared upon re-entry into the study 

**Steps to reproduce**
* Create a study, create a jupyter+octave+pythonmaths 
* Drag and drop files into the jupyter+octave+pythonmaths notebook or add a new pythonmaths notebook
* go back to the dashboard
* enter back into the same study

**Environment**
chrome

**Additional context**

**Comment by sanderegg** [comment]
Problem was fixed the following way:
- /work folder is now saved and restored
- inputs/outputs folders are now in the /work folder
- /work folder is the new jupyter lab "base" folder
- moving a file in the /work/outputs/output_1 folder now automatically upload the file(s) to simcore and are available for a next node.

**Comment by pcrespov** [comment]
Some more changes and fixes in the latest version (1.4.0 at this time). 
See [CHANGELOG](https://git.speag.com/oSparc/sparc-internal/-/blob/master/services/jupyter-octave-python-math/CHANGELOG.md)
