### ISSUE TITLE
Order of studies in dashboard

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#270]
**Describe the user role**
Typical user that will use the platform for their analysis

**Describe the goal**
When a user logs in, most likely he/she is coming back to continue working on a specific study. Right now the most recent studies are located at the bottom and there is no way to order the studies in any way.
I would like to see the most recent studies first or to be able to organize my studies in a sequence that is more productive for what I'm currently working on at the moment

**Describe the benefit**
Reduce the time from login to editing/running the selected study. Facilitate finding the study that the user wants to work on, which is most likely is the same one for multiple sessions in a row. 

**Additional context**

**Comment by odeimaiz** [comment]
After redesigning the Study Browser, the studies, as well as the templates and services in the Discover tab, are sorted by last changed, being the most recent one first in the list.

Please, reopen the case if you experience something different to that.
