### ISSUE TITLE
Save entire /home/jovyan directory in Jupyter-octave-python-math service 

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#274]
**Describe the user role**
As a z43 user I want my entire state to be saved

**Describe the goal**
Don't lose work by accidentally/intentionally not putting it in the "work" directory

**Describe the benefit**
fewer complaints

**Comment by sanderegg** [comment]
after testing saving the full home (v.1.2.3) this triggered a whole lot of other problems:
- home is pretty big already even when the lab is empty (about 180MB as compressed zip, 591MB uncompressed)
- it is then slow to compress (python make_archive with 'zip' parameter) - the empty lab takes 30 seconds to compress, then about 5secs to upload to S3
- during that time it is not possible to re-open the study, but there is no user feedback

-> therefore next step will be:
- move the lab base directory into the /home/jovyan/work directory
- move the inputs/outputs folders to work/inputs and work/outputs respectively
- create version 1.3.0

**Comment by sanderegg** [comment]
also auto save hook was de-activated (no upload to S3 when the notebook autosaves), the upload of the state will only happen when the service is closed.

**Comment by sanderegg** [comment]
this is done and active in jupyerlab-octave-python-math 1.3.0
