### ISSUE TITLE
Run button should depress when clicked.

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#283]
From feedback form (Newton)

**Describe the goal**
Run button should depress when clicked instead of just a highlight. (KZ: alternatively, some other UI element to show that a pipeline is running other than checking the very verbose logger)

Related: Hovering over buttons makes them stand out in relief (so you can see they are buttons) but clicking has no effect.  Clicking should engage full depression.

**Describe the benefit**
visual appeal

**Comment by KZzizzle** [comment]
@newton1985 I think it's depressed now =) can I close?

**Comment by newton1985** [comment]
Looks good and depressed to me.
