### ISSUE TITLE
Jupyterlab terminal doesn't close

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#284]
From Newton

**Long Story Short**
Closing active terminal session in JupyterLab (KZ: assuming octave python)

**Expected Behavior**
terminal session should be shut down after clicking ```x```

**Actual behaviour**
When I double click in the sessions UI on the terminal session I had closed previously, it opens a window that just hangs, and does not restore the previous state. 

**Steps to reproduce**
If I close an active terminal session using the "x" at the top of the window, the terminal session should probably be shut down automatically.  Even if this is not the desired behavior, when I double click in the sessions UI on the terminal session I had closed previously, it opens a window that just hangs, and does not restore the previous state. 

**Environment**
JupyterLab

**Comment by KZzizzle** [comment]
@newton1985 has this happened to you recently?

**Comment by newton1985** [comment]
@KZzizzle no, not since last year.
