### ISSUE TITLE
Make title field more visible

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#287]
@pcrespov @GitHK 

Cannot really see that the title here is actually a field ... Was confusing to find that there was a field missing
![image](https://user-images.githubusercontent.com/33152403/91587528-2cb97680-e957-11ea-93ee-b51b93bd47e7.png)

**Comment by KZzizzle** [comment]
this issue is deprecated - closing 
![image](https://user-images.githubusercontent.com/28002886/146050953-2787d8c7-099f-4996-8735-723ad5ad0adc.png)
