### ISSUE TITLE
Sync jupyter notebook and oSparc outputs

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#295]
From feedback form (@nitrosx)

**Describe the goal**
I'm working on a jupyter notebook and I'm having hard time understanding how to save a file from within the notebook and make it available as output of the block to be used in following blocks.
I saved the file under the outputs folder visible in the file browser of the jupyter interface, but it does not show up automatically in the output list panel on the right of the screen.
I thought that a file save in the outputs folder should become automatically visible as an output of the block.
If that's not out it works, we have to make sure to have detailed instructions on how to save a file from one jupyter notebook and pas it to the next one.

**Comment by sanderegg** [comment]
this is fixed and will be staged soon.

**Comment by sanderegg** [comment]
@odeimaiz we can close this one right?

**Comment by odeimaiz** [comment]
Yes 👍
