### ISSUE TITLE
Prep2Go: creating features to support complex S4L scripts

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#304]
**Describe the user role**
As an oSPARC user, I would like to write complex scripts for the Prep2Go project that involve multiple services with multiple inputs/outputs.   

**Describe the goal**
- [x] Extend API to include programmatic service (e.g. iSolve) generation to allow automatic mapping of output data (e.g. h5 files) to solvers.
- [x] Modify existing "python runner" service to allow non-interactive python code to accept **_variable_** and **_multiple_** inputs. 

**Describe the benefit**
These features are key to porting the Prep2Go pipeline onto oSPARC.  They are also fairly general and are likely to apply to future use-cases.

**Additional context**
This issue is being opened in the context of the Prep2Go project, which is a Sim4Life pipeline that optimizes the placement (and design) of electrode leads for stimulation of spinal roots, ultimately facilitating rehabilitation from spinal cord injury.  More issues in the context of this project are likely to follow.

**Comment by newton1985** [comment]
Hi Esra, would you please add this issue to the "Dev - Main Backlog" board?  Thanks!

**Comment by pcrespov** [comment]
## Update on sprint [The White Rabbit](https://github.com/ITISFoundation/osparc-issues/milestone/15)

# Done

- 2nd iteration on interface with feedback from TN, MaG, SyR, KZ
  - Refined API entries ✅
  - Python client w/ examples and doc ✅
- Deployed 
  - to master
  - to staging  (https://api.staging.osparc.io)
- Integrations
   - w/ Prep2Go: TN has scripts in place on JupyterSmash services*
   - w/ MAP-core: will run opencor solver from sparc.science
   - w/ Sim4Life scripts to run simulations from S4L web(/desktop)
   - w/ JupyterLab: some initial trials/prototypes by SyR
- Limitations
   - Runners connection incomplete* (~1w)
   - Scalability and resource management
   - Security
   
# Ongoing

  - Runners connection

**Comment by pcrespov** [comment]
## Update on sprint [The Red Panda](https://github.com/ITISFoundation/osparc-issues/milestone/16)

# Done
- Minor enhancement from previous sprint features
- Completed Runners connection
- Starting testing

   
# Ongoing
   - Complete integration, testing and deploy to production
   - Scalability and resource management
   - Security

**Comment by pcrespov** [comment]
## Update on sprint [The Red Panda](https://github.com/ITISFoundation/osparc-issues/milestone/18)

# Done
  - Created basic tutorial https://itisfoundation.github.io/osparc-simcore-python-client/#/md/tutorials/BasicTutorial
  - hides projects created by API in UI, better error handling and various fixes found while testing (ITISFoundation/osparc-simcore#2304)
   
# Ongoing  
   - Scalability and resource management
   - Security
   
![image](https://user-images.githubusercontent.com/32402063/120823078-54c5ae00-c557-11eb-9bc5-8348f97aacf1.png)
