### ISSUE TITLE
Portal hard launch, J-D35, Y3M2,5

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#31]
Establishing of a document specifying the functionality of the SPARC portal at its hard launch date hard launch of the SPARC Portal; this includes communication, and ascertained the necessary stability, testing, and monitoring functionality 
- [ ] a hard launch of the SPARC Portal has taken place for that purpose, SIM-CORE has ascertained the necessary stability, testing, and monitoring functionality

**Comment by odeimaiz** [comment]
Status before Mythos:

- Porting of existing simcore part to the new framework (Team involved, waiting for feedback from Leo)
- Content: Google Drive (Team not involved, mainly on EN, Nik, SR)
- Documentation migration (Team involved, not much work expected)
- Curation: what do we need to do? (Team involved, publish in Blackfynn repo, possibly curation needed -> could be big in the worst case)
- Review all 8 studies and make them great again (Team involved, please Team check all of them and make sure they work fine)

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Update datasets to new the Portal
- [ ] Make sure the Portal points to production in Dalco
- [ ] Puppeteer tests anonymous users in all platforms
- [ ] Optional, puppeteer compares screeenshots of the dynamic services

@ignapas @odeimaiz

**Comment by sanderegg** [comment]
State:
- continuous end2end testing of portal demos on the platforms
- ongoing debugging to stabilize the platforms
- refactoring internal reverse proxy to use [traefik](https://docs.traefik.io/)
