### ISSUE TITLE
Input/output files say "no value" even when there should be a value

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#312]
**Long Story Short**
input and output ports should show the file names of the inputs and outputs

**Expected Behavior**
input and output ports should show the file names of the inputs and outputs

**Actual behaviour**
no value

**Steps to reproduce**
* get a file (e.g. via file picker)
* connect to another service (e.g. isolve). The file input says "no value". 
* Run the pipeline. The output window says "no value" even after successful run

![image](https://user-images.githubusercontent.com/28002886/92935740-7de26380-f449-11ea-9f17-8eb2385d28f1.png)

**Environment**
tested on master and DALCO production - both have same behavior

**Comment by sanderegg** [comment]
fixed with [#1972](https://github.com/ITISFoundation/osparc-simcore/pull/1972)
