### ISSUE TITLE
Jupyter-smash crashes in XCoreModeling

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#318]
**Long Story Short**

From Sylvain Reboux

"The function ```XCoreModeling.GetEntityPointDistance``` (and probably also ```GetEntityEntityDistance```) for TriangleMesh entities, which was recently "upgraded" by Bryn does not work in JupyterSmash (and it works in S4L)"

![Image Pasted at 2020-9-23 09-46](https://user-images.githubusercontent.com/33161876/93994990-c0cd0100-fd90-11ea-8cd4-30570cb057b2.png)

Files to reproduce can by found here:

smb://biobackup.speag.com/osparc/osparc-issues/318

**Comment by KZzizzle** [comment]
@mguidon  is this still an issue?

**Comment by mguidon** [comment]
Hmm. Need to check.

**Comment by elisabettai** [comment]
Hi @mguidon, is this still an issue?

**Comment by mguidon** [comment]
This has been fixed.
