### ISSUE TITLE
Studies disappeared

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#322]
## Long story short
Since last time I logged in on the staging platform, the list of my studies has disappeared and the list of available services is minimal and do not include jupyter notebooks or lab

## Expected behaviour
Maintain studies across platform updates and deployments.

## Actual behaviour
After a platform update, the list of my studies that I worked a month ago, has disappeared.

## Steps to reproduce
I logged in with my user man8@pitt.edu. and the dashboard is empty

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "38a204b",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/38a204b/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "38a204b",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/38a204b/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 1340
    }
  }
]
```

**Comment by nitrosx** [comment]
Here how my dashboard looks like after I logged back in after 2 weeks and an update

![empty_dashboard_20200925](https://user-images.githubusercontent.com/2193724/94276219-ee8f8280-ff15-11ea-8430-e96b63961bcd.png)

**Comment by odeimaiz** [comment]
Hi @nitrosx,

While working on the access rights of the services, we messed up some of them. After the latest update, you should only see the studies containing services you have access to, and since there was a change missing in the database, just a few services were available.

The database was repopulated and your studies should be back.

Thanks a lot for your help!
