### ISSUE TITLE
S-D8 o2S2PARC Guided Mode Y4M05

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#327]
8.1. An additional usage mode will be implemented for o2S2PARC. It will allow turning pre-setup computational pipelines and workflows into simple applications that expose only the necessary parameters and interactions and allow a non-expert user to easily step through modeling steps within a given specific context-of-use.

- [x] Front-end has been implemented.
- [x] Back-end run logic is required. There might be overlaps with the Schedule case #349 

-------------------

proposed user interface:
- breadcrumbs on top, buttons: prev, next, run
- services can be in two states: 1) can be executed / interacted with (e.g., inputs are ready to run a solver, results are ready to visualize in postpro), 2) cannot (because inputs are not ready, e.g., as an upstream solver still needs to run)
- breadcrumbs are greyed out, if the corresponding service is in state 2
- users can navigate using prev/next/breadcrumbs to non-greyed out tabs and the display switches accordingly
- if a user navigates to a greyed out tab, a popup asks if he wants the run the required services. if yes, all the upstream services that are not up to date are run. if no, navigation does not happen.
- if a user changes things in a service that is upstream of some service that depends on the old input, the user is asked if he wants to delete the downstream results. if yes, the results are deleted and the states are updated accordingly. if no, the edit is rejected.
- at all points, the user can press run and all the executable services (i.e., up to services that require interaction) are updated if they are not up to date already. 
  - to be discussed: variant of run (maybe available through a down arrow next to the run button) executes only up to the point of the current view.
- to be discussed: icon next to the bread crumbs indicating that a step has computed results; 
i.e., there are three states: cannot be run (greyed out), can be run (not greyed out, empty checkbox), has been run (not greyed out, checked)

**Comment by esraneufeld** [comment]
@odeimaiz @drniiken @mguidon @KZzizzle 
i added a suggestion for the guided mode run logic and UI. could you please look at it and give me feedback?

**Comment by odeimaiz** [comment]
"if a user navigates to a greyed out tab, a popup asks if he wants the run the required services. if yes, all the upstream services that are not up to date are run."
What do we show while they are running? A list of all the upstream services that need to be run with their progress bar? What happens if one fails?

"if no, navigation does not happen."
That means you are not allowed to navigate to a greyed out (not ready) node, right?

**Comment by drniiken** [comment]
Dear @esraneufeld ... sounds fine for me, however, not everything is crystal clear yet. Maybe we quickly sit together tomorrow Friday and draw some of the things on paper and play it through.
Thanks again. All the best, Nik
