### ISSUE TITLE
S-D25 .1 Simulation Framework Functionality Y4M04

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#331]
to do in this sprint:
- [x] voxel viewer
- [x] other low-level issues

25.1. Continuous development of simulator functionality **Y4M04**
- [x] introduction of settings concept (collection of entities that have associated parameters)
- [x] drag & drop interactions in service GUI; cards and other GUI elements; functions as parameters
- [x] association of model entities with physics

**Comment by pcrespov** [comment]
NOTES from meeting:
- on s4l app

**Comment by mguidon** [comment]
# Status as of 18.12.2020
**Backend**
- Work EmFdtdSimluator/EmLfSimulator and non s4l based simulator in parallel (**ongoing**)
- Establishing an API that can be consumed from the rocket (**ongoing**)
- Generalizing concept/components for non s4l simulators (**ongoing**)

**Comment by mguidon** [comment]
## Status as of 01.03.2021
### Gridder 
- tool ported
- rendering/visualization working
- some settings/actions missing
### Voxeler
- topological voxeler tool ported
- rendering/visualization only works in c++ ( **BLOCKER**:memory leak/bug/boost::python issue?)
- Plan B: port legacy voxel viewer
- settings/actions missing
