### ISSUE TITLE
J-D4.6. A computational Minimal Information Standard (cMIS) has been established Y4M03

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#344]

**Comment by pcrespov** [comment]
NOTES during PM1:
- for the moment on EN. No dev required
- will affect metadata/v&v ...

**Comment by pcrespov** [comment]
## Status after [Shu sprint](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20201023_Shu.md)

- Met K-Core last Monday
- Created https://github.com/ITISFoundation/osparc-classifiers repo for osparc community (currently under review by Tom from K-Core)
-

**Comment by pcrespov** [comment]
## Status after [Alfred Büchi sprint](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20201218_AlfredB%C3%BCchi.md)

- A concept for classifiers based on SciCrunch RRIDs has been agreed upon with K-Core and the first prototype has been implemented
- A list of RRIDs that have already been associated to oSPARC services is available as a list in the Studies and Discover tabs
- Users are capable of assigning RRIDs to studies as well as adding new ones to the oSPARC list directly by searching the SciCrunch database at https://scicrunch.org/resources
- To be done with classifiers is to enable the assignment of ontologies as well as RRIDs as ontologies can refer to descriptors/types while RRIDs reference tools.

<img width="968" alt="Screen Shot 2020-12-21 at 09 22 13" src="https://user-images.githubusercontent.com/32402063/102754960-05574100-436e-11eb-8462-7613ddfe423c.png">
