### ISSUE TITLE
S-D9 Facilitation of Collaborative Work Y4M03

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#345]
9.1. 
- [x] More granular control of which rights are associated with which group of persons (e.g., who can view, edit, execute, derive, etc. a dataset/file/model/...) 
  - currently supported: see slides 72 and 73 in https://docs.google.com/presentation/d/18T8w__W0LEm4IktWh9wTHM1-2CGQ3Iq2o6NiE4I3mS4/edit#slide=id.g921c57ba63_12_0
  - suggested right levels:
    - study: 1) can open a study, view the setup and inspect existing results, 2) can change settings and re-execute, but not save the changes, 3) can create a copy of the study which is then completely owned (i.e., the study acts as a template), 4) can make changes to the study and save these changes in the original study, 5) is an owner of that study and can do anything, including publishing it on the Portal and assigning rights to groups and people
    - template: 1) can copy the template to instantiate a study which is then completely owned, 2) can make changes to the template and save these changes, 3) owns the template and can publish it on the Portal, assign rights to groups and people...
    - service: 1) can add the service to a study, 2) can duplicate the service and subsequently owns it, 3) can make changes to the service and push it to create a new version, 4) is an owner of that service and can do anything, including publishing it on the Portal and assigning rights to groups and people
    - script-based service: 1) can execute the script in a runner within a study, without seeing the script, 2) can see the script and modify it (e.g., in Jupyter lab), but not overwrite the original script-based service with the changes, 3) can make changes to the script and push it to create a new version, 4) is an owner of that script-based service and can do anything, including publishing it on the Portal and assigning rights to groups and people

what happens when somebody looses access, e.g., for a service that he was previously using; or when one has permission for a template that uses services to which one does not have access ? warning when opening that not all services are accessible?

**Comment by pcrespov** [comment]
NOTES during PM1
 - @sanderegg knows about it
