### ISSUE TITLE
S-D22.3 Meta-Modeling uncertainty assessment  Y4M10

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#354]
22.3.  An uncertainty assessment module exists that permits to propagate parameter uncertainty through a modeling pipeline and to determine the resulting uncertainty of modeled quantities of interest.  **Y4M10**
- [ ] support for efficient linearized uncertainty propagation of uncorrelated factors based on S-D2
- [ ] support for Monte-Carlo-based analysis of correlated, non-linear factors 

Definition of Done & User story:
- An uncertainty analysis service exists. It is possible to select whether a linearized or a monte-carlo based uncertainty analysis is performed (alternatively, have two variants of that service). For monte-carlo, some additional parameters exist (e.g., number of iterations, initial equilibration runs)
- In the uncertainty analysis service, a number of variables can be defined and named (see [S-D22.1](https://github.com/ITISFoundation/osparc-issues/issues/328)), along with their typical value and the associated probability distribution (normal/uniform with stddev/range, linear/log scale)
- As a result corresponding output ports (or attached parameter nodes) are created that can be connected to input ports of a pipeline
- Output ports of that pipeline that have the type scalar can be connected back to the sensitivity analysis service
- When running the uncertainty analysis service, one reference pipeline execution and 2*n variations are run for the linearized variant and nriterations variations for the monte-carlo one (see the [jupyterlab prototype](https://osparc.io/#/study/f4eb1b8a-be0a-11eb-84f2-02420a0b0154) for detail)
- The uncertainty analysis displays and provides as an output (at a port):
  - The uncertainty contributions
  - The combined uncertainty
  - For linearized UQ: The sensitivities (in [-] and [dB] for linear perturbations, and as [1/dB] or [dB/dB] for relative ones) along with the R^2 value of the 3-point fit.

(see the [jupyterlab prototype](https://osparc.io/#/study/f4eb1b8a-be0a-11eb-84f2-02420a0b0154) for detail on both the linear and the MC uncertainty analysis)
A corresponding jupyterlab can be found [here](https://osparc.io/#/study/f4eb1b8a-be0a-11eb-84f2-02420a0b0154).
 
Note: In the above user story, the uncertainty analysis service acts as both an iterator and a collector object. See 22.2 for alternatives.

**Comment by esraneufeld** [comment]
todo:
- use technology developed for sensitivity analysis to also implement two uncertainty analysis iterators and corresponding analysis scripts (based on EN implementation)
