### ISSUE TITLE
UI in Main Study Window

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#368]
## Long story short
I have a few requests for features in the main study window that would make manipulating blocks and interacting with studies much easier. They're mostly "mechanical". 

## Requested behaviour
I propose the following features:

1. Left-clicking and dragging creates a rectangle than can highlight multiple blocks at once, which can then be translated across the screen as a group.

2. Clicking and holding the middle mouse button (or something like that) allows the user to pan across the screen. Alternatively, there could be scroll bars at the top and bottom. This is all in case you're zoomed in looking at a few blocks, and would like move around.

3. A zoom feature that zooms only in the study window, and doesn't just increase the size of everything on the page.

4. Labels for each block, so that if you relabel (say, from "Sleeper 2" to "Conductivity Tensors") you still know the service is of type "Sleeper". 

Please let me know if you need any clarification, or if I can be of help in any way getting these features implemented.

Cheers,
Taylor

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "a9cf515",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/a9cf515/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "a9cf515",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/a9cf515/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2327,
      "height": 1179
    }
  }
]
```

**Comment by odeimaiz** [comment]
@newton1985 I believe that all your requests were implemented. Feel free to close it :)

**Comment by newton1985** [comment]
@odeimaiz yes, everything is there!!! looks great 👍 . Also love the inertia in the connection arrows ;). The only thing is that the pan (middle button) does something weird, where the screen (see video):

https://user-images.githubusercontent.com/70750341/149092411-f0c7a461-f58b-4cd7-a06d-950c4592adc7.mp4

**Comment by odeimaiz** [comment]
> The only thing is that the pan (middle button) does something weird, where the screen wobbles a lot (see video)

We'll see what we can do there.

Closing this one, thanks!
