### ISSUE TITLE
Add input to submission form for time estimation on run completion

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#369]
**Describe the user role**
as an osparc user, I'd like to know how long it takes a service to finish running. 

**Describe the goal**
Ask submitters to include something in their code to notify the frontend the % completion of a process

**Describe the benefit**
So that users have some idea how long a service is going to run for

**Additional context**

**Comment by KZzizzle** [comment]
From Team Black Meeting 30.11.2020

Ewa: Perhaps there should be a visual indicator on the node itself when it is running (in addition to the run button which is continuously scrolling). This can be done even if the user does not submit "progress" messages with their code.

**Comment by KZzizzle** [comment]
Per Team Black meeting 22.12.2020: Add page to documentation website about code's progress during submission

**Comment by KZzizzle** [comment]
Documentation can be found here: http://docs.osparc.io/#/docs/submission

**Comment by nitrosx** [comment]
I think that asking the user for an estimation of how long their node will run is not feasible as we do not know before hand where the container will run.

Video on submission form explains really well how to provide progress report.

**_A nice-to-have would be to have a section at the end of the page that explains how to provide progress, without the need to watch the video._**
@KZzizzle : should we close this ticket and open a new one or should we keep this one open?

**Comment by KZzizzle** [comment]
Documentation here: http://docs.osparc.io/#/docs/submission?id=showing-progress
