### ISSUE TITLE
Minimap within Guided Mode to highlight the node in which you currently are

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#370]
**Describe the user role**
As a new user who would like to be proficient at osparc, I would like to see a small map of the full pipeline (perhaps just a miniature screenshot) where the node I'm currently editing is highlighted.

**Describe the goal**
To see where in the pipeline I am even when I'm within the Guided Mode.

**Describe the benefit**
To help me navigate through the pipeline and also to make sure I have the correct node in case there are multiple of the same service.

- [ ] Create Mockup
- [ ] Approval by Team Black
- [ ] Development
- [ ] Review
- [ ] Deployment

**Comment by odeimaiz** [comment]
Dropped, thanks Katie :)
