### ISSUE TITLE
Run next node by default when in Guided Mode

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#371]
**Describe the user role**
As an osparc user, I would like to make sure that the steps in between two "slides" get run by default.

**Describe the goal**
When clicking the "next" button in guided mode, I would like for the current node to run and also all the steps in between until the "next" node. This should be on by default but there is a possibility to disable.  Additionally, if the "next" node depends on input from a node that has not yet appeared in the Guided Mode "slide order" but is later on in the slide order, that node should not yet run UNTIL that node has been visited.

**Describe the benefit**
Ease of use of Guided Mode and making sure the pipeline is run after all parameters are set.

**Additional context**
Additional details can be found with Calvin Eiber

**Comment by KZzizzle** [comment]
From Team Black Meeting 30.11.2020

Max: As a first step, give some feedback to the user such that they have the option to choose which nodes will run. 

Ewa: use hierarchical composition

**Comment by deelman** [comment]
An example of a hierarchical workflow composition can be found in this publication https://doi.org/10.1016/j.future.2008.06.014

**Comment by KZzizzle** [comment]
TB feedback from 02.03.2021 meeting:
Out-of-date nodes in Guided mode should have an orange exclamation icon with a tooltip to indicate that the node's outputs are out of date
Increase contrast between exclamation point and the background in error state (possibly using only text OR triangle icon as the universal caution symbol)

**Comment by KZzizzle** [comment]
Comment during NIH review 03.03.2021:

Gray shading for ready/not ready nodes in Guided mode is not distinct enough
