### ISSUE TITLE
Invitation Links Don't Work

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#377]
**Long Story Short**
An invitation link (at least to osparc AWS production) results in error message "this link has already been used or has expired" when they fill in their email and create password and click "Submit". This happens even though the invitation still exists in the database and has not expired.

**Expected Behavior**
User is able to create an account with the invitation link

**Additional context**
apparently the webserver cannot send emails at the moment so there is no way it could send the confirmation link to the new user. Not sure if this is the only problem

**Comment by pcrespov** [comment]
@KZzizzle  email is reestablished in AWS and invitation system is back in place. I have generated extra invitations
