### ISSUE TITLE
Plot Responsiveness in Jupyter smash

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#380]
**Long Story Short**
I was testing Jupyter Smach node with Jupyter notebook provided for the Team Black meeting of 2020/11/30 and illustrated at https://itisfoundation.github.io/osparc-manual-z43/#/Tutorials/Sim4LifeParallelPlate. 
I tried to interact with the plots using the zoom and pan functionailities.
Unfortunately, the plot lacks responsiveness, to the point it might not be to usefull

**Steps to reproduce**
Please follow instructions provided at https://itisfoundation.github.io/osparc-manual-z43/#/Tutorials/Sim4LifeParallelPlate

**Environment**
Version 86.0.4240.75 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)

**Comment by mguidon** [comment]
OBE
