### ISSUE TITLE
Misleading path in visualization

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#381]
**Long Story Short**
I was testing Jupyter Smach node with Jupyter notebook provided for the Team Black meeting of 2020/11/30 and illustrated at https://itisfoundation.github.io/osparc-manual-z43/#/Tutorials/Sim4LifeParallelPlate.
At the bottom of the visualization block, a file path is shown that point to a file located in the home folder of a user.
I think that for a normal user this might be misleading and confusing.

**Expected Behavior**
Remove it or show a path to local folders accessible through Jupyter

**Actual behaviour**
A full path to an unknown user is shown

**Steps to reproduce**
Run the sample jupyter notebook and check one of the visualizations cells

**Environment**
Version 86.0.4240.75 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)

**Comment by KZzizzle** [comment]
![image](https://user-images.githubusercontent.com/28002886/100635570-f5c97700-3330-11eb-9049-8d7800db3731.png)

**Comment by elisabettai** [comment]
Hi @mguidon, do you think this is fixed.

**Comment by mguidon** [comment]
This cannot be "fixed". All juypterlabs use the user `jovyan` and the default working directory is now `/home/jovyan/work/workspace`. So I would close this as "Not doing"
