### ISSUE TITLE
Jupyter Octave+Math stuck

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#383]
**Long Story Short**
As a user, I was trying to save a json file under outputs/output_1 from a cell in my notebook.
The notebook became unresponsive and a warning appeared with the message "Directory not found: "outputs/output_1"
As I dismissed the error, it kept reappearing. The rest of the interface of jupyter lab interface is grayed out.
If you click enough times, the warning will disappear for few seconds, and the user can interact with jupyter.
The kernel linked with the notebook crashed.

**Expected Behavior**
I would expect that the warning would be shown only once and the user would be able to save the notebook and maybe "reboot" the node, so he/she can start fresh.

**Actual behaviour**
The warning keeps popping up, the jupyter lab interface is unresponsive and there is no way to restart the node in osparc.

**Steps to reproduce**
- open study named PC Vis v2.2.alpha.1
- open node named PC_Vis_Extract_Metadata
- in Jupyter lab, open the notebook named PC_Vis_Extract_Metadata_new
- run all the cells. the cell that triggered the behaviour is the last one

**Environment**
Chromium 
Version 86.0.4240.75 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)

**Additional context**
None

**Comment by KZzizzle** [comment]
This is a known bug and we are working to resolve it. In addition, there may be some changes in the near future regarding the input and output ports of the jupyterlab Octave Python service. Once we have the fixes/changes deployed we will let you know so that you can retry the study.

**Comment by sanderegg** [comment]
@GitHK you did the latest changes with the watchdog, etc... maybe you have an idea of what might be going on there?

**Comment by KZzizzle** [comment]
@GitHK  poking again

**Comment by pcrespov** [comment]
@nitrosx, @KZzizzle, @GitHK  please try latest released jupyterlab math 1.4.4

**Comment by GitHK** [comment]
Pardon me for the late reply.
@nitrosx I have checked the version you are using for both your notebooks. It is currently `1.4.0`, the issue you have reported has been addressed and fixed in version `1.4.4` and I strongly advise upgrading to that version of the service.

**Comment by odeimaiz** [comment]
duplicated https://github.com/ITISFoundation/osparc-issues/issues/375

**Comment by KZzizzle** [comment]
closed because of duplication
