### ISSUE TITLE
Logger says pipeline submission failed but it actually succeeds

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#384]
![image](https://user-images.githubusercontent.com/28002886/101636555-cc44d580-3a2b-11eb-82e3-59899411b160.png)

In the logger, I get an entry that the pipeline fails but it then continues and and the full pipeline succeeds on AWS production. Bravo for the fix on running pipelines after deleting nodes!

**Comment by sanderegg** [comment]
@KZzizzle I think this was fixed. close?

**Comment by KZzizzle** [comment]
@sanderegg agreed
