### ISSUE TITLE
Canvas autoscaling

### ISSUE THREAD

**Issue by deelman** [ITISFoundation/osparc-issues#386]
**Long Story Short**

the workflow composition canvas does not autoscale, so some menu buttons disappear
**Expected Behavior**

I expect the still see the menu when I reduce the size of the browser
**Actual behaviour**

**Steps to reproduce**

make your browser window smaller
**Environment**

chrome
**Additional context**

**Comment by KZzizzle** [comment]
Feedback from TB meeting 02.03.2021: Run button disappears when screen is too small
