### ISSUE TITLE
Zoom buttons

### ISSUE THREAD

**Issue by deelman** [ITISFoundation/osparc-issues#387]
**Describe the user role**

Team black
**Describe the goal**

add descriptions to the zoom buttons when user hovers over them
**Describe the benefit**

clarify the role the of buttons, +/- are clear, but the others are not, I am not sure what the 3rd button does, does not seem to do anythign
**Additional context**

**Comment by HaiboNi** [comment]
I also found the buttons confusing, especially the button with 4 arrows (looks like full screen). When tested with a minimal example (2 to 5 nodes in the flowchart), pressing the 4-arrow button did not produce any change, even after several zoom-in and out clicks to change the workbench view.
