### ISSUE TITLE
Provide sample workflows/studies

### ISSUE THREAD

**Issue by deelman** [ITISFoundation/osparc-issues#390]
**Describe the user role**

As a team black member, I would like to see an easy way for new users to get started.
**Describe the goal**

I think it is a bit difficult to start new studies, there are various service options and it would be good for new users to have some examples they can learn from and potentially modify.

**Describe the benefit**

Faster learning curve.
**Additional context**

**Comment by KZzizzle** [comment]
Per Team Black Meeting on 22.12.2020, This issue is fulfilled by the Template Studies in the "Discover Tab"
