### ISSUE TITLE
HW/SW Dev Support Case: New features on the material Database for Solid Materials

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#399]
**Describe the user role**

Curation and online publication of EM material measurements

**Describe the goal**

Enhancements  to feature implemented is  #266

- Backend: 
    - Adapt to new format with 4 columns
    - Work with Sina to add more metadata (e.g. units, temp, range, etc)
    - Temperature can be nullable
- Front-end :   
    - add tolerances as error bar (value +/- tol)  in given samples and in the table
    - If T nullable -> hide
    - X-axis defaults in MHz. (Use a default x-unit)
    - Table adds eps2, and tolerances for eps1 and sigma 

**Describe the benefit**

**Additional context**

The front-end looks like this https://speag.swiss/services/material-properties

![Screen Shot 2021-02-02 at 10 09 48](https://user-images.githubusercontent.com/32402063/106579885-83982d00-6541-11eb-9af4-5677f7e558de.png)

Written by @pcrespov on behalf of @Sinahashemizadeh

**Comment by Sinahashemizadeh** [comment]
For majority of the materials, the measurement frequency range is 4 MHz-67 GHz. However, for some cases, we need to handle data sets over smaller ranges.

**Comment by pcrespov** [comment]
NOTES during PM1
- @drniiken aggress on a first iteration on it. NK's high prio.

**Comment by pcrespov** [comment]
## Update on sprint [The White Rabbit](https://github.com/ITISFoundation/osparc-issues/milestone/15)

# Done

- First iteration on the UI
- Upgraded material data curation workflow to include backwards compatibility
![image](https://user-images.githubusercontent.com/32402063/109472231-2759f780-7a72-11eb-96e1-47107b95270c.png)

# Ongoing

- Fixing testing
