### ISSUE TITLE
duplicate study

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-issues#402]
As a user I'd like to be able to duplicate a study. With right click and duplicate

**Comment by GitHK** [comment]
@odeimaiz  I will ask for a hand with the fronted on this one.

**Comment by odeimaiz** [comment]
I would go for an option for "Clone"ing in the study card menu, or move all those actions to a context menu

**Comment by GitHK** [comment]
Expect a new API endpoint to duplicate the project like: `/projects/{project_id}:duplicate`
