### ISSUE TITLE
put mesher into jupyterlab & s4l python

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#404]

**Comment by esraneufeld** [comment]
As a user/antonino, i would like to be able to use meshing from the s4lpython in the jupyter smash module.

**Comment by mguidon** [comment]
## Status as of 01.03.2021
- mesh modeling ported to linux
- unstructured LF simulators ported to linux
- python API available from ```jupyter-smash v 2.4.0```
