### ISSUE TITLE
Interactive Viewer Issues

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#416]
## Long story short
Dear oSPARC Support- I recently discovered several issues with the interactive viewers. Apologies for lumping them together. 

1) When attempting to rotate an image, mouse right-click release events aren't captured, so that every time I hover my mouse over the image, it rotates the objects (even without clicking). This happens consistently on my windows machine, and never on my macbook laptop, for both chrome and firefox.

2) On my windows machine, the mouse scroll button zoom feature is not captured (i.e. zooming in and out is not possible). However, as in issue #1, it works on my macbook laptop. 

3) Object transparency does not work as expected. Setting the transparency on the first run after starting the kernel (e.g. entity.Transparency = 0.5) works, but attempts to change this value after the first time the cell is executed have no effect. 

## Expected behaviour
1) Objects in a scene are only rotated when the mouse right-button is depressed.

2) Scroll button causes the image to zoom in and out.

3) entity.Transparency = XXX causes the transparency to be reset to a new value, regardless of how many times the cell containing this code has been executed.

## Actual behaviour
1) Scene is rotated without depressing any mouse buttons as the cursor moves over a scene (on windows).

2) Mouse wheel has no effect on zoom (on windows).

3) entity.Transparency = XXX does not cause the transparency to change if the cell containing this code has been executed already after starting the kernel (on mac and windows).

## Steps to reproduce
Open a new Jupyter Smash service and attempt to view a scene, rotate, zoom in and out, and reset the transparency. Both a macbook and windows machine will be required to observe all the issues listed above.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "f49adef",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/f49adef/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "f49adef",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/f49adef/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 1874,
      "height": 844
    }
  }
]
```

**Comment by KZzizzle** [comment]
@newton1985 are you still experiencing these issues in the most recent jupyter smash's?

**Comment by newton1985** [comment]
@KZzizzle Yes- as of jupyter-smash version 2.5.6, issue #1 persists. It would be great to get this one solved, since it makes it quite difficult to visualize smash files.

**Comment by KZzizzle** [comment]
closing - this issue is being tracked at #548
