### ISSUE TITLE
Allow for dynamic number of input ports in dynamic services

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#419]
## Long story short
Complex projects may have jupyter-lab services that consume by far more than 10 input sources. At the moment, this is limited to 4.

## Expected behaviour
Allow the user to dynamically up/downscale the number of ports.

```[tasklist]
### Goal for Pastel de Nata
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4210
- [x] New version of dy-services with 20 inputs (initially smash and jupyterlab-math) @elisabettai
- [x] Update service metadata to indicate which ports are visible or not @GitHK https://github.com/ITISFoundation/osparc-simcore/pull/4243
```

**Comment by elisabettai** [comment]
I would also really appreciate this feature, I just had a use-case with a jupyterlab (tf) service where I needed 7 outputs, ideally saved to 6 output ports. 
@GitHK or @pcrespov, it is very difficult to implement?

I would think that a user can create additional `output_5`, `output_6`, etc... ports in the usual place and then these are "converted" into output ports.

Another nice feature would be the ability for the user to label those output ports (so it's easier to remember how to connect outputs to downstream services).

**Comment by odeimaiz** [comment]
Go with a larger number of inputs/outputs and only show the first 2-3. let the user show more.

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...
