### ISSUE TITLE
maintenance/scaling of the platform

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#428]
the scrum master wrote:
_We are having quite a hard time maintaining the platformS, so that they pass our E2E tests [...]_ 

in this sprint:
- [x] _[...] I would say we could say having a stable E2E with 20 users for this sprint. [...]_

in the following ones:
- [ ] _[...] then it should be recurring because we always have things to be done in maintenance. [...]_

**Comment by sanderegg** [comment]
## Update on sprint [Red Panda](https://github.com/ITISFoundation/osparc-issues/milestone/16)

### E2E
- added Jupyters e2e test running in parallel to simulate 20 users on master deploy, 10 users on staging AWS and production AWS deploys
- A number of issues were detected and fixed to improve the success rate of the e2e/p2p testing (see [platform stability #1426](https://github.com/ITISFoundation/osparc-simcore/issues/1426) case)

### Maintenance
- 3 data loss problems were detected:
  1. Jupyter lab state data was lost due to (un)archiving issue. Issue was fixed through  [#2192](https://github.com/ITISFoundation/osparc-simcore/pull/2192). Also DevOps change to ensure automated backups of S3 storage is done and also versioning which should prevent loosing data. Currently tested in on-premise master deploy, and will be moved to staging/production (on-premise and AWS) next sprint.
  2. A user opened a shared study and could not see the sharer user data in a Jupyter lab. After closing the study the empty data overwrote the original data, thus loosing the original Jupyter lab data. Issue was fixed through [#2041](https://github.com/ITISFoundation/osparc-simcore/issues/2041).
  3. User A with a shared study opened got disconnected from the platform for a long time. User B worked on the shared study and closed it properly. User A eventually re-connected, this overwrote the data of user B. Issue was fixed through [#2225](https://github.com/ITISFoundation/osparc-simcore/pull/2225)
- All maintenance cases are listed in [platform stability #1426](https://github.com/ITISFoundation/osparc-simcore/issues/1426). in the future will be connected to this issue.

**Comment by sanderegg** [comment]
## Update on sprint [Schwarznasenschaff](https://github.com/ITISFoundation/osparc-issues/milestone/17)

### E2E
- added Jupyters e2e test running in parallel to simulate 20 users on master deploy, 10 users on staging AWS and production AWS deploys
- A number of issues were detected and fixed to improve the success rate of the e2e/p2p testing (see [platform stability #1426](https://github.com/ITISFoundation/osparc-simcore/issues/1426) case)

### Maintenance
- 3 data loss problems were detected:
  1. Jupyter lab state data was lost due to (un)archiving issue. Issue was fixed through  [#2192](https://github.com/ITISFoundation/osparc-simcore/pull/2192). Also DevOps change to ensure automated backups of S3 storage is done and also versioning which should prevent loosing data. Currently tested in on-premise master deploy, and will be moved to staging/production (on-premise and AWS) next sprint.
  2. A user opened a shared study and could not see the sharer user data in a Jupyter lab. After closing the study the empty data overwrote the original data, thus loosing the original Jupyter lab data. Issue was fixed through [#2041](https://github.com/ITISFoundation/osparc-simcore/issues/2041).
  3. User A with a shared study opened got disconnected from the platform for a long time. User B worked on the shared study and closed it properly. User A eventually re-connected, this overwrote the data of user B. Issue was fixed through [#2225](https://github.com/ITISFoundation/osparc-simcore/pull/2225)
- All maintenance cases are listed in [platform stability #1426](https://github.com/ITISFoundation/osparc-simcore/issues/1426). in the future will be connected to this issue.

**NOTE:** these fixes are currently all deployed in master/staging/staging_AWS. They will be deployed to production ASAP.

**Comment by sanderegg** [comment]
## Update on sprint [Chinchilla](https://github.com/ITISFoundation/osparc-issues/milestone/19)

### Improvements
- Added static-webserver backend service, improves static website responsivity [#2342](https://github.com/ITISFoundation/osparc-simcore/issues/2342)

### Bugfixes
- Revision of fastapi-based backend services startup [#2356](https://github.com/ITISFoundation/osparc-simcore/issues/2356)
- Fix slow blocking calls at startup [#2346](https://github.com/ITISFoundation/osparc-simcore/issues/2346)
- Passing variable to computation services non global [#2330](https://github.com/ITISFoundation/osparc-simcore/issues/2330), [#2316](https://github.com/ITISFoundation/osparc-simcore/issues/2316)
- Faster access to S3 storage [#2329](https://github.com/ITISFoundation/osparc-simcore/issues/2329)
- Webserver background task auto-restarts when database connection is invalidated [#2246](https://github.com/ITISFoundation/osparc-simcore/issues/2246)

### Testing facilities
- improvements of performance testing scripts [#2347](https://github.com/ITISFoundation/osparc-simcore/issues/2356)), [#2339](https://github.com/ITISFoundation/osparc-simcore/issues/2339), [#2338](https://github.com/ITISFoundation/osparc-simcore/issues/2338), [#2337](https://github.com/ITISFoundation/osparc-simcore/issues/2337), [#2335](https://github.com/ITISFoundation/osparc-simcore/issues/2335)


### E2E

### Maintenance
- Error improvements, cleanup: [#2355](https://github.com/ITISFoundation/osparc-simcore/issues/2355), [#2304](https://github.com/ITISFoundation/osparc-simcore/issues/2304)
- Simplify Github CI scripts: [#2353](https://github.com/ITISFoundation/osparc-simcore/issues/2353)
- Improved logging of blocking calls in webserver: [2341](https://github.com/ITISFoundation/osparc-simcore/issues/2341)
- Libraries upgrades [#2343](https://github.com/ITISFoundation/osparc-simcore/issues/2343), [#2345](https://github.com/ITISFoundation/osparc-simcore/issues/2345), [#2340](https://github.com/ITISFoundation/osparc-simcore/issues/2340), [#2319](https://github.com/ITISFoundation/osparc-simcore/issues/2319), [2327](https://github.com/ITISFoundation/osparc-simcore/issues/2327), [#2326](https://github.com/ITISFoundation/osparc-simcore/issues/2326)
- improve maintenance scripts [#2328](https://github.com/ITISFoundation/osparc-simcore/issues/2328)

**Comment by sanderegg** [comment]
## Update on sprint [Marmoset](https://github.com/ITISFoundation/osparc-issues/milestone/20)

### Improvements
- New settings-library [#2395](https://github.com/ITISFoundation/osparc-simcore/issues/2395)
- 
### Bugfixes
- Fixes session cookies with latest aiohttp library [#2386](https://github.com/ITISFoundation/osparc-simcore/issues/2386)
- Cannot link files from File Picker to some cardiac models [#442]
- User with full access to study renders as viewer [#2272] 
- Project locked issue [#2381](https://github.com/ITISFoundation/osparc-simcore/issues/2384), [#431]
- fix blocking call to celery backend [#2372](https://github.com/ITISFoundation/osparc-simcore/issues/2372)
- fix blocking calls in webserver [#2397](https://github.com/ITISFoundation/osparc-simcore/issues/2397)
### Changed
- **Upgrade to python 3.8.10 in all osparc-simcore services** [#2079](https://github.com/ITISFoundation/osparc-simcore/issues/2079)
- Updates on settings in storage [#2369](https://github.com/ITISFoundation/osparc-simcore/issues/2369)
- Libraries updates [#2394](https://github.com/ITISFoundation/osparc-simcore/issues/2394), [#2367](https://github.com/ITISFoundation/osparc-simcore/issues/2367)
- Cap unarchiving workers to 2 [#2384](https://github.com/ITISFoundation/osparc-simcore/issues/2384)
- Improved error handling in frontend [#2283](https://github.com/ITISFoundation/osparc-simcore/issues/2283)
### Testing facilities
- Upgrades of e2e libraries [#2352](https://github.com/ITISFoundation/osparc-simcore/issues/2352)
- Upgrades of tests linked to python 3.8 [#2387](https://github.com/ITISFoundation/osparc-simcore/issues/2387)

### E2E

**Comment by sanderegg** [comment]
## Update on sprint [Wombat](https://github.com/ITISFoundation/osparc-issues/milestone/21)

### Improvements


### Bug fixes
- Fixes running computational task not aborted [#2449](https://github.com/ITISFoundation/osparc-simcore/issues/2449)
- Fixes dynamic-sidecar settings in director-v2 [#2431](https://github.com/ITISFoundation/osparc-simcore/issues/2431)
- Fixes API upload timeout too short [#2433](https://github.com/ITISFoundation/osparc-simcore/issues/2433)
- Fixes timeout for synchronisation of storage metadata [#2420](https://github.com/ITISFoundation/osparc-simcore/issues/2420)

### Changed
- **Webserver responsiveness issues**: disabling unused metrics with high cardinality [#2452](https://github.com/ITISFoundation/osparc-simcore/issues/2452)
- Improve log messages [#2430](https://github.com/ITISFoundation/osparc-simcore/issues/2430)
- Director-v2 uses settings-library [#2427](https://github.com/ITISFoundation/osparc-simcore/issues/2427)

### Testing facilities
- Improvements of Github-CI workflow [#2430](https://github.com/ITISFoundation/osparc-simcore/issues/2430), [#2450](https://github.com/ITISFoundation/osparc-simcore/issues/2450), [#2457](https://github.com/ITISFoundation/osparc-simcore/issues/2457), [#2460](https://github.com/ITISFoundation/osparc-simcore/issues/2460), [#2462](https://github.com/ITISFoundation/osparc-simcore/issues/2462)


### Open issue / ongoing
- webserver responsiveness issue (503s) under observation
- test to check metrics endpoints [#2417](https://github.com/ITISFoundation/osparc-simcore/issues/2417)
- improving CI workflow speed [#2466](https://github.com/ITISFoundation/osparc-simcore/issues/2466)
- storage service refactoring [#2396](https://github.com/ITISFoundation/osparc-simcore/issues/2396)
- webserver service refactoring [#2008](https://github.com/ITISFoundation/osparc-simcore/issues/2008)

**Comment by sanderegg** [comment]
## Update on sprint [Chevrotain](https://github.com/ITISFoundation/osparc-issues/milestone/22)

### Improvements


### Bug fixes

### Changed
- Refactor of service library (separation of concerns) [#2516](https://github.com/ITISFoundation/osparc-simcore/issues/2516)
- Upgrade of library, services dependencies [#2485](https://github.com/ITISFoundation/osparc-simcore/issues/2485), [#2524](https://github.com/ITISFoundation/osparc-simcore/issues/2524)
### Testing facilities
- Added data consistency scripts [#2531](https://github.com/ITISFoundation/osparc-simcore/issues/2531), [#2533](https://github.com/ITISFoundation/osparc-simcore/issues/2533), [#2535](https://github.com/ITISFoundation/osparc-simcore/issues/2535)
- Improve Github CI workflow [#2510](https://github.com/ITISFoundation/osparc-simcore/issues/2510)
- Upgrade testing and tooling dependencies [#2475](https://github.com/ITISFoundation/osparc-simcore/issues/2475)
### 3rd party services
- Fix dependencies in Mattward viewer [#137](https://github.com/ITISFoundation/osparc-services/issues/137)

### Open issue / ongoing
- webserver responsiveness issue (503s) under observation
- test to check metrics endpoints [#2417](https://github.com/ITISFoundation/osparc-simcore/issues/2417)
- improving CI workflow speed [#2466](https://github.com/ITISFoundation/osparc-simcore/issues/2466)
- storage service refactoring [#2396](https://github.com/ITISFoundation/osparc-simcore/issues/2396)
- webserver service refactoring [#2008](https://github.com/ITISFoundation/osparc-simcore/issues/2008)

**Comment by sanderegg** [comment]
## Update on sprint [Anti-PER](https://github.com/ITISFoundation/osparc-issues/milestone/24)


### Bug fixes
### Changed
- Adding tracing in aiohttp-based services [#2559](https://github.com/ITISFoundation/osparc-simcore/issues/2559)
- Adding more logs from pending services [#2566](https://github.com/ITISFoundation/osparc-simcore/issues/2566)

### Open issue / ongoing
- Adding tracing in fastapi-based services [#2558](https://github.com/ITISFoundation/osparc-simcore/issues/2558)
- Refactoring webserver settings [#2376](https://github.com/ITISFoundation/osparc-simcore/issues/2376)
- webserver responsiveness issue (503s) under observation
- improving CI workflow speed [#2466](https://github.com/ITISFoundation/osparc-simcore/issues/2466), [#2525](https://github.com/ITISFoundation/osparc-simcore/issues/2525)
- storage service refactoring [#2396](https://github.com/ITISFoundation/osparc-simcore/issues/2396)
- webserver service refactoring [#2008](https://github.com/ITISFoundation/osparc-simcore/issues/2008)
- service-integration backlog [2409](https://github.com/ITISFoundation/osparc-simcore/issues/2409)

**Comment by sanderegg** [comment]
## Update on sprint [Meerkat](https://github.com/ITISFoundation/osparc-issues/milestone/25)

### New
- Script for listing repo contents  [#2639](https://github.com/ITISFoundation/osparc-simcore/issues/2639)
- New Handling of staging hotfixes [#2649](https://github.com/ITISFoundation/osparc-simcore/issues/2649)
- Add config for github automatic changelog generation upon release [#2662](https://github.com/ITISFoundation/osparc-simcore/issues/2662)

### Bug fixes
- Properly handle timeouts when copying a project [#2655](https://github.com/ITISFoundation/osparc-simcore/issues/2655)
- Fixes makefile recipe for hotfix-releases [#2650](https://github.com/ITISFoundation/osparc-simcore/issues/2650)
### Deployment
- Fix Storage lazy update of files [#2636](https://github.com/ITISFoundation/osparc-simcore/issues/2636)


### Changed
- Adding tracing in fastapi-based services [#2558](https://github.com/ITISFoundation/osparc-simcore/issues/2558)
- New interfaces for webserver.director_v2 plugin [#2647](https://github.com/ITISFoundation/osparc-simcore/issues/2647)
- Library maintenance  [#2660](https://github.com/ITISFoundation/osparc-simcore/issues/2660),  [#2663](https://github.com/ITISFoundation/osparc-simcore/issues/2663), [#2679](https://github.com/ITISFoundation/osparc-simcore/issues/2679), [#2669](https://github.com/ITISFoundation/osparc-simcore/issues/2669), [#2676](https://github.com/ITISFoundation/osparc-simcore/issues/2676), [#2664](https://github.com/ITISFoundation/osparc-simcore/issues/2664)
- Remove overload of pytest loop fixture: [#2674](https://github.com/ITISFoundation/osparc-simcore/issues/2674)
- Github issue template reworked: [#2673](https://github.com/ITISFoundation/osparc-simcore/issues/2673)

### Open issue / ongoing

- Refactoring webserver settings [#2376](https://github.com/ITISFoundation/osparc-simcore/issues/2376)
- webserver responsiveness issue (503s) under observation
- improving CI workflow speed [#2466](https://github.com/ITISFoundation/osparc-simcore/issues/2466), [#2525](https://github.com/ITISFoundation/osparc-simcore/issues/2525)
- storage service refactoring [#2396](https://github.com/ITISFoundation/osparc-simcore/issues/2396)
- webserver service refactoring [#2008](https://github.com/ITISFoundation/osparc-simcore/issues/2008)
- service-integration backlog [2409](https://github.com/ITISFoundation/osparc-simcore/issues/2409)

**Comment by sanderegg** [comment]
## Update on sprint [Rudolph](https://github.com/ITISFoundation/osparc-issues/milestone/26)

### New

### Bug fixes
- Fixes metrics high cardinality in webserer, storage and director-v0 services #2726

### Changed
- Refactoring webserver settings [#2750](https://github.com/ITISFoundation/osparc-simcore/issues/2750), #2739, #2736
- webserver responsiveness issue (503s) under observation
- Libraries upgrades #2752, #2748, #2733, #2741, #2730, #2727
- Improved reverse proxy rules to only take care of the minimal necessary instead of defaulting to webserver #2737, #2734, #2732, #2710

### Open issue / ongoing
- garbage collector in webserver uses too much resources and temporarily blocks handling of healtchecks
- uvcorn auto-reload fails
- webserver connection issue with rabbitMQ when restarting


- improving CI workflow speed [#2466](https://github.com/ITISFoundation/osparc-simcore/issues/2466), [#2525](https://github.com/ITISFoundation/osparc-simcore/issues/2525)
- storage service refactoring [#2396](https://github.com/ITISFoundation/osparc-simcore/issues/2396)
- webserver service refactoring [#2008](https://github.com/ITISFoundation/osparc-simcore/issues/2008)
- service-integration backlog [2409](https://github.com/ITISFoundation/osparc-simcore/issues/2409)

**Comment by mguidon** [comment]
@sanderegg @pcrespov These bullet lists are priceless for the quarterly reports! Thanks a lot for updating them.

**Comment by sanderegg** [comment]
## Update on sprint [Schumann](https://github.com/ITISFoundation/osparc-issues/milestone/27)

### New

### Bug fixes
- ITISFoundation/osparc-simcore#2813
- ITISFoundation/osparc-simcore#2812
- ITISFoundation/osparc-simcore#2797
- ITISFoundation/osparc-simcore#2804
- ITISFoundation/osparc-simcore#2795
- ITISFoundation/osparc-simcore#2780
- ITISFoundation/osparc-simcore#2765

### Changed
- Frontend:
  - ITISFoundation/osparc-simcore#2823
  - ITISFoundation/osparc-simcore#2820
  - ITISFoundation/osparc-simcore#2821
  - ITISFoundation/osparc-simcore#2801
  - ITISFoundation/osparc-simcore#2790
  
- Computational backend improvements: 
  - ITISFoundation/osparc-simcore#2787
  - ITISFoundation/osparc-simcore#2842


- Refactoring webserver settings ITISFoundation/osparc-simcore#2750:
  - ITISFoundation/osparc-simcore#2836
  - ITISFoundation/osparc-simcore#2846
  - ITISFoundation/osparc-simcore#2828
  - ITISFoundation/osparc-simcore#2814

- Libraries upgrades
  -  ITISFoundation/osparc-simcore#2762 
  -  ITISFoundation/osparc-simcore#2832
  - ITISFoundation/osparc-simcore#2809

- Services upgrade:
  - ITISFoundation/osparc-simcore#2793

- E2E:
  - ITISFoundation/osparc-simcore#2802
  - ITISFoundation/osparc-simcore#2775

### Open issue / ongoing
- webserver responsiveness issue (503s) under observation

- ITISFoundation/osparc-simcore#2396)
- ITISFoundation/osparc-simcore#2008
- ITISFoundation/osparc-simcore#2409
- ITISFoundation/osparc-simcore#2777
- ITISFoundation/osparc-simcore#2798
- ITISFoundation/osparc-simcore#2817
- ITISFoundation/osparc-simcore#2826
- ITISFoundation/osparc-simcore#2827
- ITISFoundation/osparc-simcore#2847

**Comment by sanderegg** [comment]
## Update on sprint [E. Schackleton](https://github.com/ITISFoundation/osparc-issues/milestone/28)

### New
- Security: ITISFoundation/osparc-simcore#2826
- ITISFoundation/osparc-simcore#2874

### Bug fixes
- ITISFoundation/osparc-simcore#2932
- ITISFoundation/osparc-simcore#2926
- ITISFoundation/osparc-simcore#2928
- ITISFoundation/osparc-simcore#2879
- ITISFoundation/osparc-simcore#2399
- ITISFoundation/osparc-simcore#2883
- ITISFoundation/osparc-simcore#2875
- ITISFoundation/osparc-simcore#2786
- ITISFoundation/osparc-deployment-agent#41

### Changed
- Webserver refactoring
  - ITISFoundation/osparc-simcore#2910
  - Garbage collector can be run as a separate service: ITISFoundation/osparc-simcore#2757, ITISFoundation/osparc-simcore#2906, ITISFoundation/osparc-simcore#2905, ITISFoundation/osparc-simcore#2904, ITISFoundation/osparc-simcore#2901, ITISFoundation/osparc-simcore#2899, ITISFoundation/osparc-simcore#2834
- ITISFoundation/osparc-simcore#2895
- ITISFoundation/osparc-simcore#2869
- ITISFoundation/osparc-simcore#2855
- Libraries upgrades
  -  ITISFoundation/osparc-simcore#2916
  - ITISFoundation/osparc-simcore#2902
  - ITISFoundation/osparc-simcore#2893
  - ITISFoundation/osparc-simcore#2887
  - ITISFoundation/osparc-simcore#2890
  - ITISFoundation/osparc-simcore#2864
  - ITISFoundation/osparc-simcore#2827
  - ITISFoundation/osparc-deployment-agent#42
  - ITISFoundation/osparc-deployment-agent#43
- Deployment
  - ITISFoundation/osparc-simcore#2892
  - ITISFoundation/osparc-simcore#2888
- CI
  - ITISFoundation/osparc-simcore#2907
  - ITISFoundation/osparc-simcore#2900
  - ITISFoundation/osparc-simcore#2873
  - ITISFoundation/osparc-deployment-agent#27
  - ITISFoundation/osparc-deployment-agent#40
  - ITISFoundation/osparc-deployment-agent#39
  - ITISFoundation/osparc-deployment-agent#35
  - ITISFoundation/osparc-deployment-agent#34
  - ITISFoundation/osparc-python-runner#41
  - ITISFoundation/osparc-python-runner#40
  - ITISFoundation/osparc-python-runner#36
  - ITISFoundation/osparc-python-runner#39
  - ITISFoundation/osparc-dask-gateway#27
  - ITISFoundation/osparc-dask-gateway#28
### Open issue / ongoing
- webserver responsiveness issue (503s) under observation
- ITISFoundation/osparc-simcore#2396)
- ITISFoundation/osparc-simcore#2008
- ITISFoundation/osparc-simcore#2777
- ITISFoundation/osparc-simcore#2817
- ITISFoundation/osparc-simcore#2897
- ITISFoundation/osparc-simcore#2898
- ITISFoundation/osparc-python-runner#34
- ITISFoundation/osparc-simcore#2935

- ITISFoundation/osparc-simcore#2847

**Comment by sanderegg** [comment]
## Update on sprint [Macarons](https://github.com/ITISFoundation/osparc-issues/milestone/29)

View of this issue on [Zenhub](https://app.zenhub.com/workspaces/osparc-workdev-5c9260f3d76ef51f6b0fe78d/issues/itisfoundation/osparc-issues/428) March1 - Apr 3

### New
- Security: ITISFoundation/osparc-simcore#2826
- ITISFoundation/osparc-simcore#2874

### Bug fixes

### Changed
- Webserver refactoring
- Libraries upgrades
- Deployment
- CI
### Open issue / ongoing
- webserver responsiveness issue (503s) under observation
- ITISFoundation/osparc-simcore#2396)
- ITISFoundation/osparc-simcore#2008
- ITISFoundation/osparc-simcore#2777
- ITISFoundation/osparc-simcore#2817
- ITISFoundation/osparc-simcore#2897
- ITISFoundation/osparc-simcore#2898
- ITISFoundation/osparc-python-runner#34

**Comment by sanderegg** [comment]
## Update on sprint [Croissant](https://github.com/ITISFoundation/osparc-issues/milestone/30)

### Done

### Ongoing

### Open

**Comment by sanderegg** [comment]
## Update on sprint [Diolkos](https://github.com/ITISFoundation/osparc-issues/milestone/31)

### Done

- Storage refactoring/5Gib limit:
  https://github.com/ITISFoundation/osparc-simcore/issues/3098
  https://github.com/ITISFoundation/osparc-simcore/issues/3100
  https://github.com/ITISFoundation/osparc-simcore/issues/3144

- Libraries updates:
  https://github.com/ITISFoundation/osparc-simcore/issues/3092
  https://github.com/ITISFoundation/osparc-simcore/issues/3095
  https://github.com/ITISFoundation/osparc-simcore/issues/3112
  https://github.com/ITISFoundation/osparc-simcore/issues/3135
- CI:
  https://github.com/ITISFoundation/osparc-simcore/issues/3085
  https://github.com/ITISFoundation/osparc-simcore/issues/3094
  https://github.com/ITISFoundation/osparc-simcore/issues/3097
  https://github.com/ITISFoundation/osparc-simcore/issues/3099
  https://github.com/ITISFoundation/osparc-simcore/issues/3124
- Others:
  https://github.com/ITISFoundation/osparc-simcore/issues/3129
  https://github.com/ITISFoundation/osparc-simcore/issues/3130
  https://github.com/ITISFoundation/osparc-simcore/issues/3122
  https://github.com/ITISFoundation/osparc-simcore/issues/3114

### Ongoing
- Dy-sidecar case: https://github.com/ITISFoundation/osparc-issues/issues/638
- 5Gib case: https://github.com/ITISFoundation/osparc-simcore/issues/3021
- https://github.com/ITISFoundation/osparc-simcore/issues/3073
- https://github.com/ITISFoundation/osparc-simcore/pull/3112

### Open
- https://github.com/ITISFoundation/osparc-simcore/issues/3137
- https://github.com/ITISFoundation/osparc-simcore/issues/3145
- https://github.com/ITISFoundation/osparc-simcore/issues/3151
- ITISFoundation/osparc-simcore#2396)
- ITISFoundation/osparc-simcore#2008
- ITISFoundation/osparc-simcore#2817
- https://github.com/ITISFoundation/osparc-simcore/issues/2156
- https://github.com/ITISFoundation/osparc-simcore/issues/2759
- https://github.com/ITISFoundation/osparc-simcore/issues/2715
- https://github.com/ITISFoundation/osparc-simcore/issues/2980
- https://github.com/ITISFoundation/osparc-simcore/issues/3005
- https://github.com/ITISFoundation/osparc-simcore/issues/3000
- https://github.com/ITISFoundation/osparc-simcore/issues/2994
- https://github.com/ITISFoundation/osparc-simcore/issues/2991
- https://github.com/ITISFoundation/osparc-issues/issues/617
- https://github.com/ITISFoundation/osparc-simcore/issues/3078
- https://github.com/ITISFoundation/osparc-simcore/issues/3033

**Comment by sanderegg** [comment]
## Update on sprint [Brutalism](https://github.com/ITISFoundation/osparc-issues/milestone/32)

### Done

- Storage refactoring/5Gib limit:
  - ITISFoundation/osparc-simcore#3021
- Libraries updates:
- CI:
- Others:

### Ongoing
- Dy-sidecar case: https://github.com/ITISFoundation/osparc-issues/issues/638
- ITISFoundation/osparc-issues#617
  - https://github.com/ITISFoundation/osparc-simcore/issues/3223

### Open
- https://github.com/ITISFoundation/osparc-simcore/issues/3073
- https://github.com/ITISFoundation/osparc-simcore/pull/3112
- https://github.com/ITISFoundation/osparc-simcore/issues/3145
- https://github.com/ITISFoundation/osparc-simcore/issues/3151
- ITISFoundation/osparc-simcore#2396
- ITISFoundation/osparc-simcore#2008
- ITISFoundation/osparc-simcore#2817
- https://github.com/ITISFoundation/osparc-simcore/issues/2156
- https://github.com/ITISFoundation/osparc-simcore/issues/2759
- https://github.com/ITISFoundation/osparc-simcore/issues/2715
- https://github.com/ITISFoundation/osparc-simcore/issues/2980
- https://github.com/ITISFoundation/osparc-simcore/issues/3000
- https://github.com/ITISFoundation/osparc-simcore/issues/2994
- https://github.com/ITISFoundation/osparc-simcore/issues/2991
- https://github.com/ITISFoundation/osparc-simcore/issues/3078
- https://github.com/ITISFoundation/osparc-simcore/issues/3033

**Comment by elisabettai** [comment]
Closing this one, since we have a new one for y6 (#675)
