### ISSUE TITLE
After ungrouping a nodes-group the study gets corrupted

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#439]
After ungrouping a nodes-group, the frontend removes the ```parent```s field in the workbench data, but the backend doesn't remove it when that field s missing.

**Comment by sanderegg** [comment]
@odeimaiz this one was fixed right?

**Comment by KZzizzle** [comment]
@odeimaiz I guess this issue is now deprecated?

**Comment by odeimaiz** [comment]
yep, one day we will bring it back
