### ISSUE TITLE
When Study is duplicated, rename

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#444]
When you duplicate a study, rename the duplicate (e.g. _copy or _V#)

**Comment by KZzizzle** [comment]
beware if you decide to append a full timestamp

**Comment by GitHK** [comment]
will append the time when it was cloned in the following format `HH:MM:SS`, this should be enough for the user to distinguish between cloned duplicated studies. This will also apply to imports
