### ISSUE TITLE
Tensorflow/pytorch-specific solvers with GPU capabilities

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#451]
**Describe the user role**
As an oSPARC user, I would like to be able to run tensorflow/pytorch calculations as GPU-enabled "runner services".  

**Describe the goal**
As far as I understand, current runner services do not supply solvers that are compatible with machine learning libraries tensorflow and pytorch. The goal is to provide such runners that do support these libraries.

**Describe the benefit**
This is essential to the development of AI pipelines on oSPARC.

**Additional context**
Refers to https://github.com/ITISFoundation/osparc-issues/issues/332

**Comment by KZzizzle** [comment]
just to update, a tensorflow python runner now exists
