### ISSUE TITLE
Deployment of tensorflow/pytorch jupyterlab notebooks

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#452]
**Describe the user role**
As an oSPARC user, I would like to be able to access jupyterlab notebook services that have tensorflow and pytorch pre-installed.

**Describe the goal**
Run tensorflow/pytorch inside jupyterlab notebooks, and in general have access to an "AI ecosystem" on oSPARC.

**Describe the benefit**
It saves the time required to pip install in the first cell of every project.

**Additional context**
Refers to https://github.com/ITISFoundation/osparc-issues/issues/332

**Comment by KZzizzle** [comment]
@newton1985 perhaps we can close this one? 
![image](https://user-images.githubusercontent.com/28002886/146183478-6270ce14-4d36-4e58-8619-9087a54d723c.png)

**Comment by newton1985** [comment]
@KZzizzle I don't know... jk.
