### ISSUE TITLE
Multi-select services in study window

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#465]
**Describe the user role**
As an oSPARC user, I would like to be able to draw a rectangle on the study window to multi-select several services at once, and move them across the screen as a group.

**Describe the goal**
Efficient translation of services in the study window.

**Describe the benefit**
This would really be intuitive from a user point of view, and save a lot of time organizing services.

**Comment by KZzizzle** [comment]
@newton1985 following the mentioned PR's you can now multiselect by holding down the ctrl key and this will allow you to move them in the workbench. Would that satisfy the use case or could it only be fulfilled by drawing a rectangle?

**Comment by newton1985** [comment]
@KZzizzle @odeimaiz I know I'm being a stickler about it... but the rectangle is really what is needed. The multiselect using control is a step in the right direction, but the rectangle would make the difficulty of manipulations "order 0" instead of linear with project size.
