### ISSUE TITLE
osparc not loading file

### ISSUE THREAD

**Issue by bandrow** [ITISFoundation/osparc-issues#485]
## Long story short
I started here https://sparc.science/datasets/99?type=dataset&tab=files&path=files%2Fderivative
clicked on ratHeartMesh.vtk
and got to osparc
I have been waiting for 5 minutes and it still has not loaded. Something seems wrong.
It did load the 
meshMarker.csv csv file, so the platform is up.
 

```

**Comment by KZzizzle** [comment]
@ignapas  is this about the tokens again?

**Comment by ignapas** [comment]
> ## Long story short
> I started here https://sparc.science/datasets/99?type=dataset&tab=files&path=files%2Fderivative
> clicked on ratHeartMesh.vtk
> and got to osparc
> I have been waiting for 5 minutes and it still has not loaded. Something seems wrong.
> It did load the
> meshMarker.csv csv file, so the platform is up.

Yes, we are experiencing some problems while downloading the files. We are now trying to understand what causes the problem to fix it as soon as possible.

**Comment by KZzizzle** [comment]
@ignapas this seems not to be an issue anymore - can it be closed?
