### ISSUE TITLE
Pennsieve Invalid Key Leads to Not Loading s3

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#492]
**Long Story Short**
Using the Pennsieve API through the oSPARC GUI, an invalid API key will result in not loading s3 (in addition to not loading Dat--core but this is expected)

**Expected Behavior**
If the Pennsieve key is invalid, I expect that Dat-core would not be loaded in Data but that s3 would still be available for me

**Actual behaviour**
s3 is also no longer accessible (no data in File picker and Data tabs)

**Steps to reproduce**
Enter an invalid key in the Pennsieve API entry
![image](https://user-images.githubusercontent.com/28002886/125603478-cbcd3ce3-8fc9-4957-a76a-1d56c4cda38c.png)

**Comment by sanderegg** [comment]
@KZzizzle this is not the case anymore right? or at least I cannot reproduce it.

**Comment by KZzizzle** [comment]
nope let's close and I'll reopen if it comes up again
