### ISSUE TITLE
Interesting error message upon adding broken link

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#504]
## Long story short
I added a broken link for a study-thumbnail and I got this interesting error message:

![image](https://user-images.githubusercontent.com/33161876/133041202-44b5bf72-1df5-4633-b4f8-90459481f919.png)

**Comment by odeimaiz** [comment]
In order to prevent XSS attacks, before setting and rendering the provided link we use the DOMPurify library to "curate" the url. Apparently, it didn't like it and made some corrections to the url.

Is it the message itself what you would change?

**Comment by mguidon** [comment]
Ah this comes from a library. I thought you created the sentence yourself. It just reads strange. Maybe change to
"While parsing an input, the following error occurred: 'There was some curation....'"
I like the functionality, looks like we care about security.

**Comment by KZzizzle** [comment]
@mguidon what would be a DoD for this issue?

**Comment by elisabettai** [comment]
It should be fixed by now, according @odeimaiz
