### ISSUE TITLE
M1–12 Enhancements of the modeling/simulator/postpro service and framework

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#519]
This is the central service/framework for the creation and handling of 3D geometries, the setup and launching of simulations, and the visualization and postprocessing of results. It is also the most graphically interactive service and plays a central role for GUI-oriented users (i.e., the pendant to what the API offers for more scripting-oriented users). As such, it is crucial that this service/framework be easy-to-use, interactive, and comprehensive.

**Deliverable: platform service with at least 70% of the functionality in Appendix I (Q3 - updates will be demonstrated in each NIH update meeting)**

**Comment by esraneufeld** [comment]
![image](https://user-images.githubusercontent.com/33489840/137679511-71af1084-e923-4d0c-9000-24feb203f33d.png)

**Comment by colinRawlings** [comment]
Targeted for sprint beginning 11.7.22:

# ✨Features
- Measure edits in the modeler (last 10%) [CR/IP]
- Enhanced file browser (last 10%) [IP]
- Materials DB [OM]
- s4l:web modes - e.g. postpro-only for TI planning [CR/IP]
- UI for graceful startup - no more blank panels and `server disconnected` warnings at startup [IP] 

# ♻️Maintenance
- Port `EspressoModeling` (to get tests enabled) [CR]
- Drag and drop library upgrade [IP]
- Steal permissions settings strategy from jupyterlab project's dockerfiles [#329](https://git.speag.com/oSparc/osparc-s4l/-/issues/329)

# 🐛Bugs
- Multi browser support [IP] [#330](https://git.speag.com/oSparc/osparc-s4l/-/issues/330)
- Provide `nvcc` for rec5g equivalent source algorithms [#331](https://git.speag.com/oSparc/osparc-s4l/-/issues/331)
