### ISSUE TITLE
M1–12 DevOps: platform monitoring and maintenance; fixing of stability issues; down-time reduction

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#529]
During Y5, continuous work is expected regarding:
- Status monitoring and maintenance of the platform (includes as well monitoring of AWS, storage); improvement of the monitoring infrastructure
- Platform testing, e.g., adding automatic tests for new services / functionality
- Scaling and monitoring dynamic services
- Reducing down-time
- Bug fixing of reported issues (internal and external) and issues arising from continuous development of the platform

**Deliverable: continuous DevOps activity (Q1, Q2, Q3, Q4 - updates will be demonstrated in each NIH update meeting)**

**Comment by elisabettai** [comment]
Closing this one, since we have a new one (together with maintenance) for y6 #675
