### ISSUE TITLE
Expected value to be a map but found 'undefined'

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#544]
There is a SPARC user who is trying to open a study but cannot. The error message from webserver is:
```log
WARNING: simcore_service_webserver.projects.projects_db:__load_projects(403) - project in db with uuid [432] failed validation, please check. error: 9 validation errors for ProjectAtDB


workbench -> 9b1091d3-4200-53c1-9d4f-2c112e005778 -> outputs -> outFile

  value is not a valid boolean (type=value_error.strictbool)
```

```json
{
  "3b4ef82f-7bb2-4bee-8c9c-e4b7d9d5c554": {
    "key": "simcore/services/dynamic/jupyter-octave-python-math",
    "version": "1.6.5",
    "label": "JupyterLab Math (Python+Octave)",
    "inputs": {},
    "inputNodes": [],
    "parent": null,
    "thumbnail": ""
  }
}
```

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/9gi45nk8djbajgyeyhipkuwiao) *by @KZzizzle*._

**Comment by KZzizzle** [comment]
Update:
"It didn't work at 1:30 Eastern time, and so I shared it with my organization and got a share link. This worked.  After I exited this other browser tab, and logged out, I was able to log back in and enter it normally"

**Comment by odeimaiz** [comment]
Study ID: dd6fd2b0-9a34-11eb-8758-02420a0b012c

**Comment by pcrespov** [comment]
@KZzizzle I validated the project and does not show errors. The errors logs you reported is from a different project which actually has some issues ... I am building a diagnose tool to question the entire db and find others.
