### ISSUE TITLE
PyTorch Service Fails

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#547]
## Long story short
After the Jupyter ML PyTorch Service crashed while training a neural network, I tried to close and reopen the study. When attempting to reopen, the service fails

## Expected behavior
For the neural network to finish training.

## Actual behavior
Crash during training and subsequently rendering the whole study unusable.

## Steps to reproduce
1) Run Bryn Lloyd's Segmantic Code to train a neural network
2) wait for it to crash at some random epoch
3) close the study
4) attempt to reopen it.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "9addb14",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/9addb14/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "9addb14",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/9addb14/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "screenResolution": {
      "width": 1920,
      "height": 1080
    },
    "windowResolution": {
      "width": 2133,
      "height": 968
    }
  }
]
```

**Comment by Konohana0608** [comment]
When attempting to make a new study to try over, I realized that the Service ML PyTorch itself just fails to load even if importing a new one in a new study. And when then closing the study and trying to open it back up again, the study fails to load as described above. So the failing study probably happens due to it containing a PyTroch service with an error?

![failing ML PyTorch](https://user-images.githubusercontent.com/61539759/134336432-490aa5b7-0ce6-4ab8-b45e-ba3c90a0f679.jpg)
.

**Comment by elisabettai** [comment]
Hi @Konohana0608, are you still having this type of issues with PyTorch services?
