### ISSUE TITLE
Collapsing primary column in GUI will create irretrievable blanks

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#553]
When I collapse the primary (leftmost column) in workbench GUI, that will result in a blank column uncollapsed and no way to retrieve the column

![image](https://user-images.githubusercontent.com/28002886/140973813-3da6d73d-218a-40f2-909e-b29f49173d4c.png)

**Comment by odeimaiz** [comment]
Fixed in https://github.com/ITISFoundation/osparc-simcore/pull/2617
