### ISSUE TITLE
Fix duplicate feature for large studies

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#558]
Duplicating large studies fails

**Comment by KZzizzle** [comment]
related to #466

**Comment by pcrespov** [comment]
## Update on sprint [Croissant](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20220603_Croissant.md)

Relates to
- SAN gives guidelines to develop: ITISFoundation/osparc-simcore#2152
- TN bug: ITISFoundation/osparc-issues#560
- copy nodes! including state data could be achieved as well: ITISFoundation/osparc-issues#259
- bug report: ITISFoundation/osparc-issues#558
- ops shows heavy use of resources with export: ITISFoundation/osparc-simcore#2805 



### Done

- MS defined a use-case
- ITISFoundation/osparc-simcore#3048

### Ongoing

- API models ITISFoundation/osparc-simcore#3082
- clone handler: ITISFoundation/osparc-simcore#2974

### Open

- storage (waiting for rclone and 5GB upload feature)
- benchmarks *at least* with MS use case

**Comment by pcrespov** [comment]
## Update on sprint [Diolkos](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20220704_Diolkos.md)

No progress on this issue during this sprint

**Comment by sanderegg** [comment]
## Update on sprint [Brutalism](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20220829_Brutalism.md)

### Planned

This issue aims to enhance cloning of **large** studies. We are

### Done

- https://github.com/ITISFoundation/osparc-simcore/pull/3234
- https://github.com/ITISFoundation/osparc-simcore/pull/3235
- https://github.com/ITISFoundation/osparc-simcore/pull/3260
- https://github.com/ITISFoundation/osparc-simcore/issues/3268

### Ongoing

- ITISFoundation/osparc-simcore#3082: improving API models
- ITISFoundation/osparc-simcore#2974: clone handler and long polling operations

### Summary

Thanks to https://github.com/ITISFoundation/osparc-simcore/pull/3077, https://github.com/ITISFoundation/osparc-simcore/issues/3100, https://github.com/ITISFoundation/osparc-simcore/issues/3144 and https://github.com/ITISFoundation/osparc-simcore/pull/3021 a.k.a. complete refactoring of the storage micro-service the problem with copying studies containing files >5Gb is possible and executed in place.

The webserver micro-service and the frontend were modified to allow to use the same mechanism as "creating a project from a template" but for any study. The operation which can be potentially very long (depending on the amount of data) has been modified to leverage "long running operations in a REST API" which will allow to report a progress (still ongoing). A way to retrieve these long running operations of a specific user will allow the frontend to be F5-refreshed and recover its list of tasks. 

Still ongoing are:
- modify the storage "copy" operation to report progress
- improve the frontend to show the copy progress
- the webserver(s) services may be restarted, scaled, etc... currently this leads to losing the copy operation. This needs to be improved by using a distributed message system (such as RabbitMQ)
- current tests show that a study containing about 10Gb could be copied, a 100Gb one not.

**Comment by sanderegg** [comment]
## Update on sprint [Vaporwave](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221007_Vaporwave.md)

### Done
- https://github.com/ITISFoundation/osparc-simcore/issues/3290
- https://github.com/ITISFoundation/osparc-simcore/issues/3287
- https://github.com/ITISFoundation/osparc-simcore/issues/3335
- https://github.com/ITISFoundation/osparc-simcore/issues/3326

### Not reproducible
- https://github.com/ITISFoundation/osparc-issues/issues/604

### Ongoing
- https://github.com/ITISFoundation/osparc-simcore/pull/3168

### Open
- In case of web browser refresh or disconnection/later reconnection, currently no recovery of copy tasks (but they will still eventually complete) - will not be implemented for now.

**Comment by elisabettai** [comment]
Closing this, as discussed with @sanderegg. The only open part is an e2e test, that will be tackled on the side at another point.
Note: as of today, this has not been released to production yet (but will be).
fyi @esraneufeld
