### ISSUE TITLE
Export/Copy/Publish_Template : Structure & Code Only

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#560]
## Long story short
As it stands, it is very difficult (and in many cases impossible) to export or publish a template from a large study. However, often it is not necessary to copy _every_ file in a study, just the structural elements. I.e., the nodes, the connections between them, the directory structure of jupyter notebooks, and code/config files (*.py, *.ipynb, *.txt etc.). Therefore I propose we extend the export/publish options to allow the user to filter which data types they would like to consider when cloning the study.

## Expected behaviour
I expect to be able to export a study's contents, clone a study, or publish a study template, without necessarily copying large data files that are generated during the execution of the pipeline. Ideally, the user could filter (or otherwise somehow specify) which files/filetypes they would like to preserve with the copy. 

## Actual behaviour
Currently publishing/exporting a study tries to zip *everything*, including potentially (very) large intermediate files that are produced during pipeline execution.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "349c2dc",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/349c2dc/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "349c2dc",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/349c2dc/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 1240
    }
  }
]
```

**Comment by AntoninoMarioC** [comment]
In addition, it would be great to allow the user to export the pipeline in some latex standard formats for graphs, so that automatic generation of reports can be done as well as documentation.

**Comment by KZzizzle** [comment]
related to #558 and #466

**Comment by sanderegg** [comment]
There is now a function when creating a Template that allows for only copying the study skeleton without all its data. This is not yet with all filtering but can be a workaround:
![image](https://user-images.githubusercontent.com/35365065/152508390-b23ab058-416e-4b1d-8850-589f520a55f8.png)

**Comment by ignapas** [comment]
Export and duplication features will be disabled until we come up with a proper implementation.

**Comment by esraneufeld** [comment]
but the copy/publish/export without data remains available?

**Comment by esraneufeld** [comment]
@pcrespov 
with the current data loss situation, i would very much appreciate, if we could at least keep the copy without data alive. what speaks against that?

**Comment by pcrespov** [comment]
> @pcrespov with the current data loss situation, i would very much appreciate, if we could at least keep the copy without data alive. what speaks against that?

that it is implemented with export (the one we have disabled)
Nonetheless, we have a plan in place since a long time (and even some parts implemented) with a new design so it is time to retake it. SEE ITISFoundation/osparc-simcore#2152

**Comment by elisabettai** [comment]
@newton1985, it this one still high priority, given that you can at least create a template  (with/without the data).
![image](https://user-images.githubusercontent.com/18575092/222685244-d2682db9-3bb2-4827-9501-7588e718a788.png)

Maybe you can write down a smaller case that reflects the functionality has been already put in place.

**Comment by newton1985** [comment]
@elisabettai In the past this feature hasn't worked for larger studies, so to investigate the current status I gave it a try on osparc.io with Bladder Control as a test case - just the study structure, no data. It failed with the following message:
![failure](https://user-images.githubusercontent.com/70750341/222687263-bed727c0-71ae-42ca-8554-3a9f698f7b35.jpg)

I guess this shouldn't happen since I requested to create a template _without_ data.

**Comment by newton1985** [comment]
but assuming that the feature is working, I think it would satisfactorily address the need, and we could close the issue
