### ISSUE TITLE
Allowing the possibility to add the following icons/tags on a Service

### ISSUE THREAD

**Issue by AntoninoMarioC** [ITISFoundation/osparc-issues#567]
**Describe the user role**
I'd like to visually see on each service, tags that allow the user/collaborator to:
1. specify if the service includes code that has been verified and approved (developer+tester) and  tags specifying who did it (a legend can be also visualized within a box in the pipeline)
2. specify if the service includes code that has been verified by single user and not approved (only developer)
3. change the color of the service icon and a label associated to it. E.g. a project contains services that are file pickers (**data input**), do **pre-processing** of data, actual **calculation**, **post-processing**, The user would like to add these tags to the different services and have the possibility to visualized a legend within the pipeline.

**Comment by esraneufeld** [comment]
dear Antonino,
the TSR function (related to the stars) is meant to handle quality assurance. could you review the TSR function and then suggest what is insufficient? at the same time, we need to be careful in changing it, as the TSR is an established standardized form of reporting.

**Comment by esraneufeld** [comment]
with regard to 3: the possibility of labeling and of associating RRIDs also exists. please comment how you would adapt the existing approach

**Comment by KZzizzle** [comment]
@AntoninoMarioC do you have any input on Esra's comments?

**Comment by pcrespov** [comment]
@AntoninoMarioC could you please answer Esra's comments?

**Comment by pcrespov** [comment]
@AntoninoMarioC is this evaluation taking place once the service is in osparc or afterwards. Notice that we envision to include some validation "certificates" before it gets on-boarded. See

![image](https://user-images.githubusercontent.com/32402063/149789928-32a94e3c-9b12-45b4-971b-a6bd654b17ec.png)

**Comment by pcrespov** [comment]
@AntoninoMarioC, @newton1985  do you have any inputs on the questions above?

**Comment by AntoninoMarioC** [comment]
Hi @pcrespov @esraneufeld, 
labeling is fine. I would still like, as user, to be allowed to change the background color or frame color of the different services, and have a (automatic) editable legend panel where I can change the color legend.

E.g. yellow is segmentation, green (:) is Solving, blue is postpro neuro. When I change the color of a service, a legend panel appears at the first istance of color change, or gets populated with the additional color and respective editable label.

In addition, it would be great that if the user decides to make a black box of the services with the same colors, the blackbox inherits the color of those services (or can be edited and changed).

Is that all?

**Comment by elisabettai** [comment]
Hi @AntoninoMarioC, do you think the bookmarks and annotating features fit your purpose?

**Comment by pcrespov** [comment]
Yes @AntoninoMarioC , check visuals in ITISFoundation/osparc-simcore#2966
