### ISSUE TITLE
osparc-fs: Hardware

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#578]
Provide standalone storage cluster based on ceph with the following characteristics:
- 100 % S3 API compatibility with minio/AWS S3
- More reliable and faster than current solution
- Possibility to do backups
- Block storage provisioning for:
  - nfs/cifs mounts
  - file-based databases (dvc, binary repo)

**MVP**: osparc can be deployed with ceph as storage backend.

This is part of #513

**Comment by mrnicegyu11** [comment]
Some notes from our talk with Tobi:
--- Backups are currently not planned. S3 can be configured to have versioning. Currently there is no HDD RAID.
--- We could do backups by copying the data using the S3 API.

**Comment by oetiker** [comment]
@mrnicegyu11 note that there is storage redundancy! The setup can withstand a disk-loss as well as the loss of a host!

When properly configured with 3 or even 5 hosts, the redundancy can be even larger.

In other words, you should be somewhat safe from HW failure now, but once the system is fully setup with more than 2 hosts your data will be pretty safe :)
