### ISSUE TITLE
Jupyter notebook activity indicator

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#590]
Add an indicator in the dashboard that let the user know if a jupyter notebook block has notebooks that are actively running code or not.

I'm jumping between blocks while coding while running different notebooks. It would be nice to have an indicator in the dashboard instead of having to open up the notebook gui to check the status.

**Comment by GitHK** [comment]
The Jupiter notebook which is ran in the platform has it's own internals, currently there is no plan to expose the status of the notebook in the platform.
