### ISSUE TITLE
timestamps in the logger

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#591]
**Describe the user role**
As an oSPARC user, I would like to know when certain events occurred that are recorded in the logger.

**Describe the goal**
Provide temporal information for service events.

**Describe the benefit**
For example, to know how long a service has been running/working on a problem, or to distinguish between similar messages.

**Additional context**

**Comment by pcrespov** [comment]
@GitHK the dy-sidecar could use the healthcheck and log upstream what is asked here. Could you please have a look at it? thx

**Comment by GitHK** [comment]
@newton1985

If I understand this correctly in the below view you would like to also see some timestamps appear, right? Would a short date and time be sufficient, like `10/02 07:59:33`? Or do you find it more useful to be verbose `10/02/2022 07:59:33`?

<img width="804" alt="Screenshot 2022-02-10 at 07 57 43" src="https://user-images.githubusercontent.com/5694077/153354102-eca04988-dfc9-43be-86e4-aa3066619bc2.png">
 
@sanderegg I guess the computational sidecars should also handle this.

**Comment by newton1985** [comment]
@GitHK, a short date/time should be fine!

**Comment by sanderegg** [comment]
@GitHK the way the log is formatted is in fine a front-end thing. Just have the full information in the backend and I will adapt it accordingly

**Comment by GitHK** [comment]
@sanderegg I think this https://github.com/ITISFoundation/osparc-simcore/issues/2157 already addresses it.

**Comment by elisabettai** [comment]
This implemented on master and should reach production in the coming days.
