### ISSUE TITLE
"Stop" button sometimes doesn't work 

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#593]
## Long story short
For certain computational services processing large datasets, the "stop" button has no effect.

## Expected behaviour
I expect the stop button to stop the service quickly.

## Actual behaviour
The service keeps running.

## Steps to reproduce
Create a computational service (for example, predict-labels), with a large input dataset, run it, then try to stop it.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "093554c",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/093554c/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "093554c",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/093554c/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "RadialMenu",
    "version": "1.2.0",
    "url": "https://github.com/victorqribeiro/radialMenu"
  },
  {
    "name": "GitGraph",
    "version": "1.4.0",
    "url": "https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 1297
    }
  }
]
```

**Comment by newton1985** [comment]
I noticed that also when closing a re-opening a study, sometimes the study opens with the computational service still "running", though nothing is being recorded in the log.

**Comment by newton1985** [comment]
ALSO!!!! Sometimes this results in the "Run" button not working either. For example, if I'm stuck in a state where the study believes that the pipeline is running (even though it isn't), and I delete the offending node and add a new one, then it won't start because it thinks it's running already.

**Comment by pcrespov** [comment]
@sanderegg could be the issue related with tdirector2 you commented me last week. If it is only front-end issue, please re-assign. thx

**Comment by elisabettai** [comment]
@newton1985, this should have been fixed in release on 19/04/2022 and should be fixed. 
https://github.com/ITISFoundation/osparc-simcore/releases/tag/v1.24.0

We close it for now, feel free to re-open if needed.
