### ISSUE TITLE
add "save" button

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#594]
## Long story short
It would be great to have a save button that allows data to be written to S3 without having to close the study. This would also provide users with quick feedback in case there is some issue communicating with storage.

## Expected behaviour
I expect that clicking this button would cause the study data to be stored to S3, but without interrupting use of the study.

## Actual behaviour
There is no save button (yet).

## Steps to reproduce
n/a

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "093554c",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/093554c/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "093554c",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/093554c/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "RadialMenu",
    "version": "1.2.0",
    "url": "https://github.com/victorqribeiro/radialMenu"
  },
  {
    "name": "GitGraph",
    "version": "1.4.0",
    "url": "https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 1240
    }
  }
]
```

**Comment by esraneufeld** [comment]
also, a `save copy` button complementing the `save` button would be nice.

**Comment by esraneufeld** [comment]
if the concern is, that this could end up in too frequent data transfer, perhaps an intelligent save that only saves services in which the data has changed could be envisioned.

**Comment by sanderegg** [comment]
## webbrowser
- click
- greys out the iframe
## webserver
- ```POST /projects/{project_id}/nodes/{node_id}:save``` (long running task)
## director-v2
- ```POST /v2/dynamic_services/{node_uuid}:save``` (long running task)
  - then calls the dynamic sidecar to pause (**docker pause**), save, resume (**docker unpause**) the service

**Comment by GitHK** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- fist attempt of having a save/restart feature https://github.com/ITISFoundation/osparc-issues/issues/594, https://github.com/ITISFoundation/osparc-

**Comment by sanderegg** [comment]
## Update on sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221114_KatherineSwitzer.md)
- https://github.com/ITISFoundation/osparc-issues/issues/594
  - https://github.com/ITISFoundation/osparc-simcore/issues/3447
  - https://github.com/ITISFoundation/osparc-simcore/pull/3501

**Comment by elisabettai** [comment]
Hi @sanderegg, from what I understood from PM1, this is not high priority for this sprint. I'll move it down in the PM2 board.

Related work is the new messaging from the backend to the frontend and that is also needed for s4l lite release, so I'll add that to the PM2 board (if I find the issue).

For the specifics of starting/stopping dynamic services, we should do more testing before if goes to production (I can help with that).

**Comment by sanderegg** [comment]
Hi @elisabettai , I created an issue and is now linked here: https://github.com/ITISFoundation/osparc-simcore/issues/3541

**Comment by sanderegg** [comment]
@newton1985 can we close this one?

**Comment by newton1985** [comment]
@sanderegg - do I understand correctly that we're dropping the request for this feature in favor of selective start/stop? Also, stopping a service triggers data transfer to storage, correct?

**Comment by GitHK** [comment]
When you stop the service, the service's state (usually the workspace) is transferred. All ongoing pending output ports are also awaited to finish before closing.

**Comment by newton1985** [comment]
Ok, great then yes close this one.

**Comment by sanderegg** [comment]
@newton1985 as the owner of the issue you have the final say.
Stopping a service triggers full saving of the service, yes.

**Comment by KZzizzle** [comment]
Just wanted to chime in (since I followed this issue) that the new stop
feature is super cool!
