### ISSUE TITLE
osparc disconnects from keyboard events

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#596]
**Long Story Short**
Approximately every 90 seconds, osparc stops grabbing keyboard events. The issue can be corrected by clicking again in the workbench/notebook etc., but it is annoying to continuously interrupt typing to re-establish connectivity. 

**Expected Behavior**
I expect to be able to type continuously (in a notebook etc) without losing connectivity to the event listeners.

**Actual behaviour**
Every 90 seconds (approx), osparc stops listening to the keyboard.

**Steps to reproduce**
Type in a jupyterlab notebook for > 90 seconds. 

**Environment**
I'm using a windows pc and a chrome browser. Apparently this issue is also replicable with firefox on linux as well.

**Additional context**

**Comment by elisabettai** [comment]
HI @newton1985, is this issue still relevant? Now the interactive services GUI should only start when you double-click.

**Comment by newton1985** [comment]
Hi @elisabettai - I haven't experienced this recently. I'll ping you guys/reopen in case I experience it again.
