### ISSUE TITLE
VNS Calibrator can't be started

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#599]
Service owner says:

It seems the VNS-Calibrator service is broken on the latest version of OSPARC. The service stays in the “connecting” state indefinitely. Looking at the log, I can see the following error:

```[bios-health-vns-calibrator:1.0.9] PermissionError: [Errno 13] Permission denied: '/home/jovyan/inputs/input_1/trials.pickle’```

**Comment by GitHK** [comment]
The issue was addressed a new version `1.0.12` was released.
