### ISSUE TITLE
Study run failure because of wrong input link in file-picker

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#601]
**Long Story Short**

I got a failure when running a pipeline, it was because of a wrong link inserted in file-picker.
**Expected Behavior**

- I get more information on why the pipeline failed
- file-picker should check that a link is valid
**Actual behaviour**

Pipeline run failure with no further message
**Steps to reproduce**

**Environment**

Pasted a text instead of a link in file picker

**Comment by sanderegg** [comment]
@elisabettai was that not fixed? close?

**Comment by elisabettai** [comment]
Yes, I'm pretty sure it was fixed.
