### ISSUE TITLE
Storage cannot handle file links in when saving study to template

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#604]
**Long Story Short**

I tried to save a Study to Template. With the option "Save with data" saving doesn't work

**Steps to reproduce**

Showed the steps to @mrnicegyu11 

**Environment**

Firefox, osparc.speag.com

**Comment by mrnicegyu11** [comment]
More Information: This fails because the study uses a filelink. The storage service throws the following error when creating the template:
```
ERROR:servicelib.aiohttp.rest_middlewares:Unexpected server error "<class 'KeyError'>" from access: 10.11.3.87 "POST /v0/simcore-s3/folders". Responding with status 500
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.8/site-packages/servicelib/aiohttp/rest_middlewares.py", line 75, in _middleware_handler
    response = await handler(request)
  File "/home/scu/.venv/lib/python3.8/site-packages/servicelib/aiohttp/rest_middlewares.py", line 203, in _middleware_handler
    resp: _ResponseOrBodyData = await handler(request)
  File "/home/scu/.venv/lib/python3.8/site-packages/simcore_service_storage/handlers.py", line 401, in create_folders_from_project
    await dsm.deep_copy_project_simcore_s3(
  File "/home/scu/.venv/lib/python3.8/site-packages/simcore_service_storage/dsm.py", line 831, in deep_copy_project_simcore_s3
    source = output["path"]
KeyError: 'path'
```

The filelink should be copied as-is into the template.

**Comment by mrnicegyu11** [comment]
Formally known as: `Saving study to template with File Picker input as link doesn't work`

**Comment by sanderegg** [comment]
@elisabettai , @mrnicegyu11 this is not reproducible on master deployment. I would wander in saying this was fixed with the storage refactoring (or the duplicate copy fixes). Please confirm and I think you could close it.

**Comment by elisabettai** [comment]
@sanderegg, you're right. It now works in master, I'll close the issue.

Just noticed a very small thing: the "Download" button in the FilePicker doesn't work with a [file link](https://user-images.githubusercontent.com/32800795/61083844-ff48fb00-a42c-11e9-8e63-fa2d709c8baf.png) (which I suppose is valid). But this more for @odeimaiz, I guess.
