### ISSUE TITLE
Flag inputs zipped by backend

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#613]
## Long story short
When I want to pass a zip file between services _as a zip file_, osparc usually (but not always, for some reason), unzips this file automatically, since is the default behavior for files that appear in an input port.   

## Expected behaviour
I expect osparc to flag the files it zips in an output port of a given service for the purpose of transferring data between services. This way it can differentiate between such files and user-zipped files, which should be preserved in the their zipped format (since this is what the user will be expecting).

## Actual behaviour
User-zipped files get unzipped automatically.

## Steps to reproduce
n/a

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "7e17def",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/7e17def/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "7e17def",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/7e17def/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "RadialMenu",
    "version": "1.2.0",
    "url": "https://github.com/victorqribeiro/radialMenu"
  },
  {
    "name": "GitGraph",
    "version": "1.4.0",
    "url": "https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2424,
      "height": 1149
    }
  }
]
```

**Comment by GitHK** [comment]
Does this still appear to be the case in the new dynamic-sidecar powered services? That behaviour should have been fixed. 
Also computational services should have this issue fixed by now.

@newton1985 can you confirm this?

**Comment by sanderegg** [comment]
@newton1985 I think this behavior will remain until we stop zipping files. The workaround is to create a "double" zipped file.

**Comment by sanderegg** [comment]
@newton1985  so it is consistent. it will always unzip a zip file provided the input port type is not ```application/zip``` which I think is 99% of the services.
So in case you need  a zip in the subequent service, you will need to zip twice before copying to the outputs.
