### ISSUE TITLE
Add use cases to Webinar

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#616]
Present features as part of a larger problem-solving use case during Webinar on April 26th

https://www.eventbrite.com/e/new-o2s2parc-user-interface-for-online-data-analysis-and-modelling-tickets-292384468817

**Comment by elisabettai** [comment]
We'll add this to our next [webinar](https://www.eventbrite.com/e/new-o2s2parc-user-interface-for-online-data-analysis-and-modelling-tickets-292384468817) on 26th of April.

**Comment by KZzizzle** [comment]
webinar has been uploaded to youtube at https://youtu.be/msXGYk2_89U
