### ISSUE TITLE
Sharing studies: silent fail if target user cannot access certain services

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#619]
## Long story short
When I try to share a study with a user, it may appear as though it has been successfully shared to the owner, but the "sharee" cannot see the study in his/her studies tab because he/she does not have access to a _specific_ service inside the study (e.g. S4L).

## Expected behaviour
In these circumstances, there are several obvious options: 1) make it impossible for the owner to share a study with a target who does not have access to all services inside that study (with an informative error message, including the specific problematic services), or 2) the study shows up in the studies tab of the target user, but with a lock (and an informative error message if access is attempted). 

## Actual behaviour
Silent failure: target user cannot see shared study.

## Steps to reproduce
Share a study with a user who does not have access to one or more services inside that study.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "d01a263",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/d01a263/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "d01a263",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/d01a263/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "Plotly",
    "version": "2.9.0",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "RadialMenu",
    "version": "1.2.0",
    "url": "https://github.com/victorqribeiro/radialMenu"
  },
  {
    "name": "GitGraph",
    "version": "1.4.0",
    "url": "https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 1851,
      "height": 975
    }
  }
]
```

**Comment by odeimaiz** [comment]
I would go for the second option:
The study shows up in the studies browser, but with a lock or another icon (and an informative message in the tooltip)

**Comment by GitHK** [comment]
I'd say this is closed? @newton1985 please reopen it if you think otherwise.

**Comment by elisabettai** [comment]
Reopening since I'm still experiencing it (i.e. shared a study with collaborator who did not have access to latest service version and he did not see the study card at all, instead of seeing it blocked).

**Comment by elisabettai** [comment]
@sanderegg, this can be closed now, right? Well, I know that I was the one re-opening it.

**Comment by sanderegg** [comment]
@elisabettai I would vote yes.
@newton1985 ?

**Comment by newton1985** [comment]
+1 yes
