### ISSUE TITLE
API framework for iSolve

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#621]
**User Story**:

`sim4life:web` currently runs `iSolve` in a `subprocess` and the task manager can display logs and progress info. This should be replaced by leveraging the `osparc API` to take advantage of scheduling those jobs. In a **first** step, the following features are required:
- Stream logs to the frontend
- Stream progress to the frontend
- Potentially users will reconnect to the scheduler, so logs/progress need to be re-flushed (Not possible with ARES now)
- Do we use tokens for this? Where do we store them (we dont want users to add them all the time). This will require platform wide `user/service/version` storage facilities (could be re-used for sim4life application preferencens.

**Second** step will include:
- In addition to logs/progress, convergence and sensor information in form of 2d-plots can be collected from `iSolve`. We should handle that as well.

**Notes**:
- If implemented properly in simphony, this will work automatically with the Desktop Application as well.
- See [here](https://git.speag.com/simphony/Simphony/-/tree/master/osparc/prototypes/osparc_api) for a prototype implementation for integration into sim4life
```[tasklist]
### Sundae
- [x] Submit jobs from the web version
- [x] Submit jobs from the desktop version
```

**Comment by pcrespov** [comment]
## Update on sprint [Croissant](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20220603_Croissant.md)

- New API server entrypoints so 
    - logs files
    - specify cluster in run options
    - logs stream or list (tail, etc)
    - progress stream
 - python clients: python and (probably) c++
    - doc + inital example 


### Done

- logs files
  - ITISFoundation/osparc-simcore#3072
  - ITISFoundation/osparc-simcore#3067
  - ITISFoundation/osparc-simcore#3051

### Ongoing
 -  ITISFoundation/osparc-simcore-python-client#27

### Open

- specify cluster in run options
- logs stream or list (tail, etc)
- progress stream

**Comment by pcrespov** [comment]
## Update on sprint [Diolkos](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20220704_Diolkos.md)

No significant progress on this issue during this sprint

**Comment by sanderegg** [comment]
Notes:
- status on integration in Sim4Life desktop unclear

**Comment by sanderegg** [comment]
Main framework to submit jobs was completed with [7Peaks milestone](https://github.com/ITISFoundation/osparc-simcore/milestone/71) .
Subsequent improvements/bugfixes will get their own issues.
