### ISSUE TITLE
Pipeline Update Issues

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#622]
Pipeline:
![image](https://user-images.githubusercontent.com/33152403/166691750-7b55828d-747d-4e0e-8159-362cb3cf4659.png)

App Mode:
![image](https://user-images.githubusercontent.com/33152403/166692782-42293145-27a4-4c94-9c61-c7243c0e41fb.png)

Issues:
- Pressing the Run button (not Next) does not advance to the next step when done. This is a UX choice.
- sleeper_2 is never executed, as the interactive Jupyterlab can start without it
- When a file is selected, it is not pulled by the Jupyterlab
- Bug: When the run button is pressed on sleeper_3, its (the sleeper's) view disappears:
![image](https://user-images.githubusercontent.com/33489840/166716613-2044ddbb-dda1-4b1f-87cd-7765d117cfd8.png)

Causes and Measures:
- Interactive services are started immediately when the study is opened and there is no means to specify if certain inputs are necessary
  - This a problem from many uses of voila to present results (e.g., TI TP), which require results to be computed before they are started.
  - Not in all instances, inputs to interactive services are a prerequisite (even if there is a connection?), nor should the service automatically restart if the inputs change. but sometimes yes
  - Does it make sense to allow users to define for inputs, whether they are necessary? then an interactive service could still i) force the execution of required upstream services, and ii) update/restart if a required input changes
- When a file is picked in the file picker, it should be pushed to the subsequent (interactive) service
- Pressing the run triangle should advance to the next step when done (agree?)
- There is some bug in the last step that needs to be fixed

and here is the corresponding [demo study](https://osparc.speag.com/#/study/bf3f0398-cb8d-11ec-a3ce-02420a0b058e)

**Comment by elisabettai** [comment]
This should have been fixed and demoed at the sprint review meeting ("Croissant") on 3.06.2022. 

Closing for now, @esraneufeld let us know if something is still missing.
