### ISSUE TITLE
Option to relaunch a dynamic service without going to Dashboard

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#631]
**Describe the user role**
As a user who experiences the failed start/crash of a dynamic service, I would like to be able to restart only that service instead of going back to the Dashboard and then back into the Study.

**Describe the goal**
Avoid the potentially long process of unlocking a study and entering it again when only one service is problematic.

**Describe the benefit**
While there are problems in JupyterLab (directory not found, service disconnected), it would be useful to be able to restart a single dynamic service if it fails for some reason

**Comment by sanderegg** [comment]
shall be implemented by
https://github.com/ITISFoundation/osparc-simcore/issues/3447

**Comment by sanderegg** [comment]
this was implemented using the start/stop buttons
