### ISSUE TITLE
improving dynamic-sidecar design

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-issues#638]
### dynamic sidecar service
- **Data loss** issues 
  - https://github.com/ITISFoundation/osparc-simcore/issues/3116 
  - https://github.com/ITISFoundation/osparc-simcore/issues/3141 
  - https://github.com/ITISFoundation/osparc-simcore/issues/3142
- https://github.com/ITISFoundation/osparc-simcore/issues/3172
- https://github.com/ITISFoundation/osparc-simcore/issues/3233
- https://github.com/ITISFoundation/osparc-simcore/issues/3247
- missing retry when uploading
    - https://github.com/ITISFoundation/osparc-simcore/issues/3242
- https://github.com/ITISFoundation/osparc-simcore/issues/3229
- https://github.com/ITISFoundation/osparc-simcore/issues/3293
### director v2 service
- timeouts:
   - https://github.com/ITISFoundation/osparc-simcore/issues/3091
   - https://github.com/ITISFoundation/osparc-simcore/issues/3111
   - https://github.com/ITISFoundation/osparc-issues/issues/708
- resource management : 
  - https://github.com/ITISFoundation/osparc-simcore/issues/3143
- https://github.com/ITISFoundation/osparc-simcore/issues/3170
- sidecars cleanup:
    - https://github.com/ITISFoundation/osparc-simcore/issues/3241
    - https://github.com/itisfoundation/osparc-simcore/issues/3219
    - https://github.com/ITISFoundation/osparc-simcore/issues/3266
- others:
  - https://github.com/ITISFoundation/osparc-simcore/issues/3228

## From users

- Service **restart** no closing the study
  - https://github.com/ITISFoundation/osparc-issues/issues/594 
  - https://github.com/ITISFoundation/osparc-issues/issues/631
  - https://github.com/ITISFoundation/osparc-issues/issues/630
- https://github.com/ITISFoundation/osparc-issues/issues/600
- https://github.com/ITISFoundation/osparc-issues/issues/585

## Uncategorised

- https://github.com/ITISFoundation/osparc-simcore/issues/3261
- https://github.com/ITISFoundation/osparc-issues/issues/659
- https://github.com/ITISFoundation/osparc-simcore/issues/3240
- https://github.com/ITISFoundation/osparc-issues/issues/663
- https://github.com/ITISFoundation/osparc-issues/issues/664

# Enhancements
- https://github.com/ITISFoundation/osparc-simcore/issues/3322

# Continous testing
- [E2E testing of large studies (open, close)](https://github.com/ITISFoundation/osparc-simcore/issues/3146)

**Comment by sanderegg** [comment]
link also #585

**Comment by GitHK** [comment]
- https://github.com/ITISFoundation/osparc-simcore/issues/3141

**Comment by GitHK** [comment]
-https://github.com/ITISFoundation/osparc-simcore/issues/3142

**Comment by pcrespov** [comment]
Two issues that IMO were missing above and were discussed during meeting

- [ ] we need to have the fix that cancels tasks in the dy-sidecar when the REST client timesout (currently all these task are accumulating)
- [ ] we need to have the fix in the dy-sidecar that prevents running XX docker-compose CLI calls in parallel (currently all these run in parallel and fuck up the host RAM/CPUs)

**Comment by GitHK** [comment]
- https://github.com/ITISFoundation/osparc-simcore/issues/3170

**Comment by GitHK** [comment]
- https://github.com/ITISFoundation/osparc-simcore/issues/3172

**Comment by GitHK** [comment]
## Update on sprint [Meteora]

### Done

- https://github.com/ITISFoundation/osparc-simcore/issues/3164
- https://github.com/ITISFoundation/osparc-simcore/issues/3165
- https://github.com/ITISFoundation/osparc-simcore/issues/3174
- https://github.com/ITISFoundation/osparc-simcore/issues/3179
- https://github.com/ITISFoundation/osparc-simcore/issues/3182
- https://github.com/ITISFoundation/osparc-simcore/issues/3189
- https://github.com/ITISFoundation/osparc-simcore/issues/3187
- https://github.com/ITISFoundation/osparc-simcore/issues/3195

### Ongoing 
- https://github.com/ITISFoundation/osparc-simcore/issues/3211

### Open

- https://github.com/ITISFoundation/osparc-simcore/issues/3116 between reboots dy-sidecar looses original volumes
- https://github.com/ITISFoundation/osparc-simcore/issues/3143
- https://github.com/ITISFoundation/osparc-simcore/issues/3091
- https://github.com/ITISFoundation/osparc-simcore/issues/3111
- https://github.com/ITISFoundation/osparc-simcore/issues/3142
- https://github.com/ITISFoundation/osparc-simcore/issues/3141 

User requests


- https://github.com/ITISFoundation/osparc-issues/issues/600
- https://github.com/ITISFoundation/osparc-issues/issues/585
- https://github.com/ITISFoundation/osparc-issues/issues/594
- https://github.com/ITISFoundation/osparc-issues/issues/631
- https://github.com/ITISFoundation/osparc-issues/issues/630

**Comment by sanderegg** [comment]
## Update on sprint [Brutalism](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20220829_Brutalism.md)


### Done

- Significant improvements on dy-sidecar start/stop reliability
- Command line in the dy-sidecar that allows for fast service data upload to S3 backend in case of problem → usual time loss down from hours to 20-30 minutes of manual intervention (https://github.com/ITISFoundation/osparc-simcore/pull/3255)
- Backups every 6h on AWS of each computer in the cluster 
- Service logs now show download/upload information (https://github.com/ITISFoundation/osparc-simcore/pull/3285)
- Typical metrics use-case:
  - 2 large studies contain 21 and 16 dynamic services with multi-GB per service respectively


### Ongoing
- During start: some services are “stuck” at creation time → need manual intervention (potential fixes https://github.com/ITISFoundation/osparc-simcore/issues/3249, https://github.com/ITISFoundation/osparc-simcore/pull/3254)
- Stop: some services sometimes fail to upload their data to AWS S3 storage → need manual intervention (potential fix in staging)
- Computer disconnects from cluster -> data loss (https://github.com/ITISFoundation/osparc-simcore/pull/3239)
- Reset of director-v2 service after manual intervention
- Multi-container services sometimes fail to start after being stuck (iSeg, sim4life)
- Study lock remains after manual intervention
- Add e2e test to simulate open/close of large study (https://github.com/ITISFoundation/osparc-simcore/issues/3168)

### Open
- Allow user to trigger a manual save of a service (stop/save/restart service)
- Allow user to start/stop a service to save resources
- Allow user to restart and/or reset a service
- Display service last save timestamp and data size

**Comment by GitHK** [comment]
## Update on sprint [Vaporwave](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221007_Vaporwave.md)

### Done

- Avoid failures when opening services:
  - https://github.com/ITISFoundation/osparc-simcore/pull/3297
  - https://github.com/ITISFoundation/osparc-simcore/issues/3293

- Automatic cleanup after errors, reduces support interventions
  - https://github.com/ITISFoundation/osparc-simcore/pull/3272
  - https://github.com/ITISFoundation/osparc-simcore/issues/3266
  - https://github.com/ITISFoundation/osparc-simcore/issues/3219
  - https://github.com/ITISFoundation/osparc-simcore/issues/3241

- Allows to backup data in extreme situations to avoid data loss
  - https://github.com/ITISFoundation/osparc-simcore/pull/3302
  - https://github.com/ITISFoundation/osparc-simcore/issues/3116

- Allows time for autoscaling create more nodes when resources are not available https://github.com/ITISFoundation/osparc-simcore/pull/3382
- Easier debugging of isseus with S3 transfers https://github.com/ITISFoundation/osparc-simcore/pull/3409

- Solved by multiple previous changes https://github.com/ITISFoundation/osparc-issues/issues/585

### Ongoing

- Required after https://github.com/ITISFoundation/osparc-simcore/pull/3302
  - Automatic backup of data in case of failuires https://github.com/ITISFoundation/dy-volumes-cleanup/pull/1
    - https://github.com/ITISFoundation/osparc-simcore/issues/3407

  - Adding tooling for support to avoid errors and reduce time in case of issues  https://github.com/ITISFoundation/osparc-simcore/issues/3406

- Rare S3 transfer error (investigation in progress) https://github.com/ITISFoundation/osparc-simcore/issues/3402

- The "save button" feature will bring some benefits, refactioring is onging to enable it
  - https://github.com/ITISFoundation/osparc-issues/issues/594
  - https://github.com/ITISFoundation/osparc-issues/issues/631
  - https://github.com/ITISFoundation/osparc-issues/issues/630
  - https://github.com/ITISFoundation/osparc-simcore/issues/3322

### Open

- https://github.com/ITISFoundation/osparc-simcore/issues/3145
- https://github.com/ITISFoundation/osparc-issues/issues/719
- https://github.com/ITISFoundation/osparc-simcore/issues/3385
- https://github.com/ITISFoundation/osparc-simcore/issues/3390
- https://github.com/ITISFoundation/osparc-simcore/issues/3413
- https://github.com/ITISFoundation/osparc-issues/issues/730
- https://github.com/ITISFoundation/osparc-simcore/issues/3229

**Comment by sanderegg** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- https://github.com/ITISFoundation/osparc-issues/issues/594
- refactoring dy-volume remover service into osparc-simcore (@GitHK please add links thanks)

**Comment by GitHK** [comment]
## Update on sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221114_KatherineSwitzer.md)

### Done

- Moved automatic backup of leftover data in case of failures to simcore (follow up to https://github.com/ITISFoundation/dy-volumes-cleanup/pull/1)
  - https://github.com/ITISFoundation/osparc-simcore/pull/3465 
  - https://github.com/ITISFoundation/osparc-simcore/issues/3445

- Services suddenly closing did not save their state (users were reporting loosing data)
  - https://github.com/ITISFoundation/osparc-simcore/pull/3438
  - https://github.com/ITISFoundation/osparc-simcore/issues/3413

- More reliable study closing (helps studies with lots of data per service) 
  - https://github.com/ITISFoundation/osparc-simcore/pull/3448
  - https://github.com/ITISFoundation/osparc-simcore/issues/3402

- Less data transfers when starting services
  - https://github.com/ITISFoundation/osparc-simcore/pull/3443
  - https://github.com/ITISFoundation/osparc-issues/issues/730

- **Security**: users can no longer start docker-containers via dy-sidecar
  - https://github.com/ITISFoundation/osparc-simcore/pull/3467
  - https://github.com/ITISFoundation/osparc-simcore/issues/3390

- Tooling for graceful close and clenup of service after failure to close
  - https://github.com/ITISFoundation/osparc-simcore/issues/3406
  - https://github.com/ITISFoundation/osparc-simcore/pull/3430

- Fixes and improvements to service shutdown cleanup https://github.com/ITISFoundation/osparc-simcore/pull/3431

### Ongoing

Refactored how directory outputs are handled (only upload changed port and not all output ports if one of them changes)
  - https://github.com/ITISFoundation/osparc-simcore/issues/3461
  - https://github.com/ITISFoundation/osparc-simcore/pull/3476


Automatic backup of leftover data in case of failures 
  - https://github.com/ITISFoundation/osparc-simcore/pull/3513
  - https://github.com/ITISFoundation/osparc-simcore/issues/3407

The "save button" feature (has a separate case now https://github.com/ITISFoundation/osparc-issues/issues/594)
  - https://github.com/ITISFoundation/osparc-issues/issues/594
  - https://github.com/ITISFoundation/osparc-issues/issues/631
  - https://github.com/ITISFoundation/osparc-issues/issues/630

### Open

- Higher priority
  - https://github.com/ITISFoundation/osparc-simcore/issues/3478
  - https://github.com/ITISFoundation/osparc-simcore/issues/3336

- https://github.com/ITISFoundation/osparc-simcore/issues/3145
- https://github.com/ITISFoundation/osparc-issues/issues/719
- https://github.com/ITISFoundation/osparc-simcore/issues/3385
- https://github.com/ITISFoundation/osparc-simcore/issues/3229
- https://github.com/ITISFoundation/osparc-simcore/issues/3322

**Comment by pcrespov** [comment]
@GitHK If you have nothing against I have left this "main" issue.

**Comment by GitHK** [comment]
## Goal for sprint [Athena](https://github.com/ITISFoundation/osparc-issues/milestone/36)

- https://github.com/ITISFoundation/osparc-simcore/issues/3461
- https://github.com/ITISFoundation/osparc-simcore/issues/3519
- https://github.com/ITISFoundation/osparc-simcore/issues/3478
- https://github.com/ITISFoundation/osparc-simcore/issues/3437
- https://github.com/ITISFoundation/osparc-simcore/issues/3336
- https://github.com/ITISFoundation/osparc-simcore/issues/3505

**Comment by GitHK** [comment]
## Update on sprint [Athena](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221202_Athena.md)

### Done

- https://github.com/ITISFoundation/osparc-simcore/pull/3594
- https://github.com/ITISFoundation/osparc-issues/issues/709

Helps with start & stop stability. Address e2e detected issues.
- https://github.com/ITISFoundation/osparc-simcore/pull/3583
  - https://github.com/ITISFoundation/osparc-simcore/issues/3478
- https://github.com/ITISFoundation/osparc-simcore/pull/3586
- https://github.com/ITISFoundation/osparc-simcore/pull/3589

### Ongoing
- https://github.com/ITISFoundation/osparc-simcore/pull/3610
- https://github.com/ITISFoundation/osparc-simcore/pull/3476
  - https://github.com/ITISFoundation/osparc-simcore/issues/3461

### Open
- https://github.com/ITISFoundation/osparc-simcore/issues/3519
- https://github.com/ITISFoundation/osparc-simcore/issues/3437
- https://github.com/ITISFoundation/osparc-simcore/issues/3336
- https://github.com/ITISFoundation/osparc-simcore/issues/3505

**Comment by GitHK** [comment]
## Pre-planning sprint Zefram Cochrane


- cancellable observation cycle (make life more simple for who is stopping services that were just started)
- 400 BadRequest (RequestTimeout) issue
- #3579
- #3567
- #3505
- #3385

**Comment by GitHK** [comment]
## Update on sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230111_ZeframCochrane.md)

### Done
- https://github.com/ITISFoundation/osparc-simcore/pull/3610
- https://github.com/ITISFoundation/osparc-simcore/pull/3476
- https://github.com/ITISFoundation/osparc-simcore/pull/3737
- https://github.com/ITISFoundation/osparc-simcore/pull/3666

more flexible dynamic scheduler (allows to solve some impactful bugs)
- https://github.com/ITISFoundation/osparc-simcore/pull/3698
- https://github.com/ITISFoundation/osparc-simcore/pull/3699
- https://github.com/ITISFoundation/osparc-simcore/pull/3708

### Ongoing

- https://github.com/ITISFoundation/osparc-simcore/pull/3724

### Open
For a detailed analysis https://github.com/ITISFoundation/osparc-issues/issues/638#issuecomment-1337503076

**Comment by GitHK** [comment]
## Planned for sprint XXXXX

Legend:
- :rotating_light: milestone end of January 2023
- :construction_worker: helps with maintenance
- :lock: security concern


### Stability

- [400 BadRequest (RequestTimeout) issue](https://github.com/ITISFoundation/osparc-simcore/issues/3531)
  - :rotating_light: very important, huge time waster, no idea how to debug currently, requires AWS
- https://github.com/ITISFoundation/osparc-simcore/issues/3385
  - :rotating_light: very important to pickup ongoing tasks, might create issues with already running containers
- https://github.com/ITISFoundation/osparc-simcore/issues/3581
  - :construction_worker:  could be considered as closed, requires checking
- can be handled together, impacts the same system
  - https://github.com/ITISFoundation/osparc-simcore/issues/3567
    - :construction_worker: pretty big deal, when a dy-service is deleted, it is no longer possible to remove it (creates extra maintenance interventions)
    - related to https://github.com/ITISFoundation/osparc-simcore/issues/3493
  - https://github.com/ITISFoundation/osparc-simcore/issues/3604
    - :construction_worker: would like this fixed, since it causes strange issues, unfortunately might be a big case
  - https://github.com/ITISFoundation/osparc-simcore/issues/3322
    - :construction_worker: cancellable observation cycle (make life more simple for who is stopping services that were just started)
  - https://github.com/ITISFoundation/osparc-simcore/issues/3714
    - :construction_worker: allows to deal with pending forever services or in states that are not what is desired
- https://github.com/ITISFoundation/osparc-simcore/issues/3437
  - proper limitation of services, might be required for :rotating_light:
  - also related https://github.com/ITISFoundation/osparc-simcore/issues/3505
  - also related to https://github.com/ITISFoundation/osparc-issues/issues/739
- https://github.com/ITISFoundation/osparc-simcore/issues/3736
  - blocks correctly saving the state (impacts closing the services)
- https://github.com/ITISFoundation/osparc-simcore/issues/3749
  - :construction_worker: generates a lot of pending services, a pain for maintenance and users will see their studies locked 
  - 
### :rotating_light: Required for end of January 2023

- https://github.com/ITISFoundation/osparc-simcore/issues/3565
  - required for :rotating_light:
- https://github.com/ITISFoundation/osparc-simcore/issues/3664
- https://github.com/ITISFoundation/osparc-issues/issues/597
  - unsure if this is still required for :rotating_light:
  - might be related with above
- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/1920
  - this might require some thinking, unsure if required for :rotating_light:
  - required for global preferences (see issues above)


### Security

- https://github.com/ITISFoundation/osparc-simcore/pull/3606
  - :rotating_light: needs to be finished, to allow license to work and block internet access
- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/3506
  - :lock: security concern

### Important request

- https://github.com/ITISFoundation/osparc-simcore/issues/3336
  - requested since 3 sprints ago


### Enhancements

- https://github.com/ITISFoundation/osparc-simcore/issues/3446
  - more faster reliable removal of services (will be a bit time intensive)
  - also related to this https://github.com/ITISFoundation/osparc-simcore/issues/3602
  - once one of the issues is fix the other is easily fixable
  - once refactored this can be closed https://github.com/ITISFoundation/osparc-issues/issues/763
- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/3601
  - :construction_worker: currently if something goes wrong with a long running task we don't know what happened from the error traceback, this is pretty bad, making errors reproducibility almost impossible
- https://github.com/ITISFoundation/osparc-simcore/issues/3582
  - good to have, to avoid confusion between stacks when debugging
- https://github.com/ITISFoundation/osparc-simcore/issues/3570
  - simple, no current benefit
- https://github.com/ITISFoundation/osparc-simcore/issues/3357
  - confusing for users
- https://github.com/ITISFoundation/osparc-simcore/issues/3194
  - better error reporting
- https://github.com/ITISFoundation/osparc-simcore/issues/3108
  - refactor
- https://github.com/ITISFoundation/osparc-simcore/issues/2839
  - might be important when copying study from one deployment to anther on the same machine (dalco)
- https://github.com/ITISFoundation/osparc-simcore/issues/2774
  - refactor, estetic

### Bugs

- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/3407
  - requires followup to properly finish with the agent, might just be closed like this, need to check with OPS
- https://github.com/ITISFoundation/osparc-simcore/issues/2613
  - this is still an issue, remove files from outputs never get deleted in s3
- https://github.com/ITISFoundation/osparc-simcore/issues/2658
  - check if still an issue, only affects 1 service (maybe)

**Comment by GitHK** [comment]
## Update on sprint [Resistance Is Futile](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230220_ResistanceIsFutile.md)

### Done

- https://github.com/ITISFoundation/osparc-simcore/issues/3531
- https://github.com/ITISFoundation/osparc-simcore/issues/3567
- https://github.com/ITISFoundation/osparc-simcore/issues/3604
- https://github.com/ITISFoundation/osparc-simcore/issues/3322
- https://github.com/ITISFoundation/osparc-simcore/issues/3714
- https://github.com/ITISFoundation/osparc-simcore/issues/3736
- https://github.com/ITISFoundation/osparc-simcore/issues/3749
- https://github.com/ITISFoundation/osparc-simcore/pull/3606
- https://github.com/ITISFoundation/osparc-simcore/pull/3766
- https://github.com/ITISFoundation/osparc-simcore/pull/3771
- https://github.com/ITISFoundation/osparc-simcore/issues/3794
- https://github.com/ITISFoundation/osparc-simcore/issues/3793
- https://github.com/ITISFoundation/osparc-simcore/pull/3798
- https://github.com/ITISFoundation/osparc-simcore/pull/3795
- https://github.com/ITISFoundation/osparc-simcore/pull/3833
- https://github.com/ITISFoundation/osparc-simcore/pull/3859
- https://github.com/ITISFoundation/osparc-simcore/pull/3878
- https://github.com/ITISFoundation/osparc-simcore/pull/3880

### Ongoing
- https://github.com/ITISFoundation/osparc-simcore/pull/3888
- https://github.com/ITISFoundation/osparc-simcore/pull/3812

**Comment by GitHK** [comment]
- Removing a node while the study is unlocked causes the sidecar to fail. This is done by the e2e and happens on all deployments https://github.com/ITISFoundation/osparc-simcore/issues/3898

**Comment by GitHK** [comment]
## Planned for sprint Resistance is Mithril

Legend:
- :rotating_light: milestone end of January 2023
- :construction_worker: helps with maintenance
- :lock: security concern


### Stability

- [400 BadRequest (RequestTimeout) issue](https://github.com/ITISFoundation/osparc-simcore/issues/3531)
  - :rotating_light: very important, huge time waster, no idea how to debug currently, requires AWS
- https://github.com/ITISFoundation/osparc-simcore/issues/3385
  - :rotating_light: very important to pickup ongoing tasks, might create issues with already running containers
- https://github.com/ITISFoundation/osparc-simcore/issues/3437
  - proper limitation of services, might be required for :rotating_light:
  - also related https://github.com/ITISFoundation/osparc-simcore/issues/3505
  - also related to https://github.com/ITISFoundation/osparc-issues/issues/739

### :rotating_light: Required for end of January 2023

- https://github.com/ITISFoundation/osparc-simcore/issues/3565
  - required for :rotating_light:
- https://github.com/ITISFoundation/osparc-simcore/issues/3664
- https://github.com/ITISFoundation/osparc-issues/issues/597
  - unsure if this is still required for :rotating_light:
  - might be related with above
- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/1920
  - this might require some thinking, unsure if required for :rotating_light:
  - required for global preferences (see issues above)


### Security


- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/3506
  - :lock: security concern

### Enhancements

- https://github.com/ITISFoundation/osparc-simcore/issues/3446
  - more faster reliable removal of services (will be a bit time intensive)
  - once one of the issues is fix the other is easily fixable
  - once refactored this can be closed https://github.com/ITISFoundation/osparc-issues/issues/763
- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/3357
  - confusing for users
- https://github.com/ITISFoundation/osparc-simcore/issues/3194
  - better error reporting
- https://github.com/ITISFoundation/osparc-simcore/issues/3108
  - refactor
- https://github.com/ITISFoundation/osparc-simcore/issues/2839
  - might be important when copying study from one deployment to anther on the same machine (dalco)
- https://github.com/ITISFoundation/osparc-simcore/issues/2774
  - refactor, estetic

### Bugs

- `below are way less important`
- https://github.com/ITISFoundation/osparc-simcore/issues/3407
  - requires followup to properly finish with the agent, might just be closed like this, need to check with OPS
- https://github.com/ITISFoundation/osparc-simcore/issues/2613
  - this is still an issue, remove files from outputs never get deleted in s3
- https://github.com/ITISFoundation/osparc-simcore/issues/2658
  - check if still an issue, only affects 1 service (maybe)

**Comment by GitHK** [comment]
## Update on sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)


### Done
- https://github.com/ITISFoundation/osparc-simcore/issues/3898
- https://github.com/ITISFoundation/osparc-simcore/issues/3385
- https://github.com/ITISFoundation/osparc-simcore/issues/3407
- https://github.com/ITISFoundation/osparc-simcore/issues/2658
- https://github.com/ITISFoundation/osparc-simcore/issues/3863
- https://github.com/ITISFoundation/osparc-simcore/pull/3942

### Ongoing
- https://github.com/ITISFoundation/osparc-simcore/issues/3446
  - https://github.com/ITISFoundation/osparc-issues/issues/763
  - https://github.com/ITISFoundation/osparc-simcore/issues/3890
  - https://github.com/ITISFoundation/osparc-simcore/pull/3909
  - https://github.com/ITISFoundation/osparc-simcore/pull/3974
  - https://github.com/ITISFoundation/osparc-simcore/pull/3941
- https://github.com/ITISFoundation/osparc-simcore/issues/3944
  - https://github.com/ITISFoundation/osparc-simcore/pull/3947
- https://github.com/ITISFoundation/osparc-simcore/issues/4035
  - https://github.com/ITISFoundation/osparc-simcore/pull/4040

### New
- https://github.com/ITISFoundation/osparc-simcore/issues/3950
- https://github.com/ITISFoundation/osparc-simcore/issues/4034

**Comment by sanderegg** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)
- issue with start a jupyter-smash and go to dashboard unclear (lock seems to unlock too fast? service stopping when re-opening?)
- https://github.com/ITISFoundation/osparc-issues/issues/836 , https://github.com/ITISFoundation/osparc-simcore/issues/3726, https://github.com/ITISFoundation/osparc-simcore/issues/4034, we need a serious analysis here
- clean all the logs in director-v2 about the sidecar, it is unreadable at the moment, and makes devops nervous
- https://github.com/ITISFoundation/osparc-simcore/issues/3944
- https://github.com/ITISFoundation/osparc-simcore/issues/3950
- https://github.com/ITISFoundation/osparc-simcore/issues/3446, please also analysis the auto-scaled case.
- TB continued

**Comment by sanderegg** [comment]
hanging sidecars?

**Comment by GitHK** [comment]
## Update on sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)

### Done
- https://github.com/ITISFoundation/osparc-simcore/issues/3944
- https://github.com/ITISFoundation/osparc-simcore/issues/3950

### Onging
- https://github.com/ITISFoundation/osparc-simcore/issues/3446
  - depends on:
    - https://github.com/ITISFoundation/osparc-simcore/pull/3941
    - https://github.com/ITISFoundation/osparc-simcore/pull/3974
      - reverted by https://github.com/ITISFoundation/osparc-simcore/pull/4139
    - https://github.com/ITISFoundation/osparc-simcore/pull/4055
  - is blocking:
    - https://github.com/ITISFoundation/osparc-simcore/issues/4084 (requires https://github.com/ITISFoundation/osparc-simcore/pull/3941)
    - https://github.com/ITISFoundation/osparc-simcore/issues/4044 (required code was reverted from https://github.com/ITISFoundation/osparc-simcore/pull/3974)
  - ANE working on new solution to unlock these cases
- https://github.com/ITISFoundation/osparc-simcore/issues/4167
### TODO

- Need to decide Usability vs Platform stability when counting the max number of dynamic services https://github.com/ITISFoundation/osparc-issues/issues/836 https://github.com/ITISFoundation/osparc-simcore/issues/3726 https://github.com/ITISFoundation/osparc-simcore/issues/4034
  - fixed issues with counting services https://github.com/ITISFoundation/osparc-simcore/pull/4055

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...

**Comment by GitHK** [comment]
## Update on sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)

Done: 
- https://github.com/ITISFoundation/osparc-simcore/pull/4207
- https://github.com/ITISFoundation/osparc-simcore/pull/4225
- https://github.com/ITISFoundation/osparc-simcore/pull/4249
- https://github.com/ITISFoundation/osparc-simcore/pull/3812

Ongoing:
- https://github.com/ITISFoundation/osparc-simcore/pull/4267
- https://github.com/ITISFoundation/osparc-simcore/pull/4291

**Comment by GitHK** [comment]
# Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)

no progress

**Comment by GitHK** [comment]
# Update [Sundae](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230814_Sundae.md)
Done:
- https://github.com/ITISFoundation/osparc-simcore/pull/4485
- https://github.com/ITISFoundation/osparc-simcore/pull/4505
- https://github.com/ITISFoundation/osparc-simcore/pull/4545
- https://github.com/ITISFoundation/osparc-simcore/pull/4551

New issues:
- https://github.com/ITISFoundation/osparc-simcore/issues/4595
