### ISSUE TITLE
Save a study when logging off

### ISSUE THREAD

**Issue by cosfor1** [ITISFoundation/osparc-issues#641]
When logging off from the application, it would be nice to have the same dialog as in the case of switching to the dashboard, asking the user to save and close.
Thank you

**Comment by odeimaiz** [comment]
@sanderegg Is the study closed when the frontend calls the /logout endpoint? It doesn't explicitly call the :close one.

**Comment by sanderegg** [comment]
@odeimaiz so what happens in the backend is the following:
- user logsout
- backend logs out the user from any open tab/other web browser
- removes the entry in redis
- then the project is closed after 15 minutes if the user does not log-in again

**Comment by odeimaiz** [comment]
OK, since the study is not Closed&Saved right away, I'll close this issue
