### ISSUE TITLE
Cannot see Pennsieve data files

### ISSUE THREAD

**Issue by bvhpatel** [ITISFoundation/osparc-issues#644]
**Long Story Short**
 I don't see the Pennsieve option in my Storage although I am connected to Pennsieve.

**Expected Behavior**
I expect to see Pennsieve listed in my Storage and be able to select a data file from Pennsieve. 

**Actual behaviour**
I don't see the Pennsieve option in my Storage.

**Steps to reproduce**
After connecting osparc with Pennsieve, open an existing study and click on the Storage option. There should be Pennsieve listed besides "simcore.s3" but it is not.

**Environment**
Chrome Version 102.0.5005.115 (Official Build) (64-bit)

**Additional context**
This is happening since about 5 days ago. There was no issue before that.

![osparc-pennsieve](https://user-images.githubusercontent.com/8172375/175743790-6c6420ef-3518-4d44-a244-d2cf0f63bdff.PNG)

**Comment by elisabettai** [comment]
Hi @bvhpatel, thanks for reporting this.
We're refactoring our storage and after that we can try to reproduce the issue.

In the meantime, regenerating the API key/token should solve the problem.

**Comment by sanderegg** [comment]
It seems that we have an issue with our pennsieve integration when listing data inside very large datasets such as:
![image](https://user-images.githubusercontent.com/35365065/194277593-2e27fcd5-817f-4d18-ad37-04fe84b43af2.png)

current workaround is to restart the pennsieve integration in the backend. then it works again. This will need some further analysis though.

**Comment by sanderegg** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- Fix the issue
