### ISSUE TITLE
Logger: different colors for type of messages (e.g. red for Errors)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#649]
It would be helpful if the Logger would show messages in different colors so that the user can more easily find important stuff.
E.g. red for errors/Exceptions. 
I tried making a sleeper fail: all the messages are white.

**Comment by odeimaiz** [comment]
related to https://github.com/ITISFoundation/osparc-issues/issues/762

**Comment by odeimaiz** [comment]
It was already in place in the frontend, https://github.com/ITISFoundation/osparc-simcore/pull/4232 closes it.
