### ISSUE TITLE
Logger: Error doesn't filter errors

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#650]
If I make a sleeper fail and then I filter the logger messages by "Error" no message is left in the logger.
I would expect to see only the error message from the sleeper.

**Comment by odeimaiz** [comment]
related to https://github.com/ITISFoundation/osparc-issues/issues/762

**Comment by odeimaiz** [comment]
It was already in place in the frontend, https://github.com/ITISFoundation/osparc-simcore/pull/4232 closes it.
