### ISSUE TITLE
Trial account

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#677]
Add expiration date to trial accounts and a mechanism to extend it

related to https://github.com/ITISFoundation/osparc-issues/issues/670

**Comment by sanderegg** [comment]
- add expiration date in confirmation table
- add expiration date in users table
- pass that info to the frontend (/me)
- background task that checks expiration on a daily basis -> set the user as EXPIRED/BANNED
- if the user is connected, log him/her out forcefully
