### ISSUE TITLE
M1-12 Support MAP-Core for simulations on the Portal

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#681]
Launch simulations from the Portal (in support of the leading MAP-Core):
Create a Schema and API that exposes metadata describing the input and output ports of computational studies and enables MAP-Core to automatically generate a Portal GUI for configuring and launching computational studies, and recovering results. This functionality shall not be limited to CellML models.

Deliverable: o²S²PARC API functionality & port meta-data required for MAP-Core to implement the Portal-based simulation configuration and launching + timely documentation of API.

Deadline: Month 4
[Wrike M2.1.3](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=916233806&pid=916190536&cid=720993193)

Related MAP-Core milestone:  ﻿[M4.4 SIM API support](https://www.wrike.com/open.htm?id=904558666).

**Comment by elisabettai** [comment]
@pcrespov, I guess this is continuation of the work you have been doing in support MAP-Core.

**Comment by elisabettai** [comment]
Hi @pcrespov, as far as I understand this is completed, right? Could you also check the linked Wrike ticket in the description to see if there's something missing?

**Comment by pcrespov** [comment]
@elisabettai no, this is not completed yet. As you add above, this is a continuation of the work we have been doing with MAP-Core. The idea is around extending osparc API to expose json-schemas of solvers input/outputs

**Comment by elisabettai** [comment]
Thanks for the clarification @pcrespov. I've then added this to related Epic (together with some other tickets that were not linked yet there). Let me know if something there is not clear.

**Comment by pcrespov** [comment]
## Goal for sprint [Athena](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221209_Athena.md)

- https://github.com/ITISFoundation/osparc-issues/issues/769
- report outcome of API with MAP-Core

## Review demo

 - report outcome from cMIS?

**Comment by pcrespov** [comment]
## Update on sprint [Athena](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221202_Athena.md)

### Ongoing
  - report outcome of API with MAP-Core next week (for his Quarterly report) 

### Open
   - https://github.com/ITISFoundation/osparc-issues/issues/769

**Comment by pcrespov** [comment]
## Update on sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230111_ZeframCochrane.md)

### Ongoing
  - Periodic report outcome of API with MAP-Core (next meeting on Wed. Jan11)
      - studies ports API

### Done
   - https://github.com/ITISFoundation/osparc-issues/issues/769

**Comment by pcrespov** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)

- https://github.com/ITISFoundation/osparc-issues/issues/769
- report outcome of API with MAP-Core (for his Quarterly report)

**Comment by pcrespov** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)

- https://github.com/ITISFoundation/osparc-issues/issues/769 @elisabettai 
- report outcome of API with MAP-Core (for his Quarterly report) @pcrespov

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)

- report outcome of API with MAP-Core (for his Quarterly report) @pcrespov

**Comment by elisabettai** [comment]
## Update for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230602_PastelDeNata.md)
  - Three of our datasets on the SPARC Portal have been updated and support launching an oSPARC study or using the MAP-Core Simulation viewer. These datasets can be accessed here:
  https://sparc.science/datasets/308?type=simulation (Multi-scale human cardiac electrophysiology models)
        https://sparc.science/datasets/318?type=simulation (Multi-scale rabbit cardiac electrophysiology models)
        https://sparc.science/datasets/320?type=simulation (Kember Cardiac Nerve Model)
  
cc @pcrespov

**Comment by elisabettai** [comment]
@pcrespov, I changed the name of this milestone to M1-12... to it's clear that is ongoing.
I put as deadline mid of August, when I assume you'll sync with MAP ahead of the quarterly reports.

**Comment by pcrespov** [comment]
## Update Baklava

- Meeting between @pcrespov and Alan on Tuesday Aug. 22 for Q4 report.
