### ISSUE TITLE
M2 Access to log after job was run (via API)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#687]
Deliverable: Provide access to logs after job was run 
Deadline: Month 2

----
[Wrike M4.1.5](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=921193030&pid=916192005&cid=720993193)

More context from [Wrike parent case](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=916303146):
Extend existing APIs (computational API, study creation and access, platform API), add new APIs (progress API, import/export API) as required by users and in support of the DRC APIs, exposing: 

- queuering of service & study input/output port descriptions
- search for compatible services to a data item (initially based on mime-type, potentially later extensible based on file-level meta-data annotation)
-  launching of computational study with given input parameters / data; initially focusing on similar use-cases as the Portal-launched simulations
- **Access to logs after job was run** 
- API for import/export of data
- Instantiation of a study that contains a file import service that already points to the given data-item and an attached visualization/analysis/processing user-requested service (user-login dependant)
- The above functionality accepting data and input will support data pointers from the DRC API

Deliverable: The above described o²S²PARC / DRC API (and Python client) functionality

TODO for EI/EN: verify that all the above is still relevant

**Comment by elisabettai** [comment]
Related to #668

**Comment by elisabettai** [comment]
Hi @pcrespov. Any chance that this was already done? I.e. is it possible to download the logs when a job (study) is run via the API?

**Comment by pcrespov** [comment]
> Hi @pcrespov. Any chance that this was already done? I.e. is it possible to download the logs when a job (study) is run via the API? I remember seeing something related, but I couldn't remember exactly.

@elisabettai  it is **almost** there. It is in a branch and can be used (SEE https://github.com/ITISFoundation/osparc-simcore-python-client/pull/27 )... but still needs to be officially released and for that i need to update a couple of things before.

**Comment by pcrespov** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- Release https://github.com/ITISFoundation/osparc-simcore-python-client/tree/v0.5.0 as ``osparc 0.5.0``
- Ensure tested

**Comment by pcrespov** [comment]
## Update on sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221114_KatherineSwitzer.md)

### Done
- Released``osparc 0.5.0``: [pypi](https://pypi.org/project/osparc/0.5.0/), [release changelog](https://github.com/ITISFoundation/osparc-simcore-python-client/releases/tag/v0.5.0)
- Demo tutorial -> [BasicTutorial](https://itisfoundation.github.io/osparc-simcore-python-client/#/md/tutorials/BasicTutorial)
