### ISSUE TITLE
M3 Additional o²S²PARC Metrics

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#688]
Deliverable: Update the DRC metrics document with the new metrics that SIM-Core plans to collect. The NIH has asked for metrics on most used services, computational resource usage, issue and resolution metrics, statistics on frequent bugs/support issues. Corresponding metrics will be established and reported on.
Deadline: Y6Q1

Related DAT-Core milestones:
﻿[Milestone 4.5.1 Q1 Metrics Report](https://www.wrike.com/open.htm?id=920698388)

[Wrike M9.2](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=922009340&pid=916384856&cid=720993193)

More details on the metrics in [DRC Metrics doc](https://docs.google.com/document/d/1LWHWcC7fIf7woUgTm1J37TbsMqS7gdhyCchz_h4l0F4/edit#heading=h.nwzkeykt8nqr) (link points already to the list relevant for o²S²PARC)

**Comment by sanderegg** [comment]
- review if new metrics are same as old ones (described year 2 or 3 of oSparc)
- go through Katie's process on generating the metrics
- review the dashboard generated on grafana

**Comment by elisabettai** [comment]
I've checked in the [DRC Metrics doc](https://docs.google.com/document/d/1LWHWcC7fIf7woUgTm1J37TbsMqS7gdhyCchz_h4l0F4/edit#heading=h.nwzkeykt8nqr) and there are no surprises in terms of metrics.
There are only two things missing, but we should be able to manually get them from the Portal ("organs with simulations" and "number of publications per dataset")

**Comment by elisabettai** [comment]
"go through Katie's process on generating the metrics":
reviewed everything. 

As a rule-of-thumb to filter puppetters, we have this: https://git.speag.com/oSparc/osparc-metrics/-/blob/master/FilterPuppets.md
If we continue with this manual way, we need to update the numbers for the e2e and p2e tests.

**Comment by elisabettai** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- Review all the metrics (grafana/prometeus) and prepare for the report.
### Still open:
ITISFoundation/osparc-simcore#2831
ITISFoundation/osparc-simcore#3336
ITISFoundation/osparc-simcore#3472
#727 
### Fixed:
ITISFoundation/osparc-simcore#3412. We can now filter puppeteers in the webserver metrics. Need release to prod
ITISFoundation/osparc-simcore#2840

**Comment by elisabettai** [comment]
I'm re-opening this.
There is a bug that needs to be fixed soon: https://github.com/ITISFoundation/osparc-simcore/issues/3907
A feature request (filtering puppeteers from service usage metrics): https://github.com/ITISFoundation/osparc-simcore/issues/3908
