### ISSUE TITLE
M6 Search compatible service to data

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#689]
exposing search for compatible services to a data item (initially based on mime-type, potentially later extensible based on file-level meta-data annotation)

Deadline: Month 6

[Wrike M4.1.2](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=921190413&pid=916192005&cid=720993193)

**Comment by elisabettai** [comment]
@pcrespov, I'm re-opening this since https://github.com/ITISFoundation/osparc-simcore/pull/3984 partially resolves this one. The keywork "resolves" closed this one automatically, I assume this was not intentional, let me know if I'm misunderstanding.

**Comment by pcrespov** [comment]
## Update for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230324_Mithril.md)

- Completed with a different design variation
- See PR references above for details
