### ISSUE TITLE
M10 API for import and export of data

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#690]
Deliverable: Provide API for import/export of data 
Deadline: Month 10

[Wrike M4.1.6](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=921194180&pid=916192005&cid=720993193)

This is part of [Comprehensive o²S²PARC API & DRC API integration](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=916303146)

**Comment by elisabettai** [comment]
@pcrespov, have you had some time to think about which part of the API covers import/export of data? I imagine what done as part of #682 should cover it, but I'm sure you have more about this.

**Comment by elisabettai** [comment]
@pcrespov, I'd like to help here, since we might already functionality that cover this.
In the BasicTutorial, [here](https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial?id=files) I see API calls to upload and download data.

Doesn't this cover "Provide API for import/export of data"?

**Comment by pcrespov** [comment]
> @pcrespov, I'd like to help here, since we might already functionality that cover this. In the BasicTutorial, [here](https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial?id=files) I see API calls to upload and download data.
> 
> Doesn't this cover "Provide API for import/export of data"?

@elisabettai that is definitively import/export of data but I am not 100% sure whether it covers the original ticket. I let you to decide.

**Comment by elisabettai** [comment]
This is what we wrote in the reporting that should close this issues 

> The o2S2PARC API (o2S2PARC Python Client version 0.5.0) supports the upload of data (files) to computational services and the download of data from the services outputs. This feature is documented on the o2S2PARC Python Client Tutorial (see [here](https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial?id=files)). In addition, the server side was extended to expose entry-points to import data from the SPARC Portal (any file type) as part of [Y6-M2.1.6: Pulling Files from the Portal](https://www.wrike.com/open.htm?id=916241916)
