### ISSUE TITLE
M10 Accept Pointers from DRC API

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#692]
Deliverable: The functionality #691 accepting data and input will support data pointers from the DRC API

Deadline: Month 10

[Wrike 4.1.8](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=921196439&pid=916192005&cid=720993193)

**Comment by bisgaard-itis** [comment]
As discussed offline with @elisabettai this one is considered done

**Comment by elisabettai** [comment]
This is what we wrote in the reporting that should close the issue:

> Implementation: The API functionality for Import/Export of data that allows uploading/downloading programmatically data to/from computational services on o2S2PARC (see [Y6-M4.1.6: API for Import/Export of Data](https://www.wrike.com/open.htm?id=921194180)) can also now accept data from the SPARC Python Client, for example using the Pennsieve service within the SPARC Python Client. With the integration of the o2S2PARC Python Client in the SPARC Python Client (see [Y6-T4.1: Develop SPARC Python Library](https://www.wrike.com/open.htm?id=916295864)), investigators can seamlessly download data (e.g. with the DAT-Core part of the client) and use them in o2S2PARC.

fyi @pcrespov
