### ISSUE TITLE
M8 Attribute (& Charge) Resource Usage

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#697]
In the future, it will be necessary for sustainability purposes **to attribute (and charge) resource usage** costs to commercial users, users exceeding the limits of the free usage tier, or whatever the adopted sustainability model foresees. Usage tracking and attribution functionality shall be developed that permits to attribute storage and computational resource costs to and preparation for cost attribution to paying users.

Deliverable: Functionality to track and attribute o²S²PARC resource usage
Deadline: Month 8

[Wrike M7.1.2](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=916369620&pid=916192754&cid=720993193)
```[tasklist]
### Tasks
```

```[tasklist]
### Watermelon
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/173
```

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...

**Comment by elisabettai** [comment]
From NIH June meeting: deadline is now Q4
![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/2a5b9c17-9807-4cf0-b29f-a2ee11d67900)

**Comment by elisabettai** [comment]
As discussed, we can close this once we're able to track resources from director-v2. This will enable tracking all services (and not only jupyter-smash). 

@matusdrobuliak66, please correct if this is wrong. I am following up progress for this in https://github.com/ITISFoundation/osparc-issues/issues/922.

**Comment by matusdrobuliak66** [comment]
> As discussed, we can close this once we're able to track resources from director-v2. This will enable tracking all services (and not only jupyter-smash).
> 
> @matusdrobuliak66, @mrnicegyu11 please correct if this is wrong. I am following up progress for this in #922, but I will need to figure out which tasks from there will close this one.

You are correct, basically, most of the tasks that are currently in the Sundae task list (all that are connected with RabbitMQ, publishing messages from director-v2, and receiving/storing messages somewhere in resource-usage-tracker) are needed to track the usage.

The question I have here is, what is the outcome/goal of this milestone? The outcome of the second one is to track the user credits based on which you are able to bill. What is the goal here, is it the same?

**Comment by matusdrobuliak66** [comment]
## Update [Baklava](https://github.com/ITISFoundation/osparc-issues/milestone/48)

Done:
 - Collecting and storing events/resources in the Database now from all running services (Computational & Dynamic)
![image](https://github.com/ITISFoundation/osparc-issues/assets/60785969/ec53810c-2df8-4302-8e4b-7264e0629770)
