### ISSUE TITLE
dy-sidecar: large projects that start to upload right away and sometimes fail

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#706]
Observed on several occasions:
https://monitoring.osparc.io/graylog/search?q=%22simcore_sdk.node_ports_common.exceptions.S3TransferError%3A+Could+not+upload+file%22+AND+NOT+container_name%3A%2F.%2Agraylog_graylog.%2A%2F&rangetype=relative&from=432000

Symptoms:
- large project is opened (Bladder Control)
- some nodes start downloading inputs right away (although they should be up to date?)
- some nodes start uploading outputs right away??? (why?) is that because the frontend called on retrieve?
- sometimes there is an error when uploading that completes with a 500 coming from AWS (this might need also some investigation as to why that happens?)

--> we need to get in control the retrieve call

**Comment by pcrespov** [comment]
We also noticed that it reaches up to 600+ retrials? SHould we perhaps limit this? Could this be stressing aws services? Is there any reason to reach that level or retrials?

**Comment by sanderegg** [comment]
> We also noticed that it reaches up to 600+ retrials? SHould we perhaps limit this? Could this be stressing aws services? Is there any reason to reach that level or retrials?

Hmm I think this was not retrials but multiple tasks (multipart uploads)

**Comment by mrnicegyu11** [comment]
Happened again today, error 500 from aws-S3

https://monitoring.osparc.io/graylog/messages/graylog_132/a8d43de3-3352-11ed-9520-0242ac120010

**Comment by elisabettai** [comment]
Regarding:
"some nodes start uploading outputs right away??? (why?) is that because the frontend called on retrieve?"

I've opened #730. Looks like the unwanted upload happens just after the container has changed ownership of the outputs folder.
