### ISSUE TITLE
dy-sidecar: iSeg/Sim4life sometimes fail to start

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#707]
When opening large projects, iSeg/Sim4life sometimes are still stuck

**Comment by elisabettai** [comment]
This still happens on master (with Bladder Control). I wrote a bit more in #718, see [this comment](https://github.com/ITISFoundation/osparc-issues/issues/718#issuecomment-1252109059).

**Comment by elisabettai** [comment]
Should have been fixed by: https://github.com/ITISFoundation/osparc-simcore/pull/3297
