### ISSUE TITLE
Service does not start

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#709]
Prep2Go: WM Conductivity state goes in error right on openining.

No dy-sidecar started, and there are PermissionDenied messages in the director-v2 to analyze:

https://monitoring.osparc.io/graylog/search?q=container_name%3A%2F.%2Adirector-v2.%2A%2F&rangetype=absolute&from=2022-09-13T12%3A26%3A09.371Z&to=2022-09-13T12%3A54%3A54.811Z

**Comment by elisabettai** [comment]
This was not reported anymore, so hopefully fixed as part of #638
