### ISSUE TITLE
App Mode buttons are a bit hidden

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#712]
The App Mode functionality should be easier to access (with a single click from inside a study), according to our PO @esraneufeld 

Right now you need to be in the workbench view and under 'home' to see it, maybe it can be moved on a part of the UI that is always displayed, e.g. on one of these horizontal bars on the top.

![image.png](https://images.zenhubusercontent.com/62a08d1da8b60c08113842b9/165824cb-9925-441f-b789-3470029c6e46)

**Comment by odeimaiz** [comment]
It's all about balancing between a neat UI and having the important features in hand.

We used to have it next to the collapse button on right. I'll bring it back.
