### ISSUE TITLE
Drag and drop data into workspace

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#714]
## Long story short
It would be amazing to be able to drag and drop data from the database tree directly into my notebook workspace. Since it is already possible to drag from the data tree to the workbench, I assume this would be possible. See screenshot attached.
![drag_and_drop](https://user-images.githubusercontent.com/70750341/190329248-183681f8-f683-49b1-bbfa-493e84a00088.jpg)

## Expected behaviour
Data is drag-and-drop-able from data tree to NB workspace. 

## Actual behaviour
Can't drag-and-drop data from data tree into NB workspace.

## Steps to reproduce
n/a

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "091e179",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/091e179/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "091e179",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/091e179/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "Plotly",
    "version": "2.9.0",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "RadialMenu",
    "version": "1.2.0",
    "url": "https://github.com/victorqribeiro/radialMenu"
  },
  {
    "name": "GitGraph",
    "version": "1.4.0",
    "url": "https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2167,
      "height": 1085
    }
  }
]
```

**Comment by mrnicegyu11** [comment]
@newton1985 :
Not sure if this is possible since this goes into the jupyter (i.e. ourside osparc), whose code we dont maintain.

Because of our conversation yesterday let me clarify: This is all happening in one tab, not "from one oSparc tab another", correct?

**Comment by newton1985** [comment]
@mrnicegyu11 - to clarify, yes, this is within a single tab (as in the image), not across multiple tabs.

Regarding whether or not it's possible - I would suppose that there should be a way to make it _appear_ as though data is being dragged and dropped into the NB, since I can 1) drag the data into the workbench, 2) connect it to the input port of the service, 3) copy that data into my workspace. I guess at the very least, this could be "wrapped" such that from the user point of view the middle steps are hidden?

**Comment by GitHK** [comment]
Not feasible. That feature of Jupyter-lab works via native file drag and drop. We cannot drop a link there and have it upload.

Closing.
