### ISSUE TITLE
Convert JupyterLabs to Python runners

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#720]
In order to run Prep2Go in app mode the following is necessary:
- convert jupyter labs into python runners

steps:
1. add 3 outputs to the current osparc-python-runner service --> version 1.3.0
2. change how inputs are mapped into inputs (currently is a flat directory, all inputs are unzipped in the same folder vs one subfolder per input port) -> needs change in osparc platform as well
3. this all needs to be ported to s4l-python-runners
4. needs of flavors with pytorch, etc...

Please @newton1985 extend if something is missing in the above

**Comment by elisabettai** [comment]
An alternative way was pursued: all the jupyter labs will be converted in voila mode and will have a Run button (made with ipywidgets). 

I provided an example to TN, for the "CT Bone Seg" node of the corresponding study on dalco-staging on 28-09.
