### ISSUE TITLE
osparc.io unresponsive & failing to start some dynamic services

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#721]
Due to high server load and a machine failure in the core osparc-simcore stack, operations of `osparc.io` were impaired between 18th of September 2022 / 1pm (UTC) to 19th of September 2022 / 6am (UTC)

CC @elisabettai

**Comment by elisabettai** [comment]
This was resolved by bringing manager2 back online. 
However what are the factors that made the platform unusable for few hours are still under investigation.
