### ISSUE TITLE
Redis locked "CLOSING" not removed

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#724]
Hello guys, I have a project in https://osparc.speag.com/ without big files, that is taking more than 20 mins to close. Is there anything happening?

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/x11879d5miyi9d1cncugsc3dby) *by `@cassara`*._

**Comment by mrnicegyu11** [comment]
Lock:
![firefox_b4qZG6dCCz](https://user-images.githubusercontent.com/8209087/191459232-940b1a33-9db4-4d08-81f4-1d601a5981a9.png)
No services for project in portainer:
![firefox_yfV0avpaO1](https://user-images.githubusercontent.com/8209087/191459268-a8713518-7383-46a1-8f71-b0c330324743.png)
No project_id in redis by the user:
![firefox_h9PbjomBhZ](https://user-images.githubusercontent.com/8209087/191459303-7a3092d3-3da9-4da9-b932-ada6ad898e85.png)



I resolved this by manually removing the lock.

**Comment by pcrespov** [comment]
@sanderegg I guess your PR will resolve this. I leave it to you. Reassign me if there is something else missing

**Comment by sanderegg** [comment]
should be fixed by https://github.com/ITISFoundation/osparc-simcore/pull/3675
