### ISSUE TITLE
Data and paper citation is not consistent across pages

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#73]
e.g., references for https://data.sparc.science/sim/#/dataset/8 vs. https://data.sparc.science/sim/#/dataset/4

**Comment by KZzizzle** [comment]
➤ Katie Zhuang commented:

working on it

**Comment by KZzizzle** [comment]
➤ DRC SIMCORE commented:

Manuel Guidon is this still he case?

**Comment by KZzizzle** [comment]
Hi @ignapas could you check the citations on the portal? some of them have developers as first authors - I'm not sure this is correct (e.g. https://data.sparc.science/sim/#/dataset/4)

**Comment by KZzizzle** [comment]
➤ Manuel Guidon commented:

Simcore developer names appear probably because they own the corresponding datasets.

**Comment by ignapas** [comment]
I took a look and removed our names from the contributor lists. Now republishing.

**Comment by KZzizzle** [comment]
All references now render correctly with correct authors.
