### ISSUE TITLE
release v1.37.0

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#734]
# Release v1.37.0

- Releases latest **staging_vaporwave_X** -> **production** 
- Target  date for the release:
	-> ~~MONDAY~~  (TN unexpected review)
	-> ~~TUESDAY~~ (v1.36+v1.35 failed: remains 1.34.6) 
	-> **MONDAY (Oct 10)**

## Prepare staging

- [x] apply hotfixes already in production and call vaporwave_2  @odeimaiz @pcrespov  (Th)
- [x] apply hotfix AWS and call vaporwave_3  @pcrespov @GitHK   (Th)
- [x] target *vaporwave_4*  @pcrespov @GitHK  (Fri)
	- ITISFoundation/osparc-simcore#3414
	- ITISFoundation/osparc-simcore#3409
	- dy-volume issue (ITISFoundation/osparc-simcore/#3272): 
           -  ITISFoundation/osparc-simcore#3407:  Adds support tools in ITISFoundation/dy-volumes-cleanup#1
           -  ITISFoundation/osparc-simcore#3406

## Check changelog

See [changelogs](https://github.com/ITISFoundation/osparc-simcore/releases) 
- [x] review changelog of staging @elisabettai @pcrespov  (Thu/Fri)

## Check ⚠️devops

- [x] review and prepare (⚠️ devops) @mrnicegyu11 @Surfict   (Thu/Fri)
	- assess whether announcement necessary (e.g. logout?)
	- assess when is the most confortable time to do release -> when on Tuesday?
- [x] review outcome from dy-volumes issue @mrnicegyu11 @Surfict 🚨 !!!
	  
## Test assessment: e2e-testing

Assessment carried out by batman/robin
- [x] @GitHK  (Thu/Fri/Mon)
- [x] @odeimaiz / @elisabettai  (Wed/Thr/Fri)
		- no show-stoppers
		- dask scheduler issue [#15](https://git.speag.com/oSparc/e2e-testing/-/issues/5) (cron job to autostart tmp in place)

## Test assessment: targeted-testing

- [x] **targeted-testing** @elisabettai (Thu/Fri/Mon)
	- [x] DEVELOPERS: check feedback in PR by @elisabettai
	- [x] 🚨  ITISFoundation/osparc-simcore/#3272 (ANE adds dy-volume script removal should make risk of failure affordable until next release)
		- ITISFoundation/osparc-simcore#3407
		- ITISFoundation/osparc-simcore#3406

## Test assessment: user testing
- [x] **user-testing** @newton1985  (Fri)
   - no show-stoppers
   - [x] need to follow up with non-blocking issues (video) @pcrespov 

## Releasing 
- Release has to be done **by at least two people** 
- Release assessment
	- [x] check successfully deployed
		- check image label for commit ID
		- ...
	- [x] update changelog (see outcome from *check changelog*)

**Comment by pcrespov** [comment]
@ITISFoundation/dev-team 
Have just deployed pre-release https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_vaporwave4 in AWS and dalco staging.  All checks:
- [x] https://github.com/ITISFoundation/osparc-simcore/commit/6e82fc0de27e7f1de44533425df589799f0b2e22 checks in VCS_REF of image labels and front-end
- [x] e2e passes

**Comment by Surfict** [comment]
1.37.0 deployed  just now on tip.itis.swiss, osparc.io and osparc.speag.com. SHA=6e82fc0de27e7f1de44533425df589799f0b2e22
More details [here](https://github.com/ITISFoundation/osparc-simcore/releases/tag/v1.37.0)

**Comment by pcrespov** [comment]
Moving to a new issue ``need to follow up with non-blocking issues (video)`` @pcrespov
