### ISSUE TITLE
Improvements on UX for service deprecation

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#737]
From PC via mattermost:
`I think deprecated does not mean that it cannot be used but rather that that feature will not be usable in the future`

Improvements for deprecated services:
- [x] Call it `deprecated` only if the date where it cannot be started in the future. Find another descriptive name for the state when we do not allow an old service to be started
- [x] In the "patch upgrade page" (reachable from osparc dashboard), deprecated services with only major version upgrades available are called "up-to-date" which is not accurate.
- [x] A descriptive (error)message when trying to run deprecated comp. services is missing from the frontend
- [x] *Future Improvement:* Allow automatic patch upgrades even when study is open

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/jopjyg83wpn4tduy66sbijrrzh) *by @pcrespov*._

**Comment by mrnicegyu11** [comment]
@sanderegg I added you as suggested by @odeimaiz since there might be backend changes as well. Remove yourself from this ticket if not applicable :) merci vielmals!

**Comment by pcrespov** [comment]
I imaging two ways:

either mark as deprecated and an "not supported" day
or mark them right away as "not supported" (and state the reason e.g. unsecure)

Here some screenshots of tools that report outdated features/libraries

![image](https://user-images.githubusercontent.com/32402063/194526718-2e10a86c-4e41-4421-9e36-f28246b11f13.png)
![image](https://user-images.githubusercontent.com/32402063/194526743-34f69ec5-e5e2-4ff6-a925-6687bc599820.png)

**Comment by pcrespov** [comment]
![image](https://user-images.githubusercontent.com/32402063/199943187-ae8136b9-91df-454b-86c4-21770b4afbe3.png)
From https://www.ibm.com/docs/en/acvfc?topic=manager-product-lifecycle

**Comment by pcrespov** [comment]
This was nicely presented today by @odeimaiz 

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/17ddf4ea-5aca-46e7-ad50-c02a8150447c)
