### ISSUE TITLE
tiplan e2e test failing on master: docker service placement constraint issue

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#738]
**Long Story Short**
- tiplan e2e test failing on master
- the ti-postpro (dynamic sidecar service) stays pending forever in the frontend
- portainer shows the dy-sidecar to be pending, as such:
![firefox_eioDSq8yV8](https://user-images.githubusercontent.com/8209087/194846927-12d60d93-90f2-4b48-8da3-f84d4178b2e3.png)
- Inspection of the docker service scheduling constraints give 
![firefox_vq6vDKjT9D](https://user-images.githubusercontent.com/8209087/194846981-d2704bcb-a3d5-4736-a253-012e7942c060.png)
- Removing the constraint for `os= linux` (SIC!, note the whitespace) switches the message for the pending dy-sidecar to
![image](https://user-images.githubusercontent.com/8209087/194847225-dd87fda5-3799-4d7e-9205-beb00f5b831f.png)
- Then, after some seconds/minutes, the service and assoc. dy-sidecar will start.

It has furthermore been verified that the other two docker service placement constraints are correctly fulfilled on nodes master06 and master07. Thus, likely there is an error, possibly an extra whitespace, in the constraint for `os= linux`

CC @odeimaiz (discovered the issue)
CC @elisabettai (batman)

@elisabettai : I assigned you so you may please make sure that this is assigned to a person to be fixed, I dont know who maintains the docker image of the `ti-postpro` service. Then, feel free to assign someone to fix it and unassign yourself. Merci!

**Comment by elisabettai** [comment]
Ok. The maintainer of ti-postpro is @mguidon, source code is [here](https://git.speag.com/oSparc/ti-solutions/-/tree/master/services/postprocessing). 
However, I don't think the culprit is the service itself, the [constraints](https://git.speag.com/oSparc/ti-solutions/-/blob/master/.osparc/runtime.yml#L20) looks OK to me. Also the last time the test passed (Oct 7) the same service version (1.0.56) was run as today.

What specifies those labels? After a quick search in the simcore code, I did not find anything suspicious.

**Comment by elisabettai** [comment]
Still getting the same error, with `ti-postpro` on master. I've tried removing the white space in the placement constraints (in pending dy-sidecar in Portainer), but did not help.

**Comment by mrnicegyu11** [comment]
It seems that updating anything in the docker service (I changed an env var) leads to it switching from pending to started.

According to https://github.com/moby/swarmkit/blob/676f45ffddc0c2589c52f2ff84311a332fc1bb45/design/scheduler.md :
```
In the SwarmKit [task model](https://github.com/moby/swarmkit/blob/676f45ffddc0c2589c52f2ff84311a332fc1bb45/design/task_model.md), tasks start in the New state, and advance to Pending once pre-scheduling activities like network allocation are done. The scheduler becomes responsible for tasks once they reach the Pending state. If the task can be scheduled, the scheduler schedules it immediately (subject to batching), and advances the state to Assigned.
[...]
```

**Comment by GitHK** [comment]
this was due to lack of resources on the deployment. After some cleanup the `ti-postpro` is able to start again.
