### ISSUE TITLE
Deploy S4L Lite on AWS - DevOps

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#740]
**DevOps**:
- [x] Cloud is set up (done, `osparc.io` is used)
- [x] Audit / Review the cloud w.r.t. security, maintainability and bringing all potential deprecated practices up-to-date
- [x] resource limitations: set the correct VRAM number on the ec2 nodes
- [x] Study ability to bill another account than the NIH one
- [ ] AppArmor (to prevent using scripting for malicious outcomes)
- [ ] New license server with light features (requires env var)
- [ ] STUN/TURN for 5G Video Streaming
- [ ] Mailserver
- [x] s4l-web-lite Statuspage and E-Mail Alert / Notification channel for scheduled downtimes

Not strictly DevOps, but relevant for roll-out:
- [ ] Projected costs and upper limits are agreed upon
- [ ] Monitoring / alerts w.r.t. monthly costs need to be adjusted
- [ ] Strict resource limits are in place (see https://github.com/ITISFoundation/osparc-issues/issues/576, https://github.com/ITISFoundation/osparc-issues/issues/618)

**Comment by esraneufeld** [comment]
@mrnicegyu11 please fill this case

**Comment by pcrespov** [comment]
- Please do not forget to enumerate what config you want for this product (e.g. invitations? trial accounts? 2FA? manuals? issue tracker? Check TIP product settings  and setup asap. thx

**Comment by mguidon** [comment]
> 

Very good point. Thanks

**Comment by Surfict** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- Study ability to bill another account than the NIH one
- Plan cost for the two different solutions
- Documentation about creating an entire stack in AWS
- Check where is the administration of sim4life.io
