### ISSUE TITLE
Add legend/explanation of nodes connections

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#742]
**Describe the user role**
As a (novice user), I  would like a quick "cheat sheet" to understand what different arrow types represent. E.g. by hovering on the arrow, or some kind of legend (maybe in the second column?)

**Describe the goal**
The different arrow types will let me know if outputs/inputs are connected as expected

**Describe the benefit**
Right now we have many different arrow types (blue solid line, blue dashed, red, gray solid, gray dashed). It's not clear what the different colors/type of lines mean

**Additional context**
This was reported during a review

**Comment by odeimaiz** [comment]
![legend](https://user-images.githubusercontent.com/33152403/195568963-cc16036f-ba0d-41f1-9c37-78a046a181a3.gif)
