### ISSUE TITLE
Pre-release master -> Staging_switzer2

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#744]
In preparation for [pre-release](https://github.com/ITISFoundation/osparc-simcore/releases). Here an initial (incomplete) list of tasks to prepare before pre-releasing:

- [x] Draft changelog from commits list (see [docs/releasing-workflow-instructions.md](https://github.com/ITISFoundation/osparc-simcore/blob/6cae77e5444f825f67fca65876922c8d26901fd2/docs/releasing-workflow-instructions.md))
- [x] check important changes 🚨
- [x] devops check (⚠️ devops)
- [x] e2e testing check
- [x] pre-release summary

---

# check important changes 🚨

- Motivation: @GitHK important fixes for dy-services

#  devops check (⚠️ devops)

- No special preparations required
- [x] disable cron job to restart scheduler in ``staging`` deploys after this pre-release (to test #3444)
- [x] cleanup staging AWS (orphan services etc)

# e2e testing check

- No major issues

# Draft Changelog

## Added
- ✨Dy-services: cli command for cleanly closing services after error (#3430)

## Changed
- ✨ Implements #3453: fail boot if invalid product setup (#3455)

## Fixed
- 🐛Dy-services:  no longer push outputs when service starts (#3443)
- 🐛Dy-services: retry on 400 RequestTimeout when uploading (#3448)
- 🐛Dy-services: dy-sidecar sometimes does not save state and outputs (#3438) 🚨[ **TODO:** 
   - open a study a lot of juqpuyters and generate some data each the nodes
   - Leave it open for a very long time in the tab
   - If any services gets restarted and the data is saved the fix worked as expected ]
- 🐛 Fixes #3372: removes future warning of alias in BaseSettings (#3454)

## Security / Maintenance
- 🔨 Maintenance/type checker repo-wide (#3450)
- 🔒️⬆️ Maintenance/upgrade vulnerable nbconvert (#3451)
- ⬆️ Maintenance/update dask-services (#3444) 🚨 [ TODO: rm cron job that restart dask-scheduler ]
- ⬆️ Bump actions/setup-node from 3.5.0 to 3.5.1 (#3452)
- ⬆️ 📝Maintenance/week 41 updates testing+tooling dependencies and CITATIONS (#3442)

** Legend **

- ✨ New feature
- 🐛 Fixes bugs
- ♻️ Refactors code
- ⬆️ Upgrades dependencies
- 🔒️ Fixes security issues
- 🔨 Adds or updates development scripts or CI.
- 🚨 important change. REQUIRES app-level testing before releasing to production
- 📌 can be cherry-picked to production

# Summary

- what:  ```make release-staging name=switzer version=2 git_sha=dbcc9a645f25468ed57d227c42e8daad6ccb62d8``` in [``master``](https://github.com/ITISFoundation/osparc-simcore/commits/master)
- who: @Surfict @GitHK 
- when: THURSDAY Oct.20, afternoon

**Comment by pcrespov** [comment]
@ITISFoundation/dev-team FYI this pre-release is currently target for Thursday

**Comment by Surfict** [comment]
Release has been done. 

We experienced a problem with the CI (the one from the original commit, not the one from the release) who failed to tag and push the dask-sidecar image (nothing in the logs - it just didn't do it, didn't show an error). Restarting the CI mades it works. We didn't find the origin of the problem  -  the commit doesn't update the CI files or the Makefile.
