### ISSUE TITLE
Clicking on logger while opening large study crashes the browser

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#747]
**Describe the user role**
As a user who works with a large study (with many services and Gb of data) I might click on the Logger to check progress of the different services. This often makes the browser crash.

**Describe the goal**
Avoid crashing the browser (e.g. stream less information)

**Additional context**
Happened with Chrome

```[tasklist]
### Tasks
- [ ] 
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4232
```

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...

**Comment by odeimaiz** [comment]
Fixed in https://github.com/ITISFoundation/osparc-simcore/pull/4290
