### ISSUE TITLE
Log Level on Logs

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#762]
**Describe the goal**
As a user I don't want to see so many logs in the logger.

**Additional context**
In order to reduce the amount of logs displayed in the logger, the backend should attach a log level to each log

**Comment by sanderegg** [comment]
@odeimaiz we can close this right?

**Comment by sanderegg** [comment]
this was completed as far as I'm concerned. closing. please re-open if I'm wrong.
