### ISSUE TITLE
Can define secrets and expose them as env vars on running services

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#764]
@pcrespov commented on [Wed Nov 09 2022](https://github.com/ITISFoundation/osparc-simcore/issues/3535)

Following up discussion in  ITISFoundation/osparc-simcore#3526 

The user can define some secret variables in the Preferences tab. These variables are treated as secrets i.e. they will be encrypted in the database. When a dynamic service starts, they will be exposed as env vars

This is a mechanism that is frequently used in CI settings etc ... See as examples 
- https://docs.github.com/en/actions/security-guides/encrypted-secrets 
- https://docs.gitlab.com/charts/installation/secrets.html

**Comment by Konohana0608** [comment]
Could you please add the UUID of a service to the environment vars?

**Comment by pcrespov** [comment]
This is implemented by the PRs referred above. Nonetheless, the user can still not set them via the UI and currently is only reserved for services owned by z43

**Comment by pcrespov** [comment]
> Could you please add the UUID of a service to the environment vars?

@Konohana0608 use `$OSPARC_VARIABLE_STUDY_UUID` in your service compose to get the study uuid
