### ISSUE TITLE
S4L Lite - Admin

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#766]
- [ ] Logos
- [x] Email Templates will be designed by @chavanne (account registration confirmation at least) (_partly ongoing_)
- [x] Distinguishable thumbnails for the tutorials are needed (_partly ongoing_)
- [ ] Registration via zmt.swiss form automated via black/white list
- [ ] Quick start guide content
- [ ] [oSPARC-S4L-Lite manual](https://zurichmedtech.github.io/s4l-lite-manual/) content
- [ ] Rename "light" to "lite": website, s4l documentation
--------
- [ ] Is the 'one-project == one-file' agreed upon? --> It is not yet clear, there are various pros/cons. Follow up.

**Comment by mguidon** [comment]
## Pre-Planning for sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/milestone/38)

- [ ] Registration via zmt.swiss form automated via black/white list
- [ ] Is the 'one-project == one-file' agreed upon? --> It is not yet clear, there are various pros/cons. Follow up.
- [ ] Logos
- [ ] Distinguishable pictures (thumbnails) for the tutorials are needed.

**Comment by pcrespov** [comment]
## Update on sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230111_ZeframCochrane.md)

### Done
  - https://github.com/ITISFoundation/osparc-simcore/issues/3683
     - meeting with oetikers: understand current demo licenses site and adapt to invitations
     -
