### ISSUE TITLE
Edit Templates

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#777]
As template creator, I want to be able to edit it

**Comment by sanderegg** [comment]
@odeimaiz :
Question, beside the boeing number (congrats).
What about creating a study from that template, modifying and publishing again as a template?

**Comment by odeimaiz** [comment]
🥳 
Regarding your question, it's not an option. The uuid needs to stay the same.

**Comment by sanderegg** [comment]
so depending on the level of the user, if it is internal, then I would propose to edit directly in the DB (either by adding the nodes, or by changing the study type back and forth). But that is not for regular users.

**Comment by sanderegg** [comment]
So here is the idea to implement this:

- webserver API allows for an additional entrypoint to edit a template
- only users with write access can do it
- webserver API shall also allow to save the template

**Comment by sanderegg** [comment]
solved by https://github.com/ITISFoundation/osparc-simcore/pull/3704

**Comment by pcrespov** [comment]
@odeimaiz do you think there something missing here ?

**Comment by odeimaiz** [comment]
Nope, great job, thanks!
