### ISSUE TITLE
UI/UX: Review message on the max amount of services started

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#785]
This issue follows up user-testing session with @newton1985 for ITISFoundation/osparc-issues#775

The message warning that the max services have been reached pop up before it should.  Please see video from ``3:15`` on to understand the context.

NOTE: video of the session can be found in ``itis-osparc/DEVELOPERS/TESTS_SESSIONS/2022-11-25_usertest_TN.mp4``

**Comment by elisabettai** [comment]
Might be related to #782
