### ISSUE TITLE
UI: the close button (i.e. x in the upper-right) in the info form is rendered outside of the window

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#788]
This issue follows up user-testing session with @newton1985 for ITISFoundation/osparc-issues#775

The ``X`` button is rendered outside of the info window

SEE video from ``19:07``
NOTE: video of the session can be found in ``itis-osparc/DEVELOPERS/TESTS_SESSIONS/2022-11-25_usertest_TN.mp4``

**Comment by odeimaiz** [comment]
Well, not that the close button was rendered outside of the window, it simply doesn't have any and when you click away it closes :)
![image](https://user-images.githubusercontent.com/33152403/206260198-9bf8e041-6391-4276-9bb5-2723aaaa42ff.png)

We can bring a close button to the Service Information window.
