### ISSUE TITLE
No jupyters can be created

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#796]
still failing to create new NB nodes

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/cp7hemc497bhxc3hgh8acdr13c) *by `@newton`*._

**Comment by mguidon** [comment]
Taken care of by
https://git.speag.com/oSparc/osparc-ops-environments/-/issues/368
https://github.com/ITISFoundation/osparc-issues/issues/794
