### ISSUE TITLE
NeuroSimulation fails

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#802]
Hi all, I'm fairly new to using osparc. I'm trying to run a Neuro simulation on osparc.speag.com based on the EPFL Prep2Go example. The setup runs successfully, and the output smash file seems fine, but when I submit the input h5 file to a python runner, it hangs indefinitely. When I submit it through a jupyter notebook, I get the following error message: `Simulation CAPMotorTest finished with status FAILED:`. Does anyone have a suggestion on how to debug this?

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/s71fkz4defr4dfpgtxfsfyko9o) *by `@tharayil`*._

**Comment by elisabettai** [comment]
Hi @mguidon, feel free to close this one when you think you provided enough support. Write here/link issues that might be useful for the future.

**Comment by mguidon** [comment]
Yep
