### ISSUE TITLE
Link to share templates

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#806]
Hey guys - quick question: can we still link to study templates with a url?

![image](https://user-images.githubusercontent.com/18575092/207832968-08557e7a-6231-46ce-b2d8-f2b0636a3c22.png)

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/c6j49ekgc3f3drkysg76proonh) @newton1985

**Comment by elisabettai** [comment]
The link was removed because it didn't create a study copy. 

Once this is solved, the link can be put back.

**Comment by pcrespov** [comment]
@odeimaiz I will add in the ``Project`` model an entry for the permalink (if available) in coming PR

I propose the following doc in the front-end for this link
- `` Any logged-in user with the link can copy and open this template``  (template+shared w/ everyone+not public)
-  ``Anyone on the internet with the link can open this template`` (template+shared w/ everyone+public)
