### ISSUE TITLE
Failing nodes when opening study

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#810]
Failing nodes on study `67406d1c-31af-11ec-8033-02420a0b2de3`

![image](https://user-images.githubusercontent.com/18575092/208110099-5af7cb17-924f-4b9b-8a30-c9fd6ece68e8.png)

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/19iuuoeiwpypbr1t5sgf1zjx3o) *by `@newton`*._

**Comment by elisabettai** [comment]
The nodes failed to save. @GitHK manually saved.
It's not the first time those specific nodes fail...

**Comment by GitHK** [comment]
For clarity: this is a an issue with simcore, not related to the content of the nodes.
