### ISSUE TITLE
e-mails in simcore should be case-insensitives

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#812]
**Long Story Short**
When adding a collaborator I want to use the email address I normally use to contact him/her

**Expected Behavior**
Adding the collaborator with email name.SURNAME@domain should work (I am used to send email to this address)

**Actual behaviour**
If I add a collaborator with email like name.SURNAME@domain, that doesn't work

**Steps to reproduce**
A user registers with name.surname@domain in the DB.
Trying adding him to an organization using name.SURNAME@domain fails

**Additional context**
See https://github.com/ITISFoundation/osparc-issues/issues/807

**Comment by pcrespov** [comment]
NOTE: consider https://mailchimp.com/resources/are-email-addresses-case-sensitive/
