### ISSUE TITLE
🚀 Pre-release master -> Staging ZeframCochrane4

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#822]
In preparation for [pre-release](https://github.com/ITISFoundation/osparc-simcore/releases). Here an initial (incomplete) list of tasks to prepare before pre-releasing:

- [x] Draft changelog from commits list (see [docs/releasing-workflow-instructions.md](https://github.com/ITISFoundation/osparc-simcore/blob/6cae77e5444f825f67fca65876922c8d26901fd2/docs/releasing-workflow-instructions.md))
- [x] Check important changes 🚨
- [x] Devops check (⚠️ devops)
- [ ] e2e testing check
- [x] Pre-release summary
- [ ] Pre-release assessment

---

#  Devops check (⚠️ devops)

- [x] ITISFoundation/osparc-simcore#3673
- [x] ITISFoundation/osparc-simcore#3731

# e2e testing check

- Mon. ...
- Tue.
- Wed.
- Thu.
- Fri.

# Commits 

![image](https://user-images.githubusercontent.com/32402063/211903813-9352f46e-cadc-43d3-b2c3-fc6e287819b8.png)

- ✨Frontend: Update all templates (#3748)
- ✨ Autoscaling: send autoscaling status messages in RabbitMQ (#3725)
- ✨ Contact-Us message for "product-stranger" users (#3744)
- ✨ Add capability to use basicauth flags to e2e puppeteer (#3745)
- 🐛⚗️ Bugfix/is3531/try disabling keep alive when uploading (#3737)
- 🐛 Fix/storage skip invalid projects while listing (#3740)
- Bump actions/setup-node from 3.5.1 to 3.6.0 (#3738)
- Bump json5 from 2.2.0 to 2.2.3 in /tests/e2e (#3735)
- ✨ Frontend: Product group (#3734)
- Is765/product group and vendor (🗃️ DB change)  (#3731)
- ✨ Products: Is765/2fa settings per product  (⚠️ 🗃️ devops) (#3673)
- 🐛✨ Cookie text, Fit thumbnail height and hide Classifiers from s4l-lite (#3730)

# Pre-release summary

- https://github.com/ITISFoundation/osparc-simcore/releases/new?prerelease=1&target=master&tag=staging_ZeframConchrane4&title=Staging%20ZeframConchrane4
- Changelog
```md
* 🐛✨ UI: Cookie text, Fit thumbnail height and hide Classifiers from s4l-lite by @odeimaiz in https://github.com/ITISFoundation/osparc-simcore/pull/3730
* ✨ Products: Is765/2fa settings per product  (⚠️ 🗃️ devops) by @pcrespov in https://github.com/ITISFoundation/osparc-simcore/pull/3673
* ✨ Products: Is765/product group and vendor (🗃️ DB change)  by @pcrespov in https://github.com/ITISFoundation/osparc-simcore/pull/3731
* ✨ Products.UI: Product group by @odeimaiz in https://github.com/ITISFoundation/osparc-simcore/pull/3734
* ⬆ Upgrades: Bump json5 from 2.2.0 to 2.2.3 in /tests/e2e by @dependabot in https://github.com/ITISFoundation/osparc-simcore/pull/3735
* ⬆ Upgrades: Bump actions/setup-node from 3.5.1 to 3.6.0 by @dependabot in https://github.com/ITISFoundation/osparc-simcore/pull/3738
* 🐛 Storage: Fix/storage skip invalid projects while listing by @pcrespov in https://github.com/ITISFoundation/osparc-simcore/pull/3740
* 🐛⚗️ Dy-Services: Bugfix/is3531/try disabling keep alive when uploading by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/3737
* 🔨 e2e: Add capability to use basicauth flags to e2e puppeteer by @mrnicegyu11 in https://github.com/ITISFoundation/osparc-simcore/pull/3745
* ✨ Products.UI: Contact-Us message for "product-stranger" users by @odeimaiz in https://github.com/ITISFoundation/osparc-simcore/pull/3744
* ✨ Autoscaling: send autoscaling status messages in RabbitMQ by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/3725
* ✨ Products.UI: Update all templates by @odeimaiz in https://github.com/ITISFoundation/osparc-simcore/pull/3748


**Full Changelog**: https://github.com/ITISFoundation/osparc-simcore/compare/staging_ZeframCochrane3...staging_ZeframConchrane4
```

# Pre-release assessment

**Comment by mrnicegyu11** [comment]
Looks fine, the DevOps Changes will be handled :) Thanks a lot let us know how we can help with this :)

**Comment by mrnicegyu11** [comment]
Issue during deploy: 
in the ops-config, the route to the `REGISTRY_DOMAIN` was set to a non-existing URL. Due to wildcard certificates on the DNS of said non-existing URLS, self-signed certificates where served. This was reported in the frontend logs when running comp. services. Dynamic services just remained pending forever.
The config issue was resolved.
The release went smooth apart from that
