### ISSUE TITLE
User cannot reset password

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#823]
Resetting passwords on osparc.io gives the error: "User: Cannot reset password. invalid token or user."

There are set password entry in the DB and the email use to reset the password is correct.

**Comment by mrnicegyu11** [comment]
1. Requesting password reset - works 
2. Clicking reset link from mail - works (example for me, slightly modified: `http://osparc.io/v0/auth/confirmation/sCZTdAxJJVrwdpfoQYvTYBsEMFgPR2`
3. Submitting new password: Doesnt work
![firefox_H1fvwbEydt](https://user-images.githubusercontent.com/8209087/212047672-bb9bf997-363c-46b6-9c71-bf778fdab9ca.png)

In the webserver logs:
![firefox_lyWbcgg1mr](https://user-images.githubusercontent.com/8209087/212047814-17dd26f5-1cfd-4f4a-8b82-9d9fe4ccf068.png)

Devtools in browser show a strange route for the REST request
![image](https://user-images.githubusercontent.com/8209087/212047633-21392498-8d13-4fc7-b004-f88ba717dc62.png)

**Comment by elisabettai** [comment]
This still needs a release to osparc.io (and staging.osparc.io).

**Comment by elisabettai** [comment]
This was resolved in osparc.io with the release of oSPARC 1.41.0  (see https://github.com/ITISFoundation/osparc-issues/issues/824)
