### ISSUE TITLE
Dynamic sidecar: A pending resource service never stops when going to dashboard

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#827]
While testing the Autoscaling the following issue was discovered (BLOCKER):

- click on a service in the dashboard
- once in the study workbench with the pending resources service, go back to the dashboard
--> the service will never go away.
--> the autoscaling will slowly increase the number of nodes for nothing

The problem can be simulated in master by:
setting in services_specifications something like:
```json
{"TaskTemplate": {"Resources": {"Limits": {"NanoCPUs": 250000000000}, "Reservations": {"NanoCPUs": 250000000000}}}}
```

Then do start the selected service, go back to the dashboard. and the service will stay forever.

@mguidon: this is currently a blocker

**Comment by GitHK** [comment]
While the service is starting we should check if any labels are updated. In my local deployment labels always get updated. Which I think is different from what we saw yesterday in the autoscaling scenario.

I would like to retry this with you today.

`watch 'docker service inspect dy-sidecar_11132bb9-dbca-4674-bb10-afd0d343070d | jq ".[0].Spec.Labels"'`

**Comment by sanderegg** [comment]
@GitHK did you follow what is written in the description above? E.g. set the service specifications such that the service is pending resources?

**Comment by GitHK** [comment]
Yes I did follow, but I have a feeling I am getting something different. I would like to try it again with you today.
