### ISSUE TITLE
Portal - oSPARC connection

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#830]
in view of showing progress to the NIH on the following milestones:

```[tasklist]
### Group of Issues
- [x] #711 (and #681)
- [x] #689
- [ ] #682
- [x] #683
- [ ] #673
- [x] API: obtain a list of all services and parameterized template studies marked as SPARC relevant
- [x] API: their input port description
```

**Comment by esraneufeld** [comment]
@mguidon

**Comment by pcrespov** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)

Details inside each issue

- https://github.com/ITISFoundation/osparc-issues/issues/711 @pcrespov 
- https://github.com/ITISFoundation/osparc-issues/issues/681 @pcrespov @elisabettai 
- https://github.com/ITISFoundation/osparc-issues/issues/689 @pcrespov @elisabettai 
- https://github.com/ITISFoundation/osparc-issues/issues/683 @pcrespov @ignapas @elisabettai 
- https://github.com/ITISFoundation/osparc-issues/issues/681 @ignapas @odeimaiz @pcrespov @elisabettai 
- https://github.com/ITISFoundation/osparc-issues/issues/673 @GitHK @elisabettai

**Comment by elisabettai** [comment]
Based on what @mguidon said, for the steering committee meeting we might need  to show-case this one:
https://github.com/ITISFoundation/osparc-issues/issues/683
So I guess that one has higher priority. @ignapas, did you already get the wire frames?

**Comment by pcrespov** [comment]
> So I guess that one has higher priority, @pcrespov. @ignapas, did you already get the wire frames?
@elisabettai today in the standup i asked that question and the answer was no :-) Let's  follow up on that tomorrow

**Comment by mguidon** [comment]
Even if we get the wireframes, I just realized that this will not be available in time for the sc meeting because the next portal release to prod will happen afterwards. I will discuss with esra how to proceed

**Comment by pcrespov** [comment]
## Update for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)

Details inside each issue

- https://github.com/ITISFoundation/osparc-issues/issues/711  - In progress
- https://github.com/ITISFoundation/osparc-issues/issues/681 - Ongoing
- https://github.com/ITISFoundation/osparc-issues/issues/689 - Resolved
- https://github.com/ITISFoundation/osparc-issues/issues/683 - Resolved
- https://github.com/ITISFoundation/osparc-issues/issues/682 - In progress
- https://github.com/ITISFoundation/osparc-issues/issues/673 - Opened

**Comment by pcrespov** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)

This is the state of *remaining open child issues* with an overview (details inside each issue)

- https://github.com/ITISFoundation/osparc-issues/issues/711  - **In progress**: **main** focus to extend the API
- https://github.com/ITISFoundation/osparc-issues/issues/681 - **Ongoing** : will update map-core of progress in APIs at the end of the sprint  
- https://github.com/ITISFoundation/osparc-issues/issues/683 - **Resolved**: released to production soon
- https://github.com/ITISFoundation/osparc-issues/issues/682 - **In progress**
- https://github.com/ITISFoundation/osparc-issues/issues/673 - **Open**: should at least start this sprint!!!

**Comment by pcrespov** [comment]
## Update for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230428_Jelly_Beans.md)

This is the state of *remaining open child issues* with an overview (details inside each issue)

- https://github.com/ITISFoundation/osparc-issues/issues/711  - **In progress**: **main** focus to extend the API
- https://github.com/ITISFoundation/osparc-issues/issues/681 - **Ongoing** : will update map-core of progress in APIs at the end of the sprint  
- https://github.com/ITISFoundation/osparc-issues/issues/683 - **Resolved**: released to production
- https://github.com/ITISFoundation/osparc-issues/issues/682 - **In progress**: backend resolved
- https://github.com/ITISFoundation/osparc-issues/issues/673 - **In progress**: started
