### ISSUE TITLE
Workers in same machine can't access same input file

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#85]
Reproducible with the CC templates where the same input file is used by the 0D and the 1D solvers. If the two workers fall in the same machine the bug happens.

Workaround currently in place for the templates: Added a 2nd file picker providing the same input file.

**Comment by sanderegg** [comment]
From the code this cannot be the case. It might be some other issue.
@odeimaiz First fix other problems and check this one out afterwards

**Comment by sanderegg** [comment]
closing this issue
