### ISSUE TITLE
Last minute rewording

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#862]
- [ ] Screenshot_StressTest_1 @drniiken 
- [x] Screenshot_StressTest_2 @odeimaiz 
- [x] Screenshot_StressTest_3 @odeimaiz 
- ~~Screenshot_StressTest_4~~ @odeimaiz: The “Next” button gets disabled, I think that's good enough.
- [ ] Screenshot_StressTest_5 @mguidon  https://git.speag.com/oSparc/osparc-s4l/-/issues/567
   NOT DOING (too risky, we could hack the db if you really want)
- [x] Screenshot_StressTest_6a, 6b @odeimaiz 
- [x] Screenshot_StressTest_7 @odeimaiz 
- ~~Screenshot_StressTest_8~~ @odeimaiz: That's the name of an organization, there is not much we can do there
- [x] Screenshot_StressTest_9 @eofli @pcrespov

**Comment by eofli** [comment]
Product name corrected in dashboard manual - couple of format issues
