### ISSUE TITLE
Upgrade to python 3.10

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#877]
go to the next level

**Comment by pcrespov** [comment]
These are the steps that I suggest to follow:

1. upgrade tests & tools requirements (in 3.9)
2. upgrade primary libraries (e.g. fastapi, etc) (in 3.9) 
   - ITISFoundation/osparc-simcore#3905
3. upgrade ``pip``
4. prune unused libraries repo-wide see [doc](https://github.com/ITISFoundation/osparc-simcore/blob/31558237f0dc0dfaa0136d068ae76eb220309f12/requirements/how-to-prune-requirements.md)
5. upgrade to 3.11
6. Check deprecation warnings both in code and libraries
   - 
7.

**Comment by pcrespov** [comment]
Upgrade is implemented and steps documented
