### ISSUE TITLE
user requests (10%)

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#886]
[Support table](https://github.com/orgs/ITISFoundation/projects/9/views/14)

**Comment by elisabettai** [comment]
@sanderegg, thanks for bringing this up. Let me know if I can help with cleaning up the Support table (I'm also not sure how we use it, i.e. should we ask TN to assign priorities every sprint?).

In the meantime, this one user request that came up a couple of times recently (Team Black and internal users): https://github.com/ITISFoundation/osparc-issues/issues/716
