### ISSUE TITLE
Group Studies (not only Services) by "Shared with"

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#895]
This can be a first easy step to allow users to organize their workspace.

It can help with/solve a number of user requests:
- https://github.com/ITISFoundation/osparc-issues/issues/716
- https://github.com/ITISFoundation/osparc-issues/issues/751
- https://github.com/ITISFoundation/osparc-issues/issues/873
- https://github.com/ITISFoundation/osparc-issues/issues/887

**Comment by pcrespov** [comment]
@odeimaiz dont' you think this could be the issue that requires both front and backend? 
BTW i unassigned because @sanderegg assigned it to me by mistake

**Comment by odeimaiz** [comment]
Yes, I assign it to you.

**Comment by sanderegg** [comment]
@elisabettai can you close this one since the other 2 are already planned, thx
