### ISSUE TITLE
Study taking long to open

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#898]
I'm trying to load one of the Prep2Go viewer studies (my original, not the template we created), and so far I've been waiting around 30-40 minutes.

It's called Supp. Materials: Volunteers, and it's on osparc.io

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/cry93k697jnwpdow7jgx9wxx5r) *by `@newton`*._

**Comment by elisabettai** [comment]
This type of issues should go somewhere else (e.g. gitlab). 
From MaG: "This is a legacy service which now wants to have 96 GB of RAM". The limits need to be overwritten to make it work.

**Comment by mguidon** [comment]
I prepared a new study for antonino with the original data but the latest services.
