### ISSUE TITLE
NEUROFAUNA rat, S-D18, Y3M3

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#9]
finalization of the NEUROFAUNA rat 
- [x] a detailed, image-based rat anatomical model has been created

**Comment by odeimaiz** [comment]
Template created containing the Neurofauna Rat
![image](https://user-images.githubusercontent.com/33152403/91150155-4e4b0180-e6bc-11ea-95a0-746109fdda9f.png)
