### ISSUE TITLE
Sharing: user will not get notified (more details)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#900]
Follow up of https://github.com/ITISFoundation/osparc-simcore/pull/3915
Improve not be notified message with more information. 
E.g. add: "The study/template will appear in their dashboard at the next login." Or "Send them an email to notify"
send email or you'll see the study when logging in.

**Comment by odeimaiz** [comment]
I would close it in https://github.com/ITISFoundation/osparc-simcore/pull/3937
