### ISSUE TITLE
Demoting a full organization might need a danger zone

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#901]
We just did an experiment on a Study.
This study has a owner and it was shared with an organization with "Collaborator" role.
A member of the organization demoted the organization to "Viewer" -> now all the the members of the organization are blocked in "Viewer" mode.
The only way to recover the edit rights is to send an email to the owner.

It would be good to add a confirmation message/danger zone to avoid these kinds of operations.

**Comment by nitrosx** [comment]
Could we add a "message to owner" or "request collaborator access" directly from the study?

**Comment by odeimaiz** [comment]
Hi @nitrosx, how are you doing?
I moved your comment (and replied) into a new feature request issue:
https://github.com/ITISFoundation/osparc-issues/issues/903
