### ISSUE TITLE
Include bash functionality by default in Jupyterlab NBs

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#905]
**Describe the user role**
As an osparc user, I would like certain functions to be _always_ available in the terminal of any version of any Jupyterlab NB on all platforms (e.g. zip).

**Describe the goal**
Include certain bash functions by default in the terminal of all Jupyterlab NBs. 

**Describe the benefit**
Users need basic functionality like zip etc.

**Additional context**
We should discuss to figure exactly what functions are required.
![screenshot](https://user-images.githubusercontent.com/70750341/225267003-ba6327ec-8c06-4293-bebf-975563bc74a1.jpg)

**Comment by mguidon** [comment]
Thats a good idea. Just out of curiosity, which version of jupyter-smash is that? zip/unzip has been added recently.

**Comment by newton1985** [comment]
This would be 3.0.8 Jupyterlab Sim4Life on osparc.io

**Comment by newton1985** [comment]
duplicate/parent of #791 ?

**Comment by elisabettai** [comment]
Closing this and keeping the discussion in #791. A list of terminal commands that should be available in all services sounds a good idea.
