### ISSUE TITLE
File load error

### ISSUE THREAD

**Issue by Fariba2012** [ITISFoundation/osparc-issues#908]
Hi support team, 
I have another issue with my study on osparc.io. 
I cannot open my jupyterlab file; could you please help?
![image](https://user-images.githubusercontent.com/118256846/225861378-4816c327-921f-4cb9-8f99-6a4623a243b9.png)

**Comment by elisabettai** [comment]
Hi @Fariba2012 thanks for opening this, good that it solved with a restart. Did you mean that you restarted the whole study/reloaded the page or something else?

**Comment by elisabettai** [comment]
Just talked with @Fariba2012 and she hasn't experienced this problem anymore. We'll re-open if it happens again.
