### ISSUE TITLE
notify sharer of studies when sharee does not have access to services inside study 

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#909]
**Describe the user role**
As an osparc user, I would like to be notified/warned when attempting to share a study with another osparc user who does not have access to services inside the study. 

**Describe the goal**
Alert the sharer of studies to the fact that their target user will not be able to open the shared study.

**Describe the benefit**
This will reduce confusion for sharer and sharee, and save time for all involved.

**Additional context**

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...
