### ISSUE TITLE
Xcore DLL not licensed 

### ISSUE THREAD

**Issue by Fariba2012** [ITISFoundation/osparc-issues#910]
dear osprac support team, 

I tried the license for AI segmentation toolkit and it works the 1st time; now I am trying to use it on other study and it failed. but maybe it is not because of that but because of another license: 
![image](https://user-images.githubusercontent.com/118256846/225947074-02b79093-b039-490f-ab88-fe566d752746.png)

could you please help with that? 
thank you

**Comment by colinRawlings** [comment]
This was diagnosed as a result of AWS needing to restart the license server node by @mguidon .  The problem was fixed
