### ISSUE TITLE
🚀 Pre-release master -> staging_JellyBeans_1

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-issues#915]
In preparation for [pre-release](https://github.com/ITISFoundation/osparc-simcore/releases). Here an initial (incomplete) list of tasks to prepare before pre-releasing:

- [x] Draft changelog from commits list (see [docs/releasing-workflow-instructions.md](https://github.com/ITISFoundation/osparc-simcore/blob/6cae77e5444f825f67fca65876922c8d26901fd2/docs/releasing-workflow-instructions.md))
- [ ] Check important changes 🚨
- [ ] Devops check (⚠️ devops)
- [ ] e2e testing check
- [ ] Summary
- [ ] Release
- [ ] Postmortem

---
# Motivation:

- Weekly release

#  Devops check (⚠️ devops)

# e2e testing check

- Mon. ...
- Tue.
- Wed.
- Thu.
- Fri.

# [Commits (in order)](https://github.com/ITISFoundation/osparc-simcore/commits/master)

- ♻️ e2e: improve error reporting (#4048)
- 🐛 fixes broken node progress (#4049)
- 🐛🗃️ Dask gateway: clusters cannot be deleted after usage (#4036)
- 🐛 Frontend: minors 30.03 RM (#4045)
- 🔨 Maintenance/upgrade python version to 3.10 (#4010)
- 🐛 filetypes in webserver API are case insensitive (#4041)
- 🎨 Frontend: Update services UX II (#4031)
- ✨ Is683/view link can open a project with a single service (2/2) (#4038)
- 🐛Dask: Handle when gateway is offline (#4033)
- ✨🗃️ Implements services listing for nih-portal (1/2) (⚠️  devops) (#4024)
- 🐛 Sometime docker timestamps are not parsed correctly (#4003)
- fix setDownloading(false) (#4026)
- 🎨Frontend: Update services from Dashboard UX (#4011)
- ♻️Dask gateway: add missing variables + change deprecated calls (#4022)
- ✨Add simcore_user_agent and product_name to user service labels (#3990)
- ✨ Gateway-server: add ENV variable to change how many CPUs/RAM is advertised by each sidecar (#4019)
- ♻️ Notifications cleanup (#4004)

# Summary

- [x] `` make release-staging name=JellyBeans version=1 git_sha=0b60aee54ae17ef4b31156e833b44f1c7c47aee9``
- [ ] Draft [pre-release](https://github.com/ITISFoundation/osparc-simcore/releases)
- [x] Check [target commit 0b60aee54ae17ef4b31156e833b44f1c7c47aee9](https://github.com/ITISFoundation/osparc-simcore/commits/master)  ✅ CI passed
- [ ] Announce
```json
{"start": "2023-04-04T12:30:00.000Z", "end": "2023-04-04T13:00:00.000Z", "reason": "Release JellyBeans_1 "}
```

# Release

- [ ] Release (release draft)
- [ ] Check Release CI
- [ ] Check deployed dalco/aws ()
- [ ] Delete announcement
- [ ] Check e2e runs
- [ ] Announce
``` md
https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_ResistanceIsFutile10
```

**Comment by pcrespov** [comment]
@matusdrobuliak66 please consider the following changes:
- open the issue in osparc-simcore repo instead of in this repo. SEE https://github.com/ITISFoundation/osparc-simcore/issues/new/choose
- pre-release to staging should be until ``3e95484704deafca993d5a5cd822ff0a8e540cd6``  (corresponds to PR https://github.com/ITISFoundation/osparc-simcore/pull/4038)
- These commits **were done during previous sprint**, therefore the name of the pre-release should be `` Mithril 5``. We will release with the new sprint name probably from next week on.
thx

**Comment by matusdrobuliak66** [comment]
Moved to the osparc-simcore repo https://github.com/ITISFoundation/osparc-simcore/issues/4054
