### ISSUE TITLE
don't automatically start NBs

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#916]
**Describe the user role**
As it stands, when a user opens a study where there are 5 or fewer notebooks, those notebooks are started automatically. However, this policy tends to cause long waiting times for closing studies in case the user only wants to inspect one or two notebooks, or some other aspect of the study, then close. The user could be any osparc user.

**Describe the goal**
Change the policy from: start 5 or fewer notebooks automatically, to: all notebooks must be started manually. 

**Describe the benefit**
This would significantly cut down on wait times for studies to unlock after closing in case the user only wants to quickly inspect the study (or one or two specific notebooks in the study). 

**Additional context**
@JavierGOrdonnez commented: "I would like to support Taylor on this point. Very often I just need to quickly inspect what is in the study, maybe swap to another one to inspect for differences, and then maybe come back to check some codes in one of the jupyter notebooks... Thus, having to wait significant time for studies to open and close is not ideal.

Maybe I could suggest an "inspection" opening mode in which no nodes are initialized (unless got into by the user); and the default mode still being the current behaviour."

@esraneufeld commented: "having to start services is still not obvious to users and most will have fewer than 5, so that the current behavior will be easier for them. maybe the cheap way out of having to decide (make it an option that the user can set) is the right one here?"

@newton1985 responded: "I reasoned that user will have to learn about the manual start/stop thing anyway, so perhaps it's more consistent to just always require it
... I don't think we're really sparing anyone from the complexity of osparc usage by starting nodes automatically"

**Comment by newton1985** [comment]
@elisabettai  - which dynamic services do mattward & bornstein use? are they jupyter notebooks?

**Comment by elisabettai** [comment]
> @elisabettai - which dynamic services do mattward & bornstein use? are they jupyter notebooks?

Mattward and bornstein are based on plotly-dash (they're just viewers to display data produced for instance by a computational service). They're not jupyter-based services but are still dynamic services. 

Thanks to everyone about this case and providing your ideas. As far as I understand, one of the main reason why you opened this case @newton1985 is that it takes too long to close studies without reason (e.g. a dynamic service was started, but its data has not been modified).

We'll soon discuss with the team this case and the related #928.

**Comment by sanderegg** [comment]
look into pigz library for zip parallelization

**Comment by sanderegg** [comment]
proposal:
- create a flag per project where one can select whether the services shall auto-start (default True)
- pass that to the backend


For more elaborate solutions we need:
- to be by product (s4l needs to start)
- portal links should auto-start
- per user (needs user preferences)
(- maybe you want the ones open before to re-open (needs project preferences))
