### ISSUE TITLE
Resource Control: Personalized Resources

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#920]
Dynamic and computational services can be started with default or user-defined resources. This can be selected in the frontend and via the osparc-api for solvers

- see #618

**Comment by pcrespov** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)
- ...

**Comment by mguidon** [comment]
closing since it is a duplicate
