### ISSUE TITLE
Application & Platform Improvements

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#926]
## Suggested UI/UX Improvements 

(S4L-product and applications (s4l, jupyter, ...), oSPARC)

- [ ] #929 
- [ ] #930 
- [ ] #931 
- [ ] #932 

This is a living, ongoing case ...

**Comment by drniiken** [comment]
@mguidon ... sure thing.

**Comment by mguidon** [comment]
obe
