### ISSUE TITLE
don't push to S3 unless changes have been made

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#928]
**Describe the user role**
As an osparc user, when I close studies that I haven't modified (but when I _have_ started a dynamic service), the study pushes the data to S3, locking the study for a long time unnecessarily. 

**Describe the goal**
Cut down on close/unlock time by not pushing when there are no changes.

**Describe the benefit**
Save time.

**Additional context**
This is related to case #916, where dynamic services shouldn't be started automatically to avoid wasting time on closing (and resources pulling services the user doesn't need).

**Comment by sanderegg** [comment]
Input from @colinRawlings:
look into pigz library for zip parallelization

1. test this pigz library while compressing
2. storage needs to know about folders 
3. storage needs to compute the checksum of every single file and store in S3/database

**Comment by elisabettai** [comment]
This should be resolved. Now we don't save anymore the files into a workspace folder (and zip it), instead we "save" each file individually and push only the ones that have been modified to S3 when you close the study or stop the service. This should result in faster study **closing**.
@newton1985 feel free to reopen if this is not the case.
