### ISSUE TITLE
"Anonymous User Experience" Mode

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#929]
## Summary
As a new and quite unique feature (compared to competition) we want any "potential future users" to be able to "experience" S4L, without having to register (and to go through that whole process).
Experiencing S4L means to be able to view some cool 3D models and some cool simulation results.
Allowing them to experience can be initiated by us (providing a simple link) or via the cool new (tbd) website, clicking on a link, etc.

Disclaimer:
We (Nik, Team) need to keep in mind IT related issues wrt the ViP models - issues aka "the naked man".
Exposing parts of the models which shall not be exposed and "experienced".

## Intention

Create an anonymous mode:

- allow potential users to experience the capabilities of S4L
- provide templates to guide users and help them understand the capabilities of S4L
(see summary above)

## What to Do, MVP

- accessible to both registered and non registered users
- essentially unlimited access to the platform in a "read only" mode

- we would allow some studies to be accessible in that way
- via "sharing" capability, it will be defined in what "mode" the study is (i.e., if it can be anonymously shared via link)
- anybody could share studies like this and anybody could access them and view them

- such a study could be "templated" and I could copy it to my dashboard - assuming I registered in the meantime

- shall all of these studies be viewable and accessible via a huge (and searchable) "Dashboard" ???

### The Read Only Mode

- anonymous users can't do anything but can see and move around everywhere
- they can only look at already postprocessed results, they can't instantiate new viewers
- they can look at models, operate in the 3D view/window, etc.
- they can switch tabs, look around, etc.
- but everything is greyed out

For the future we might also envision to have automated or pre-defined "views" easily accessible (that will be another case for the backlog):

```[tasklist]
### Tasks
- [ ] LImit number of users
```

```[tasklist]
### Watermelon
```

**Comment by drniiken** [comment]
@sanderegg @odeimaiz @eofli @calys

**Comment by mguidon** [comment]
## Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)

- [ ] Paused
