### ISSUE TITLE
Move Dalco Cluster to Z43

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#93]
As we are paying solid amounts of money every month for it at Dalco, please move our current Dalco/Production cluster to Z43 asap, i.e., during the coming sprint.
Thanks.

**Comment by Surfict** [comment]
**Current status**
- DevOps stack
- Migration scripts and process are ready
- CI of 3rd party services

**Ongoing development**
- Make Websockets works
