### ISSUE TITLE
Improve error message when trying to open a non published template as anonymous user

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#945]
**Describe the user role**
I am a user who knows little about oSPARC and finds this link to a template on the SPARC Portal: https://osparc.io/study/014254be-4e3a-11ed-ae4f-02420a0b0131

**Current behavior**
![image](https://user-images.githubusercontent.com/18575092/234896062-3974db8b-6752-4aff-b760-35637ebc0ade.png)

The message "Error:not found" is misleading
**Desired behavior*
We should have a nicer message with a bit more formatting (e.g. new lines) and remove the "not found"

**Additional context**
Was already mentioned by EN before SC meeting and now by K-Core. K-Core thought that the link was broken.

**Comment by elisabettai** [comment]
@pcrespov, this is related to #830 (I converted that to an epic and added this one there). 
It's a follow-up of #829.

**Comment by elisabettai** [comment]
Hi @pcrespov, do you think you/someone can have a look to this the coming sprint? I think it's better to fix it sooner than later (by that, I mean improving this error message).

I just had a look to it with EN and he was puzzled by still seeing the "Error: not found" message and also K-Core complained when we submitted studies for the Portal that have jupyters inside.

**Comment by pcrespov** [comment]
> 

@elisabettai all messages has been factored out in two files

https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/src/simcore_service_webserver/studies_dispatcher/_constants.py

and 

https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/src/simcore_service_webserver/studies_dispatcher/_errors.py

Can you please review those with EN or whoever is interested/involved and create a PR with it?

**Comment by elisabettai** [comment]
Hi @pcrespov, will do, thanks. I also got some suggestions from Team Black, I write them here to keep note:

- break the test in steps
- there's no need for button with support email, it can be added to the text. Or, if we want to keep the button, that should redirect to mailto:blabla (so it opens a mail client)
- login button: make it more prominent
- In general: simplify message

fyi @odeimaiz

**Comment by odeimaiz** [comment]
> * there's no need for button with support email, it can be added to the text. Or, if we want to keep the button, that should redirect to mailto:blabla (so it opens a mail client)

That's what it does if you click on the email once you pop it up.

> * login button: make it more prominent

We could give it the product specific strong color
