### ISSUE TITLE
sim4life.io - WP6: API

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#952]
## Description

At sim4life.io, we recognize the importance of providing a comprehensive API that is both flexible and user-friendly. As part of this commitment, we have ensured that our API supports a wide range of features:

- Files: upload/download/delete
- Solvers: start/stop/delete jobs, streaming of job progress
- Studies: create/modify/delete/run
- Users: personal preferences, remaining simulation hours

Via API, users will also be able to define the hardware on which their services run.

```[tasklist]
### This is Sparta!
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5236
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1255
```

```[tasklist]
### Kobayashi Maru
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4604
```

```[tasklist]
### Microhistory
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4768
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/50
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4153
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4231
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4234
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4914
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4652
```

```[tasklist]
## Quilmes
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4641
```

```[tasklist]
### Baklava
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4651
```

```[tasklist]
### Sundae
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4110
```
```[tasklist]
### Watermelon
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4111
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/733
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4345
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4313
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3626
```

**Comment by pcrespov** [comment]
## Update for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230602_PastelDeNata.md)
- https://github.com/ITISFoundation/osparc-simcore/issues/4231
- https://github.com/ITISFoundation/osparc-simcore/issues/4234
- https://github.com/ITISFoundation/osparc-simcore/pull/4250. SEE new [openapi-spec](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ITISFoundation/osparc-simcore/b95953661d79408f2ef88b100ed2b2a9ed3b7b97/services/api-server/openapi-dev.json)

**Comment by pcrespov** [comment]
### Sprint [WaterMelon](https://github.com/ITISFoundation/osparc-simcore/milestone/46)
-

**Comment by elisabettai** [comment]
> See more details comparing swagger views for:
> 
>     current [openapi.json](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pcrespov/sandbox-python/c1d3e4f7565a26461f510df8f333548cfa83e3ce/api/openapi.json)
>     new [openapi-dev.json](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pcrespov/sandbox-python/c1d3e4f7565a26461f510df8f333548cfa83e3ce/api/openapi-dev.json)

@pcrespov, am I missing something or these two links above point to the same version of the API? I'm unable to see the diffs by eye. 🙃

**Comment by pcrespov** [comment]
> 

@elisabettai no, one is pointing to the current `openapi.json` and the other the the new (separately). The diff is the list that I show you above. I also have an automatic report with the diff but it is not easy to visualize (it is for machines!)

**Comment by bisgaard-itis** [comment]
# Update [Quilmes](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20231006_Quilmes.md)
- https://github.com/ITISFoundation/osparc-simcore/issues/4604:
  - something
-

**Comment by bisgaard-itis** [comment]
# Update [Microhistory]

## Done and working
- Wallets/payments for job submission

## will be done in 3 weeks
- add products to api server (login) and connect to backend
- solver log streaming

## should not be available in 3 weeks
- filtering of paginated methods

**Comment by pcrespov** [comment]
## Update 7Peaks

Main implementations are
-  https://github.com/ITISFoundation/osparc-simcore/issues/4652

**Comment by bisgaard-itis** [comment]
## Update Kobayashi Maru

- Several improvements to log streaming.
- During the sprint we encountered a load issue in the API server. In order to monitor this in the future https://github.com/ITISFoundation/osparc-simcore/pull/5193. This should also be extended to other services.

There are no current release blockers. 
In order to reduce load on API server (and prepare for metamodelling framework) it is important to tackle https://github.com/ITISFoundation/osparc-simcore/issues/4597 soon
