### ISSUE TITLE
Find suitable mechanims to gather resource usage data reliably

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#955]

**Comment by matusdrobuliak66** [comment]
TODO: Describe the solutions  @matusdrobuliak66

**Comment by matusdrobuliak66** [comment]
We want to have 2 data sources:
 - **Prometheus**
   - Here we periodically get data from Prometheus and store them in the Postgres DB, to get the real running/computational times from the docker daemon. 
   - Advantage:
     - we get the real running time from the lower-level API, therefore we can trust it 
     - we can get different useful metrics that Prometheus (cAdvisor) offers us that can be used for resource monitoring and also potentially for billing purposes (ex. container_cpu_usage_seconds_total, container_network_transmit_bytes_total)
   - Disadvantage:
     - when containers are not turned down correctly, we have hanging containers that are still running (not best for billing purposes)  
 - **Application**
   - we store when the computational/dynamic service was turned on/off based on API requests in the application. 
   - Advantage:
     - we have data source closer to the user when they start/stop the dynamic service (it helps with previous disadvantage, when the container stays handing for some reason)
   - Disadvantage:
     - we do not have the "real" container runtime (can be running for a longer time or can run more containers, or even the container might not start, because of high demand) 
     - request can be lost (ex. during the restart of the application)
     - more complex to catch all the corner cases
