### ISSUE TITLE
Publishing a study as template sometimes gives 500 (but it actually works)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#964]
**Long Story Short**
On osparc.io, publishing a study as a template gives an internal server error. This might look as a problem to a not-very-expert oSPARC user.

**Expected Behavior**
No error message is shown

**Steps to reproduce**
Not sure this always happen, but it happened now to me 2 times in a row while trying to publish a study a template on osparc.io fromt he UI.

**Environment**
osparc.io, Firefox

**Additional context**
The error seems to come when polling the status https://github.com/ITISFoundation/osparc-simcore/blob/master/services/static-webserver/client/source/class/osparc/data/PollTask.js#L140

**Comment by elisabettai** [comment]
This is a frontend problem, right, @pcrespov or @sanderegg? Nothing major, since the feature actually works, it just gives a misleading message. I vaguely re-call we had this in the past, but I couldn't find an issue in this repo.

**Comment by pcrespov** [comment]
> 

@elisabettai it is difficult to judge from the info of the issue. The link in the front-end just shows code that displays an error coming from the backend. Perhaps you have write the error or find the log in the backend?
