### ISSUE TITLE
Study doesn't open

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#969]
I ran again in the issue that I can't open my study. could somebody please have a look and unlock it?

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/ph8awpemgpgdpjzjiipxe8oqto) *by `@msteiner`*._

its on tip-staging

study uuid: 669b1262-adc9-11ed-89ac-02420a0b0171

**Comment by elisabettai** [comment]
@GitHK, close and briefly describe if you found something relevant/worth following-up

**Comment by GitHK** [comment]
Looks like the same issue which was fixed yesterday and is already in master https://github.com/ITISFoundation/osparc-simcore/pull/4280
