### ISSUE TITLE
Function to update the service from within the study is missing

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#970]
Shouldn't I see here the option to update the service? 

![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/d7a73f63-e4ab-4a5b-b283-93ed8d98b879)

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/jbt398rhyjbobkpbbkagozgccw) *by @elisabettai*._

This version has a newer version, as shown on the study card.

**Comment by odeimaiz** [comment]
atm the update view is only shown for deprecated or retired services.

Show it also when a patch version is available

**Comment by odeimaiz** [comment]
Implemented in https://github.com/ITISFoundation/osparc-simcore/pull/4303
