### ISSUE TITLE
projects folders

### ISSUE THREAD

**Issue by calys** [ITISFoundation/osparc-issues#977]
projects can be organized in folders/subfolders, like in Google Drive

shared folders
  - a folder can be shared 
  - every project placed inside a shared folder is automatically "shared"
  - (similar to Google Drive, Dropbox, etc...)

**Comment by pcrespov** [comment]
- Seems similar to ITISFoundation/osparc-issues#716

**Comment by odeimaiz** [comment]
Duplicated.

Following up in https://github.com/ITISFoundation/osparc-issues/issues/716
